### ISSUE TITLE
buildah 1.23.1 as root: error extracting layer "a08e1c4f[..]": cannot mount layer, mount label "" too large 4103 > page size 4096

### ISSUE THREAD

**Issue by totph** [containers/buildah#3708] opened 2022-01-12 19:05 UTC
**Preface**: Even though buildah is _not_ running rootless, this is also fixed by using [fuse-overlayfs](https://github.com/containers/buildah/blob/2d822034f880e802e6f7021c5e/troubleshooting.md#6-rootless-buildah-build-fails-when-using-overlayfs), here via
`export STORAGE_OPTS="overlay.mount_program=/usr/bin/fuse-overlayfs"`

It is still present in version `1.24.0-dev / Git Commit:   d744ebc4` when building from source (but leaving podman unchanged).

**Description**

On both Fedora 35 and CentOS 8 `buildah bud --layers -f Dockerfile -t my_img:20220112` run as **root** and on bare metal or in a VM fails with (output rewrapped):

```
ERRO[????] error unmounting /var/lib/containers/storage/overlay/a666d42c66a66f26cb3f46bd0414bc51ad540b8eacd8f4301188412e931533b8/merged: invalid argument
error committing container for step {Env:[PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin] Command:copy Args:[test.dat /] Flags:[] Attrs:map[] Message:COPY test.dat / Original:COPY test.dat /}:
error copying layers and metadata for container "e333fca2ffb549bd61765462f8e35733523a1a8fea9f3af48ab2ef4b02059748": initializing source containers-storage:8b2704fb4bf2e73e21d28e7acadb0828be2b25974360e270cb602049dce9eef5-working-container:
error extracting layer "a08e1c4f226de4fd3e6b82044db9c34a504b7bfbb4a6b45ca52f0283474fb9d0":
cannot mount layer, mount label "" too large 4103 > page size 4096
```

I have not seen the `mount label "" too large` error message here. Is there a system limit which could be increased?

It is always `STEP 65/75` which fails, even if `COPY ...` is replaced with a `RUN` or a different `COPY` directive. The `ERRO[????]` values are e.g. 0010, 0011, 0074, 1126, do these mean anything?

<details><summary><b>Version information</b> [..]</summary>

For CentOS 8 / Fedora 35

**Output of `rpm -q buildah`:**

`buildah-1.22.3-2.module_el8.5.0+911+f19012f9.x86_64` / `buildah-1.23.1-1.fc35.x86_64`

**Output of `buildah version`:**

```
Version:         1.22.4-dev
Go Version:      go1.16.7
Image Spec:      1.0.1-dev
Runtime Spec:    1.0.2-dev
CNI Spec:        0.4.0
libcni Version:  v0.8.1
image Version:   5.15.2
Git Commit:      
Built:           Fri Aug 27 22:26:38 2021
OS/Arch:         linux/amd64
```

```
Version:         1.23.1
Go Version:      go1.16.8
Image Spec:      1.0.1-dev
Runtime Spec:    1.0.2-dev
CNI Spec:        0.4.0
libcni Version:  v0.8.1
image Version:   5.16.0
Git Commit:      
Built:           Tue Sep 28 20:26:37 2021
OS/Arch:         linux/amd64
BuildPlatform:   linux/amd64
```

The current main branch build on Fedora 35 (removing the local buildah rpm and using the path below instead):
```
$ /local/buildah/src/github.com/containers/buildah/bin/buildah version
Version:         1.24.0-dev
Go Version:      go1.16.12
Image Spec:      1.0.2-dev
Runtime Spec:    1.0.2-dev
CNI Spec:        1.0.0
libcni Version:  v1.0.1
image Version:   5.18.0
Git Commit:      d744ebc4
Built:           Wed Jan 12 19:31:29 2022
OS/Arch:         linux/amd64
BuildPlatform:   linux/amd64
```

**Output of `cat /etc/os-release`:**

```
NAME="CentOS Linux"
VERSION="8"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Linux 8"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"
CENTOS_MANTISBT_PROJECT="CentOS-8"
CENTOS_MANTISBT_PROJECT_VERSION="8"
```

```
NAME="Fedora Linux"
VERSION="35 (Thirty Five)"
ID=fedora
VERSION_ID=35
VERSION_CODENAME=""
PLATFORM_ID="platform:f35"
PRETTY_NAME="Fedora Linux 35 (Thirty Five)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:35"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f35/system-administrators-guide/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=35
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=35
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
```

**Output of `uname -a`:**

```
Linux buildc8 4.18.0-348.7.1.el8_5.x86_64 #1 SMP Wed Dec 22 13:25:12 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

```
Linux buildf35 5.15.13-200.fc35.x86_64 #1 SMP Wed Jan 5 16:39:13 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

**Output of `cat /etc/containers/storage.conf  | grep -v '#' | grep -v '^$'`:**

```
[storage]
driver = "overlay"
runroot = "/run/containers/storage"
graphroot = "/var/lib/containers/storage"
[storage.options]
additionalimagestores = []
[storage.options.overlay]
mountopt = "nodev,metacopy=on"
[storage.options.thinpool]
```

(identical on CentOS / Fedora)

</details>

**Comment by flouthoc** [comment] 2022-01-13 11:03
@totph Thanks for creating the issue

How does your `Dockerfile` looks like i mean how many steps do you have ? I am assuming its a single stage with too many `RUN` statements in that single stage.

I believe each new `RUN` carries `lower` from the previous run as well.  I think in your case the original options flag `lowerdir` for `overlay` keeps on increasing with new `RUN` and eventually it exceeds `4103` which is really odd.

My suspect is `lowerdir=` is breaching the limit in your case.

Again this is my speculation.

**Could you try switching into multiple `stages` after few `RUN`.**

cc @giuseppe @nalind

**Comment by flouthoc** [comment] 2022-01-13 11:22
Yes I think that's the issue i was able to reproduce this. Specially `lowerdir` is increased when you are using `--layers`  @totph consider splitting into stages.

**Comment by flouthoc** [comment] 2022-01-13 11:38
> Could you try switching into multiple stages after few RUN.

I verified that this fixes my reproducer.

**Comment by giuseppe** [comment] 2022-01-13 11:45
we could try some tricks to reduce the length of `lowerdir` but realistically running overlay with that many layers is expensive at runtime too, since each lookup needs to iterate all that directories.

The limit cannot be increased.  The data argument in the mount syscall uses a memory page.

**Comment by totph** [comment] 2022-01-14 18:21
Thank you for investigating! Though checking the `mount` output after a failure I notice that  the number of `:/..` paths is exactly that of the failed `STEP` (here 65), but the length of the `lowerdir=...` argument of the overlay volume is only ~1800, nowhere near 4096.

When I start a new `Containerfile` with the hash from before the failure, e.g. `FROM 377b19b...` I immediately run into the same problem with the next command (even rebooting to get rid of any leftover mounts). Also, it doesn't seem possible to `buildah commit` this hash to a local image.

Splitting this into multiple stages `FROM centos:8 as base_os_c8` and then `FROM base_os_c8` fails after 50 + 15 = 65 steps again:

`[2/2] STEP 15/25: COPY test.dat /` -> `mount label "" too large`

Could you elaborate on the multiple stage approach?

**Comment by flouthoc** [comment] 2022-01-14 19:45
@totph Thanks for confirming yes but `64` is the number where `native overlay` collapses after stacking layers.

> but the length of the lowerdir=... argument of the overlay volume is only ~1800, nowhere near 4096.

That's because you are checking the mount option of `65`'th run where the error is actually printed but the root of the problem was  `64`th run. If you instrument code by a bit you can actually see the data.

```diff
diff --git a/vendor/github.com/containers/storage/drivers/overlay/overlay.go b/vendor/github.com/containers/storage/drivers/overlay/overlay.go
index 15ba5746..2770310a 100644
--- a/vendor/github.com/containers/storage/drivers/overlay/overlay.go
+++ b/vendor/github.com/containers/storage/drivers/overlay/overlay.go
@@ -1524,6 +1524,8 @@ func (d *Driver) get(id string, disableShifting bool, options graphdriver.MountO
                return "", err
        }
 
+       fmt.Printf("mountData %+v\n", len(mountData));
+       fmt.Printf("mountData %+v\n", mountData);
```

> Splitting this into multiple stages FROM centos:8 as base_os_c8 and then FROM base_os_c8 fails after 50 + 15 = 65 steps again:

This is not what i meant. You are reusing layers here. By multi-stating I meant don't reuse the `stage` just copy data from older stages.

```Dockerfile
FROM centos:8 as base_os_c8
RUN do something something
RUN do something something
# Your 50 steps

FROM centos:8
COPY --from=base_os_c8 /some/path /dest/path
# Your 15 steps
```

@totph Please try this ^

**Comment by totph** [comment] 2022-01-18 17:55
I see, thanks. Adding the prefix `/var/lib/containers/storage/overlay/` to `l/D5PHTJVW2Z7QD6CI7GSVV5NUOC` is what doubles the mountData length. A quick workaround is setting `graphroot = "/tmp/s"` in the `/etc/containers/storage.conf`. But then `podman` (v3.4.4) doesn't see it and the data has to be copied to `/var/lib/containers` (or pushed to a registry I presume). The podman overlay mount however does not use the `/var/lib/containers/storage/overlay/` prefix. Is that a fusefs vs. kernel overlayfs thing?

Unfortunately symlinks from `/tmp/s` to `/var/..` are automatically resolved, so the storage has to actually reside there. If they are resolved by `buildah`, might that be an opt-in fix? Or if the kernel does not accept `lowerdir=` symlink arguments, then maybe a bind mount (which requires root)? The config mentions an even longer `$HOME/.local/share/containers/storage` path for rootless, that would reduce the number of usable layers even more. Also, hashes might use `a-z` in addition to `0-9A-Z` and encode the same information but reducing the length from 26 to 16.

Here `COPY --from=` does not help because only individual files can be copied. The first action is installing various large packages, so `COPY --from=img /* /` would be required. Using an intermediate file via `buildah save/load` does not work because these commands are not supported.

Is there another way to collapse layers into a single one?

**Comment by flouthoc** [comment] 2022-01-18 18:40
@totph Then two immediate solutions i could think of is

* Try reducing your `RUNs` using `&&` i.e merge multiple `RUN` into one.
```dockerfille
RUN something && something
```

* Split your whole build into two seperate builds and squash the first one.

```dockerfile
FROM centos:8 as base_os_c8
... your 50 steps
```
`buildah build --squash -t firstphase .`

```dockerfile
FROM firstphase
...

`buildah build -t finalbuild .`


Btw this issue is a really good `RFC` for inline `--squash`.

**Comment by totph** [comment] 2022-01-27 19:25
Thank you, splitting the build process into two phases with `--squash` allows us to keep the fine grained single `RUN` and `COPY` lines. And indeed, an inline `SQUASH` would help, the `mount label too large` error message could then suggest that.

I noticed that using `--layers --squash` in combination does not make sense as all the "new layers [are squashed] into a single new layer". To still get caching of intermediate steps first one run without `--squash` seems to be required.

**Comment by flouthoc** [comment] 2022-01-27 19:50
> Thank you, splitting the build process into two phases with `--squash` allows us to keep the fine grained single `RUN` and `COPY` lines. And indeed, an inline `SQUASH` would help, the `mount label too large` error message could then suggest that.
> 

@totph No issues yes this workaround would make things work for now.

> I noticed that using `--layers --squash` in combination does not make sense as all the "new layers [are squashed] into a single new layer". To still get caching of intermediate steps first one run without `--squash` seems to be required.

We do have caching in squash as well it was added here: https://github.com/containers/buildah/pull/3674

**Comment by flouthoc** [comment] 2022-01-27 19:51
@totph If your issue is resolved. Could you close the issue and we could still continue the discussion here.

**Comment by flouthoc** [comment] 2022-02-07 12:42
@totph I'm closing this since this looks resolved.

**Closed by flouthoc** 2022-02-07 12:42 UTC

**Comment by kpouget** [comment] 2022-02-22 09:55
Hello, I bump this issue as I hit the exact same issue with multiple AI/ML Dockerfiles, let me know if I should create another ticket

see there:
- https://github.com/openshift-psap/training_results_v0.7/commit/0eda76f902f536a9e5bb4cb003b4229f4ea3bb7c
- https://github.com/openshift-psap/DeepLearningExamples/commit/713071fab18415db86dd3da9bcc7bed5658a3960 (currently trying to work around it)

the base images are `nvcr.io/nvidia/pytorch:20.06-py3`  and `nvcr.io/nvidia/pytorch:20.06-py3`, (at least 66 blobs the latest)

last time I tried, I had the same issue in OpenShift (`BuildConfig`) and Podman locally ...

would it be a solution to squash the `FROM` image? (I'll try it)
anything we could do to avoid touching the original images ...?

**Comment by flouthoc** [comment] 2022-02-22 10:20
@kpouget Unfortunately since we hit `memory page limit` I think `squash` is the best solution which is present as of now as described here: https://github.com/containers/buildah/issues/3708#issuecomment-1015706918 or optimizing your `Container/Dockerfile`

**Comment by kpouget** [comment] 2022-02-22 13:09
> Do you know if BuildConfigs have the ability to do the squashing?
[found it](https://docs.openshift.com/container-platform/4.9/cicd/builds/build-strategies.html#builds-strategy-docker-squash-layers_build-strategies), but without luck :(
```
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: tensorflow-base
spec:
  output:
    to:
      kind: ImageStreamTag
      name: aiml:tensorflow-20.06-tf1-py3
  source:
    dockerfile: |2
      FROM nvcr.io/nvidia/tensorflow:20.06-tf1-py3
    type: Dockerfile
  strategy:
    dockerStrategy:
      imageOptimizationPolicy: SkipLayers
      from:
        kind: DockerImage
        name: nvcr.io/nvidia/tensorflow:20.06-tf1-py3
    type: Docker
  triggers:
  - type: ConfigChange
```
```
STEP 1/3: FROM nvcr.io/nvidia/tensorflow:20.06-tf1-py3
STEP 2/3: ENV "OPENSHIFT_BUILD_NAME"="tensorflow-base-1" "OPENSHIFT_BUILD_NAMESPACE"="matrix-benchmarking"
STEP 3/3: LABEL "io.openshift.build.name"="tensorflow-base-1" "io.openshift.build.namespace"="matrix-benchmarking"
COMMIT temp.builder.openshift.io/matrix-benchmarking/tensorflow-base-1:ae623069
[...]: error copying layers and metadata for container "7fc97b9ae59548c778c701915520cd594168a91bdb326c1ba49751c8049198a0": initializing source containers-storage:tensorflow-working-container: error creating new image source "containers-storage:tensorflow-working-container": error extracting layer "8ade4dd914184557465403436058427439a06a5081492e
```

**Comment by ThanatosDi** [comment] 2022-03-25 06:45
I want to move from docker to podman for develope
I also have this problem when I build container from Laradock php-fpm
How can I fix this problem?
```bash
STEP 123/177: RUN if [ ${INSTALL_ADDITIONAL_LOCALES} = true ]; then     apt-get install -yqq locales     && echo '' >> /usr/share/locale/locale.alias     && temp="${ADDITIONAL_LOCALES%\"}"     && temp="${temp#\"}"     && for i in ${temp}; do sed -i "/$i/s/^#//g" /etc/locale.gen; done     && locale-gen ;fi
Error: error committing container for step {Env:[INSTALL_MYSQLI=true INSTALL_IONCUBE=false INSTALL_PCOV=false INSTALL_XHPROF=false INSTALL_SOAP=false INSTALL_LDAP=false INSTALL_RDKAFKA=false INSTALL_ADDITIONAL_LOCALES=false IMAGEMAGICK_VERSION=latest INSTALL_XDEBUG=true INSTALL_PHALCON=false INSTALL_GEARMAN=false INSTALL_TAINT=false INSTALL_OCI8=false INSTALL_AMQP=false INSTALL_ENCHANT=false INSTALL_POSTGIS=false ADDITIONAL_LOCALES=en_US.UTF-8 es_ES.UTF-8 fr_FR.UTF-8 INSTALL_SWOOLE=false INSTALL_INTL=true INSTALL_GMP=false INSTALL_CASSANDRA=false INSTALL_EXIF=false INSTALL_FAKETIME=false LARADOCK_PHP_VERSION=7.4 INSTALL_PCNTL=false INSTALL_GHOSTSCRIPT=false INSTALL_IMAP=false INSTALL_MEMCACHED=true INSTALL_PHPDBG=false INSTALL_PHPREDIS=true INSTALL_IMAGEMAGICK=true INSTALL_BZ2=false INSTALL_SMB=false INSTALL_PGSQL=false INSTALL_BCMATH=true INSTALL_GNUPG=false INSTALL_BLACKFIRE=false INSTALL_SSH2=false INSTALL_PG_CLIENT=false INSTALL_YAML=false INSTALL_MONGO=true INSTALL_APCU=false INSTALL_XSL=false INSTALL_OPCACHE=true ORACLE_INSTANT_CLIENT_MIRROR=https://github.com/diogomascarenha/oracle-instantclient/raw/master/ INSTALL_IMAGE_OPTIMIZERS=true INSTALL_CALENDAR=false INSTALL_MSSQL=false INSTALL_GETTEXT=false CHANGE_SOURCE=false LARADOCK_PHALCON_VERSION=4.0.5 INSTALL_AEROSPIKE=false PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin PHPIZE_DEPS=autoconf 		dpkg-dev 		file g++ 		gcc 		libc-dev 		make 		pkg-config 		re2c PHP_INI_DIR=/usr/local/etc/php PHP_CFLAGS=-fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 PHP_CPPFLAGS=-fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 PHP_LDFLAGS=-Wl,-O1 -pie GPG_KEYS=42670A7FE4D0441C8E4632349E4FDC074A4EF02D 5A52880781F755608BF815FC910DEB46F53EA312 PHP_VERSION=7.4.28 PHP_URL=https://www.php.net/distributions/php-7.4.28.tar.xz PHP_ASC_URL=https://www.php.net/distributions/php-7.4.28.tar.xz.asc PHP_SHA256=9cc3b6f6217b60582f78566b3814532c4b71d517876c25013ae51811e65d8fce DEBIAN_FRONTEND=noninteractive LD_LIBRARY_PATH=/opt/oracle/instantclient_12_1 OCI_HOME=/opt/oracle/instantclient_12_1 OCI_LIB_DIR=/opt/oracle/instantclient_12_1 OCI_INCLUDE_DIR=/opt/oracle/instantclient_12_1/sdk/include OCI_VERSION=12] Command:run Args:[if [ ${INSTALL_ADDITIONAL_LOCALES} = true ]; then     apt-get install -yqq locales     && echo '' >> /usr/share/locale/locale.alias     && temp="${ADDITIONAL_LOCALES%\"}"     && temp="${temp#\"}"     && for i in ${temp}; do sed -i "/$i/s/^#//g" /etc/locale.gen; done     && locale-gen ;fi] Flags:[] Attrs:map[] Message:RUN if [ ${INSTALL_ADDITIONAL_LOCALES} = true ]; then     apt-get install -yqq locales     && echo '' >> /usr/share/locale/locale.alias     && temp="${ADDITIONAL_LOCALES%\"}"     && temp="${temp#\"}"     && for i in ${temp}; do sed -i "/$i/s/^#//g" /etc/locale.gen; done     && locale-gen ;fi Original:RUN if [ ${INSTALL_ADDITIONAL_LOCALES} = true ]; then     apt-get install -yqq locales     && echo '' >> /usr/share/locale/locale.alias     && temp="${ADDITIONAL_LOCALES%\"}"     && temp="${temp#\"}"     && for i in ${temp}; do sed -i "/$i/s/^#//g" /etc/locale.gen; done     && locale-gen ;fi}: error copying layers and metadata for container "e0ed2e455cedd70b7967a5fee53ffc31c0396c5252a9ec6a9e92ba63539a616b": initializing source containers-storage:2c9f97ac8c002ba33610523aa2da3b793f39067f3ca96668b4b64f78d3a290e1-working-container: error extracting layer "0408ec153e6bb8043eb45e6ab5fd8fffbdc8f758a69441ae844ee8a1f20040b3": cannot mount layer, mount label "system_u:object_r:container_file_t:s0:c411,c762" too large 4161 > page size 4096
```
podman info
```bash
host:
  arch: arm64
  buildahVersion: 1.24.1
  cgroupControllers:
  - cpuset
  - cpu
  - io
  - memory
  - pids
  - misc
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.1.0-2.fc35.aarch64
    path: /usr/bin/conmon
    version: 'conmon version 2.1.0, commit: '
  cpus: 1
  distribution:
    distribution: fedora
    variant: coreos
    version: "35"
  eventLogger: journald
  hostname: localhost.localdomain
  idMappings:
    gidmap: null
    uidmap: null
  kernel: 5.15.18-200.fc35.aarch64
  linkmode: dynamic
  logDriver: journald
  memFree: 1178517504
  memTotal: 2048176128
  networkBackend: netavark
  ociRuntime:
    name: crun
    package: crun-1.4.2-1.fc35.aarch64
    path: /usr/bin/crun
    version: |-
      crun version 1.4.2
      commit: f6fbc8f840df1a414f31a60953ae514fa497c748
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: false
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: true
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.12-2.fc35.aarch64
    version: |-
      slirp4netns version 1.1.12
      commit: 7a104a101aa3278a2152351a082a6df71f57c9a3
      libslirp: 4.6.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.3
  swapFree: 0
  swapTotal: 0
  uptime: 1h 13m 24.04s (Approximately 0.04 days)
plugins:
  log:
  - k8s-file
  - none
  - passthrough
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - docker.io
store:
  configFile: /etc/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mountopt: nodev,metacopy=on
  graphRoot: /var/lib/containers/storage
  graphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  imageCopyTmpDir: /var/tmp
  imageStore:
    number: 299
  runRoot: /run/containers/storage
  volumePath: /var/lib/containers/storage/volumes
version:
  APIVersion: 4.0.2
  Built: 1646319530
  BuiltTime: Thu Mar  3 22:58:50 2022
  GitCommit: ""
  GoVersion: go1.16.14
  OsArch: linux/arm64
  Version: 4.0.2
```

**Comment by rhatdan** [comment] 2022-03-25 11:41
@flouthoc @giuseppe thoughts?

**Comment by flouthoc** [comment] 2022-03-25 11:47
I am not sure but if its possible and we can convert lowerdir path to relatives it should help.

**Comment by jfilak** [comment] 2022-05-10 09:22
This issue is annoying me also in RHEL 8.5 :(

**Comment by giuseppe** [comment] 2022-05-10 09:44
how many layers are you using for your image?

**Comment by filak-sap** [comment] 2022-05-10 10:54
Well, I guess more than 70 but it fails on the 37th :D

**Comment by flouthoc** [comment] 2022-05-10 10:59
@filak-sap Looks like your page size is even lower than the issue reported above cause it usually fails on `65`th layer.
