### ISSUE TITLE
Empty images created with overlay mount

### ISSUE THREAD

**Issue by nhojjohn** [containers/buildah#4093] opened 2022-07-06 12:17 UTC
**Description**

I've have been building container images using buildah.  I recently started doing this on a different server and found my images were empty (or more accurately 2.34kb).  The failure appears to be silent.

My example steps are to run the following within "buildah unshare"
```
CONT=$(buildah from scratch)
MNT=$(buildah mount $CONT)
# create some content
dd if=/dev/zero of=$MNT/file count=1 bs=10M
buildah umount $CONT
buildah --log-level debug commit $CONT foo
buildah images foo
```
This should show a image with the added content
```
REPOSITORY      TAG      IMAGE ID       CREATED        SIZE
localhost/foo   latest   4f1b787b1b5a   1 second ago   10.5 MB
```

instead I get an empty container
```
REPOSITORY      TAG      IMAGE ID       CREATED         SIZE
localhost/foo   latest   e7f614869b5b   2 seconds ago   2.34 KB
```

When I reconfigure podman storage.comf to use fuse-overlayfs it works as before.

But additionally when I run the same build *on the same server and container config* as my interactive user it also works as before without modifying storage.conf.  The failures happen when running as  "build" user  which I sudo to (and also runs github actions-runner). Comparing the output of buildah system between the two users the config seems to be identical.

The main difference I can see is that the empty images are created by a user I sudo to.  The logs show the following differences of overlay path
```DEBU[0000] parsed reference into "[overlay@/home/build/.local/share/containers/storage+/var/tmp/containers-user-1007/containers]localhost/foo:latest" ```
to
```DEBU[0000] parsed reference into "[overlay@/home/john/.local/share/containers/storage+/run/user/1002/containers]localhost/foo:latest" ```

This is presumably a result in the difference in login?

The former failed run also showing the wrong number of bytes
```DEBU[0000] layer "ba949599f2947a8a4cdfe40687cf305575b5aed637b6ba6e04848fa1f1947fa5" size is 1024 bytes, uncompressed digest sha256:5f70bf18a086007016e948b04aed3b82103a36bea41755b6cddfaf10ace3c6ef, possibly-compressed digest sha256:5f70bf18a086007016e948b04aed3b82103a36bea41755b6cddfaf10ace3c6ef ```

The other notable difference is the successful run finishes with
```INFO[0000] failed to shutdown storage: "A layer is mounted: layer is in use by a container"``` whilst the failing one doesn't print this.

I also see the following in my dmesg, although I can't tie them to a particular buildah command (and there are only three)
```
[Wed Jul  6 10:44:09 2022] overlayfs: upper fs does not support xattr, falling back to index=off and metacopy=off.
[Wed Jul  6 11:44:21 2022] overlayfs: upper fs does not support xattr, falling back to index=off and metacopy=off.
[Wed Jul  6 12:39:45 2022] overlayfs: upper fs does not support xattr, falling back to index=off and metacopy=off.
```

Some other details
* The server has selinux in permissive/targeted
* The server has xfs as root filesystem

** Logs from empty commit as "build" user are shown

```
# buildah --log-level debug commit $CONT foo
DEBU[0000] Cached value indicated that overlay is supported 
DEBU[0000] [graphdriver] trying provided driver "overlay" 
DEBU[0000] Cached value indicated that overlay is supported 
DEBU[0000] Cached value indicated that metacopy is not being used 
DEBU[0000] Cached value indicated that native-diff is usable 
DEBU[0000] backingFs=xfs, projectQuotaSupported=false, useNativeDiff=true, usingMetacopy=false 
DEBU[0000] Loading registries configuration "/home/build/.config/containers/registries.conf" 
DEBU[0000] parsed reference into "[overlay@/home/build/.local/share/containers/storage+/var/tmp/containers-user-1007/containers]localhost/foo:latest" 
DEBU[0000] committing image with reference "containers-storage:[overlay@/home/build/.local/share/containers/storage+/var/tmp/containers-user-1007/containers]localhost/foo:latest" is allowed by policy 
DEBU[0000] layer list: ["ba949599f2947a8a4cdfe40687cf305575b5aed637b6ba6e04848fa1f1947fa5"] 
DEBU[0000] using "/var/tmp/buildah2808715040" to hold temporary data 
DEBU[0000] [graphdriver] trying provided driver "overlay" 
DEBU[0000] Cached value indicated that overlay is supported 
DEBU[0000] Cached value indicated that metacopy is not being used 
DEBU[0000] backingFs=xfs, projectQuotaSupported=false, useNativeDiff=true, usingMetacopy=false 
DEBU[0000] Tar with options on /home/build/.local/share/containers/storage/overlay/ba949599f2947a8a4cdfe40687cf305575b5aed637b6ba6e04848fa1f1947fa5/diff 
DEBU[0000] layer "ba949599f2947a8a4cdfe40687cf305575b5aed637b6ba6e04848fa1f1947fa5" size is 1024 bytes, uncompressed digest sha256:5f70bf18a086007016e948b04aed3b82103a36bea41755b6cddfaf10ace3c6ef, possibly-compressed digest sha256:5f70bf18a086007016e948b04aed3b82103a36bea41755b6cddfaf10ace3c6ef 
DEBU[0000] OCIv1 config = {"created":"2022-07-06T11:54:17.242692759Z","architecture":"amd64","os":"linux","config":{"Labels":{"io.buildah.version":"1.24.2"}},"rootfs":{"type":"layers","diff_ids":["sha256:5f70bf18a086007016e948b04aed3b82103a36bea41755b6cddfaf10ace3c6ef"]},"history":[{"created":"2022-07-06T11:54:17.244284382Z","created_by":"/bin/sh"}]} 
DEBU[0000] OCIv1 manifest = {"schemaVersion":2,"mediaType":"application/vnd.oci.image.manifest.v1+json","config":{"mediaType":"application/vnd.oci.image.config.v1+json","digest":"sha256:c897c3545880a78729d081fad8b0dae9e3cfebd9ae8ed1c4abe6d92c46aa0585","size":326},"layers":[{"mediaType":"application/vnd.oci.image.layer.v1.tar","digest":"sha256:5f70bf18a086007016e948b04aed3b82103a36bea41755b6cddfaf10ace3c6ef","size":1024}],"annotations":{"org.opencontainers.image.base.digest":"","org.opencontainers.image.base.name":""}} 
DEBU[0000] Docker v2s2 config = {"created":"2022-07-06T11:54:17.242692759Z","container":"cff1a423556e5e3a70974b6584e0634f78c765fc903e1d8ae995495e7d6afd3f","container_config":{"Hostname":"","Domainname":"","User":"","AttachStdin":false,"AttachStdout":false,"AttachStderr":false,"Tty":false,"OpenStdin":false,"StdinOnce":false,"Env":null,"Cmd":null,"Image":"","Volumes":null,"WorkingDir":"","Entrypoint":null,"OnBuild":[],"Labels":{"io.buildah.version":"1.24.2"}},"config":{"Hostname":"","Domainname":"","User":"","AttachStdin":false,"AttachStdout":false,"AttachStderr":false,"Tty":false,"OpenStdin":false,"StdinOnce":false,"Env":null,"Cmd":null,"Image":"","Volumes":null,"WorkingDir":"","Entrypoint":null,"OnBuild":[],"Labels":{"io.buildah.version":"1.24.2"}},"architecture":"amd64","os":"linux","rootfs":{"type":"layers","diff_ids":["sha256:5f70bf18a086007016e948b04aed3b82103a36bea41755b6cddfaf10ace3c6ef"]},"history":[{"created":"2022-07-06T11:54:17.244284382Z","created_by":"/bin/sh"}]} 
DEBU[0000] Docker v2s2 manifest = {"schemaVersion":2,"mediaType":"application/vnd.docker.distribution.manifest.v2+json","config":{"mediaType":"application/vnd.docker.container.image.v1+json","size":957,"digest":"sha256:9fbaa2d3f6d4d7e3e0ea1571eb1568311ba066979deaf1ffea4eba181fcfaffb"},"layers":[{"mediaType":"application/vnd.docker.image.rootfs.diff.tar","size":1024,"digest":"sha256:5f70bf18a086007016e948b04aed3b82103a36bea41755b6cddfaf10ace3c6ef"}]} 
DEBU[0000] Using blob info cache at /home/build/.local/share/containers/cache/blob-info-cache-v1.boltdb 
DEBU[0000] IsRunningImageAllowed for image containers-storage: 
DEBU[0000]  Using transport "containers-storage" policy section  
DEBU[0000]  Requirement 0: allowed                      
DEBU[0000] Overall: allowed                             
DEBU[0000] start reading config                         
DEBU[0000] finished reading config                      
Getting image source signatures
DEBU[0000] Manifest has MIME type application/vnd.oci.image.manifest.v1+json, ordered candidate list [application/vnd.oci.image.manifest.v1+json, application/vnd.docker.distribution.manifest.v2+json, application/vnd.docker.distribution.manifest.v1+prettyjws, application/vnd.docker.distribution.manifest.v1+json] 
DEBU[0000] ... will first try using the original manifest unmodified 
DEBU[0000] reading layer "sha256:5f70bf18a086007016e948b04aed3b82103a36bea41755b6cddfaf10ace3c6ef" 
DEBU[0000] No compression detected                      
DEBU[0000] Using original blob without modification     
Copying blob 5f70bf18a086 done  
DEBU[0000] Applying tar in /home/build/.local/share/containers/storage/overlay/5f70bf18a086007016e948b04aed3b82103a36bea41755b6cddfaf10ace3c6ef/diff 
DEBU[0000] finished reading layer "sha256:5f70bf18a086007016e948b04aed3b82103a36bea41755b6cddfaf10ace3c6ef" 
DEBU[0000] No compression detected                      
DEBU[0000] Using original blob without modification     
Copying config c897c35458 done  
Writing manifest to image destination
Storing signatures
DEBU[0000] setting image creation date to 2022-07-06 11:54:17.242692759 +0000 UTC 
DEBU[0000] created new image ID "c897c3545880a78729d081fad8b0dae9e3cfebd9ae8ed1c4abe6d92c46aa0585" 
DEBU[0000] saved image metadata "{\"signatures-sizes\":{\"sha256:b5df077b0d8ba573bb8f072b9525281745481edb580a6714f25d0bafc9f5fa28\":[]}}" 
DEBU[0000] set names of image "c897c3545880a78729d081fad8b0dae9e3cfebd9ae8ed1c4abe6d92c46aa0585" to [localhost/foo:latest] 
DEBU[0000] wrote image localhost/foo:latest@sha256:b5df077b0d8ba573bb8f072b9525281745481edb580a6714f25d0bafc9f5fa28 with ID c897c3545880a78729d081fad8b0dae9e3cfebd9ae8ed1c4abe6d92c46aa0585 
c897c3545880a78729d081fad8b0dae9e3cfebd9ae8ed1c4abe6d92c46aa0585
DEBU[0000] Cached value indicated that overlay is supported 
DEBU[0000] [graphdriver] trying provided driver "overlay" 
DEBU[0000] Cached value indicated that overlay is supported 
DEBU[0000] Cached value indicated that metacopy is not being used 
DEBU[0000] backingFs=xfs, projectQuotaSupported=false, useNativeDiff=true, usingMetacopy=false 
DEBU[0000] shutting down the store
```

**Describe the results you expected:**
Running on same server as my interactive login
```

# buildah --log-level debug commit $CONT foo
DEBU[0000] Cached value indicated that overlay is supported 
DEBU[0000] [graphdriver] trying provided driver "overlay" 
DEBU[0000] Cached value indicated that overlay is supported 
DEBU[0000] Cached value indicated that metacopy is not being used 
DEBU[0000] Cached value indicated that native-diff is usable 
DEBU[0000] backingFs=xfs, projectQuotaSupported=false, useNativeDiff=true, usingMetacopy=false 
DEBU[0000] Loading registries configuration "/etc/containers/registries.conf" 
DEBU[0000] Loading registries configuration "/etc/containers/registries.conf.d/000-shortnames.conf" 
DEBU[0000] Loading registries configuration "/etc/containers/registries.conf.d/001-rhel-shortnames.conf" 
DEBU[0000] Loading registries configuration "/etc/containers/registries.conf.d/002-rhel-shortnames-overrides.conf" 
DEBU[0000] parsed reference into "[overlay@/home/john/.local/share/containers/storage+/run/user/1002/containers]localhost/foo:latest" 
DEBU[0000] committing image with reference "containers-storage:[overlay@/home/john/.local/share/containers/storage+/run/user/1002/containers]localhost/foo:latest" is allowed by policy 
DEBU[0000] layer list: ["c687d367c1794453fc87e8dfb0963b89aab4f309459f5244c18ecadb7d31d80c"] 
DEBU[0000] using "/var/tmp/buildah2863682188" to hold temporary data 
DEBU[0000] [graphdriver] trying provided driver "overlay" 
DEBU[0000] Cached value indicated that overlay is supported 
DEBU[0000] Cached value indicated that metacopy is not being used 
DEBU[0000] backingFs=xfs, projectQuotaSupported=false, useNativeDiff=true, usingMetacopy=false 
DEBU[0000] Tar with options on /home/john/.local/share/containers/storage/overlay/c687d367c1794453fc87e8dfb0963b89aab4f309459f5244c18ecadb7d31d80c/diff 
DEBU[0000] layer "c687d367c1794453fc87e8dfb0963b89aab4f309459f5244c18ecadb7d31d80c" size is 10487296 bytes, uncompressed digest sha256:ff9f4159f71d598515ad59961b268507cd46c287f5768fc7eb4e3607e467db63, possibly-compressed digest sha256:ff9f4159f71d598515ad59961b268507cd46c287f5768fc7eb4e3607e467db63 
DEBU[0000] OCIv1 config = {"created":"2022-07-06T11:53:14.675203492Z","architecture":"amd64","os":"linux","config":{"Labels":{"io.buildah.version":"1.24.2"}},"rootfs":{"type":"layers","diff_ids":["sha256:ff9f4159f71d598515ad59961b268507cd46c287f5768fc7eb4e3607e467db63"]},"history":[{"created":"2022-07-06T11:53:14.719181725Z","created_by":"/bin/sh"}]} 
DEBU[0000] OCIv1 manifest = {"schemaVersion":2,"mediaType":"application/vnd.oci.image.manifest.v1+json","config":{"mediaType":"application/vnd.oci.image.config.v1+json","digest":"sha256:4aaee138f72ed2dbcb836885ace4041b694733dd38bcf61e3008365eba49dc3e","size":326},"layers":[{"mediaType":"application/vnd.oci.image.layer.v1.tar","digest":"sha256:ff9f4159f71d598515ad59961b268507cd46c287f5768fc7eb4e3607e467db63","size":10487296}],"annotations":{"org.opencontainers.image.base.digest":"","org.opencontainers.image.base.name":""}} 
DEBU[0000] Docker v2s2 config = {"created":"2022-07-06T11:53:14.675203492Z","container":"362d07cccebf77ee0dbd801be5fd750acfb398a1fec343321d05f6f0916d8510","container_config":{"Hostname":"","Domainname":"","User":"","AttachStdin":false,"AttachStdout":false,"AttachStderr":false,"Tty":false,"OpenStdin":false,"StdinOnce":false,"Env":null,"Cmd":null,"Image":"","Volumes":null,"WorkingDir":"","Entrypoint":null,"OnBuild":[],"Labels":{"io.buildah.version":"1.24.2"}},"config":{"Hostname":"","Domainname":"","User":"","AttachStdin":false,"AttachStdout":false,"AttachStderr":false,"Tty":false,"OpenStdin":false,"StdinOnce":false,"Env":null,"Cmd":null,"Image":"","Volumes":null,"WorkingDir":"","Entrypoint":null,"OnBuild":[],"Labels":{"io.buildah.version":"1.24.2"}},"architecture":"amd64","os":"linux","rootfs":{"type":"layers","diff_ids":["sha256:ff9f4159f71d598515ad59961b268507cd46c287f5768fc7eb4e3607e467db63"]},"history":[{"created":"2022-07-06T11:53:14.719181725Z","created_by":"/bin/sh"}]} 
DEBU[0000] Docker v2s2 manifest = {"schemaVersion":2,"mediaType":"application/vnd.docker.distribution.manifest.v2+json","config":{"mediaType":"application/vnd.docker.container.image.v1+json","size":957,"digest":"sha256:3294d013ce005aad8440d5f0d7f151ac918355ec6fb59bebd54e02ee02a6fd8f"},"layers":[{"mediaType":"application/vnd.docker.image.rootfs.diff.tar","size":10487296,"digest":"sha256:ff9f4159f71d598515ad59961b268507cd46c287f5768fc7eb4e3607e467db63"}]} 
DEBU[0000] Using blob info cache at /home/john/.local/share/containers/cache/blob-info-cache-v1.boltdb 
DEBU[0000] IsRunningImageAllowed for image containers-storage: 
DEBU[0000]  Using transport "containers-storage" policy section  
DEBU[0000]  Requirement 0: allowed                      
DEBU[0000] Overall: allowed                             
DEBU[0000] start reading config                         
DEBU[0000] finished reading config                      
Getting image source signatures
DEBU[0000] Manifest has MIME type application/vnd.oci.image.manifest.v1+json, ordered candidate list [application/vnd.oci.image.manifest.v1+json, application/vnd.docker.distribution.manifest.v2+json, application/vnd.docker.distribution.manifest.v1+prettyjws, application/vnd.docker.distribution.manifest.v1+json] 
DEBU[0000] ... will first try using the original manifest unmodified 
DEBU[0000] reading layer "sha256:ff9f4159f71d598515ad59961b268507cd46c287f5768fc7eb4e3607e467db63" 
DEBU[0000] No compression detected                      
DEBU[0000] Using original blob without modification     
Copying blob ff9f4159f71d done  
DEBU[0000] Applying tar in /home/john/.local/share/containers/storage/overlay/ff9f4159f71d598515ad59961b268507cd46c287f5768fc7eb4e3607e467db63/diff 
DEBU[0000] finished reading layer "sha256:ff9f4159f71d598515ad59961b268507cd46c287f5768fc7eb4e3607e467db63" 
DEBU[0000] No compression detected                      
DEBU[0000] Using original blob without modification     
Copying config 4aaee138f7 done  
Writing manifest to image destination
Storing signatures
DEBU[0000] setting image creation date to 2022-07-06 11:53:14.675203492 +0000 UTC 
DEBU[0000] created new image ID "4aaee138f72ed2dbcb836885ace4041b694733dd38bcf61e3008365eba49dc3e" 
DEBU[0000] saved image metadata "{\"signatures-sizes\":{\"sha256:2c6f738c53abae3088b954efae8c7488ef2003291a6e7446d2dd80ad8fcdf6cd\":[]}}" 
DEBU[0000] set names of image "4aaee138f72ed2dbcb836885ace4041b694733dd38bcf61e3008365eba49dc3e" to [localhost/foo:latest] 
DEBU[0000] wrote image localhost/foo:latest@sha256:2c6f738c53abae3088b954efae8c7488ef2003291a6e7446d2dd80ad8fcdf6cd with ID 4aaee138f72ed2dbcb836885ace4041b694733dd38bcf61e3008365eba49dc3e 
4aaee138f72ed2dbcb836885ace4041b694733dd38bcf61e3008365eba49dc3e
DEBU[0000] Cached value indicated that overlay is supported 
DEBU[0000] shutting down the store                      
INFO[0000] failed to shutdown storage: "A layer is mounted: layer is in use by a container" 
```

**Output of `rpm -q buildah` or `apt list buildah`:**

```
buildah-1.24.2-2.module_el8.7.0+1106+45480ee0.x86_64
```

**Output of `buildah version`:**

```
buildah-1.24.2-2.module_el8.7.0+1106+45480ee0.x86_64
[root@ghrunner ~]# buildah version
Version:         1.24.2
Go Version:      go1.17.7
Image Spec:      1.0.2-dev
Runtime Spec:    1.0.2-dev
CNI Spec:        1.0.0
libcni Version:  v1.0.1
image Version:   5.19.1
Git Commit:      
Built:           Tue Mar 15 20:13:34 2022
OS/Arch:         linux/amd64
BuildPlatform:   linux/amd64

```

**Output of `podman version` if reporting a `podman build` issue:**

```
Client:       Podman Engine
Version:      4.0.2
API Version:  4.0.2
Go Version:   go1.17.7

Built:      Tue Mar 15 20:15:06 2022
OS/Arch:    linux/amd64

```

**Output of `cat /etc/*release`:**

```
CentOS Stream release 8

```

**Output of `uname -a`:**

```
Linux buildhost 4.18.0-394.el8.x86_64 #1 SMP Tue May 31 16:19:11 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

**Output of `cat /etc/containers/storage.conf`:**

Note: default from rpm
```
# This file is is the configuration file for all tools
# that use the containers/storage library. The storage.conf file
# overrides all other storage.conf files. Container engines using the
# container/storage library do not inherit fields from other storage.conf
# files.
#
#  Note: The storage.conf file overrides other storage.conf files based on this precedence:
#      /usr/containers/storage.conf
#      /etc/containers/storage.conf
#      $HOME/.config/containers/storage.conf
#      $XDG_CONFIG_HOME/containers/storage.conf (If XDG_CONFIG_HOME is set)
# See man 5 containers-storage.conf for more information
# The "container storage" table contains all of the server options.
[storage]

# Default Storage Driver, Must be set for proper operation.
driver = "overlay"

# Temporary storage location
runroot = "/run/containers/storage"

# Primary Read/Write location of container storage
# When changing the graphroot location on an SELINUX system, you must
# ensure  the labeling matches the default locations labels with the
# following commands:
# semanage fcontext -a -e /var/lib/containers/storage /NEWSTORAGEPATH
# restorecon -R -v /NEWSTORAGEPATH
graphroot = "/var/lib/containers/storage"


# Storage path for rootless users
#
# rootless_storage_path = "$HOME/.local/share/containers/storage"

[storage.options]
# Storage options to be passed to underlying storage drivers

# AdditionalImageStores is used to pass paths to additional Read/Only image stores
# Must be comma separated list.
additionalimagestores = [
]

# Remap-UIDs/GIDs is the mapping from UIDs/GIDs as they should appear inside of
# a container, to the UIDs/GIDs as they should appear outside of the container,
# and the length of the range of UIDs/GIDs.  Additional mapped sets can be
# listed and will be heeded by libraries, but there are limits to the number of
# mappings which the kernel will allow when you later attempt to run a
# container.
#
# remap-uids = 0:1668442479:65536
# remap-gids = 0:1668442479:65536

# Remap-User/Group is a user name which can be used to look up one or more UID/GID
# ranges in the /etc/subuid or /etc/subgid file.  Mappings are set up starting
# with an in-container ID of 0 and then a host-level ID taken from the lowest
# range that matches the specified name, and using the length of that range.
# Additional ranges are then assigned, using the ranges which specify the
# lowest host-level IDs first, to the lowest not-yet-mapped in-container ID,
# until all of the entries have been used for maps.
#
# remap-user = "containers"
# remap-group = "containers"

# Root-auto-userns-user is a user name which can be used to look up one or more UID/GID
# ranges in the /etc/subuid and /etc/subgid file.  These ranges will be partitioned
# to containers configured to create automatically a user namespace.  Containers
# configured to automatically create a user namespace can still overlap with containers
# having an explicit mapping set.
# This setting is ignored when running as rootless.
# root-auto-userns-user = "storage"
#
# Auto-userns-min-size is the minimum size for a user namespace created automatically.
# auto-userns-min-size=1024
#
# Auto-userns-max-size is the minimum size for a user namespace created automatically.
# auto-userns-max-size=65536

[storage.options.overlay]
# ignore_chown_errors can be set to allow a non privileged user running with
# a single UID within a user namespace to run containers. The user can pull
# and use any image even those with multiple uids.  Note multiple UIDs will be
# squashed down to the default uid in the container.  These images will have no
# separation between the users in the container. Only supported for the overlay
# and vfs drivers.
#ignore_chown_errors = "false"

# Inodes is used to set a maximum inodes of the container image.
# inodes = ""

# Path to an helper program to use for mounting the file system instead of mounting it
# directly.
#mount_program = "/usr/bin/fuse-overlayfs"

# mountopt specifies comma separated list of extra mount options
mountopt = "nodev,metacopy=on"

# Set to skip a PRIVATE bind mount on the storage home directory.
# skip_mount_home = "false"

# Size is used to set a maximum size of the container image.
# size = ""

# ForceMask specifies the permissions mask that is used for new files and
# directories.
#
# The values "shared" and "private" are accepted.
# Octal permission masks are also accepted.
#
#  "": No value specified.
#     All files/directories, get set with the permissions identified within the
#     image.
#  "private": it is equivalent to 0700.
#     All files/directories get set with 0700 permissions.  The owner has rwx
#     access to the files. No other users on the system can access the files.
#     This setting could be used with networked based homedirs.
#  "shared": it is equivalent to 0755.
#     The owner has rwx access to the files and everyone else can read, access
#     and execute them. This setting is useful for sharing containers storage
#     with other users.  For instance have a storage owned by root but shared
#     to rootless users as an additional store.
#     NOTE:  All files within the image are made readable and executable by any
#     user on the system. Even /etc/shadow within your image is now readable by
#     any user.
#
#   OCTAL: Users can experiment with other OCTAL Permissions.
#
#  Note: The force_mask Flag is an experimental feature, it could change in the
#  future.  When "force_mask" is set the original permission mask is stored in
#  the "user.containers.override_stat" xattr and the "mount_program" option must
#  be specified. Mount programs like "/usr/bin/fuse-overlayfs" present the
#  extended attribute permissions to processes within containers rather then the
#  "force_mask"  permissions.
#
# force_mask = ""

[storage.options.thinpool]
# Storage Options for thinpool

# autoextend_percent determines the amount by which pool needs to be
# grown. This is specified in terms of % of pool size. So a value of 20 means
# that when threshold is hit, pool will be grown by 20% of existing
# pool size.
# autoextend_percent = "20"

# autoextend_threshold determines the pool extension threshold in terms
# of percentage of pool size. For example, if threshold is 60, that means when
# pool is 60% full, threshold has been hit.
# autoextend_threshold = "80"

# basesize specifies the size to use when creating the base device, which
# limits the size of images and containers.
# basesize = "10G"

# blocksize specifies a custom blocksize to use for the thin pool.
# blocksize="64k"

# directlvm_device specifies a custom block storage device to use for the
# thin pool. Required if you setup devicemapper.
# directlvm_device = ""

# directlvm_device_force wipes device even if device already has a filesystem.
# directlvm_device_force = "True"

# fs specifies the filesystem type to use for the base device.
# fs="xfs"

# log_level sets the log level of devicemapper.
# 0: LogLevelSuppress 0 (Default)
# 2: LogLevelFatal
# 3: LogLevelErr
# 4: LogLevelWarn
# 5: LogLevelNotice
# 6: LogLevelInfo
# 7: LogLevelDebug
# log_level = "7"

# min_free_space specifies the min free space percent in a thin pool require for
# new device creation to succeed. Valid values are from 0% - 99%.
# Value 0% disables
# min_free_space = "10%"

# mkfsarg specifies extra mkfs arguments to be used when creating the base
# device.
# mkfsarg = ""

# metadata_size is used to set the `pvcreate --metadatasize` options when
# creating thin devices. Default is 128k
# metadata_size = ""

# Size is used to set a maximum size of the container image.
# size = ""

# use_deferred_removal marks devicemapper block device for deferred removal.
# If the thinpool is in use when the driver attempts to remove it, the driver
# tells the kernel to remove it as soon as possible. Note this does not free
# up the disk space, use deferred deletion to fully remove the thinpool.
# use_deferred_removal = "True"

# use_deferred_deletion marks thinpool device for deferred deletion.
# If the device is busy when the driver attempts to delete it, the driver
# will attempt to delete device every 30 seconds until successful.
# If the program using the driver exits, the driver will continue attempting
# to cleanup the next time the driver is used. Deferred deletion permanently
# deletes the device and all data stored in device will be lost.
# use_deferred_deletion = "True"

# xfs_nospace_max_retries specifies the maximum number of retries XFS should
# attempt to complete IO when ENOSPC (no space) error is returned by
# underlying storage device.
# xfs_nospace_max_retries = "0"

```

**Comment by flouthoc** [comment] 2022-07-07 15:20
Hi @nhojjohn , Thanks for creating the issue. I will take a look at this.

**Comment by UlrichLohrmann** [comment] 2022-07-08 05:54
One more information.
I replaced the home directory of the user that produced empty images with a complete new home directory but the images created are still empty. So the problem seems to be somewhere outside the home directory and have to be specific to the Linux ID of the user that produces empty images (as with other user IDs this problem does not occur).

**Comment by UlrichLohrmann** [comment] 2022-07-08 06:06
Additional information.

The problem is during "buildah commit" command. If I start this with the option "--log-level debug" I get the following messages:

+ buildah unmount --log-level debug mokka
DEBU[0000] Cached value indicated that overlay is supported
DEBU[0000] [graphdriver] trying provided driver "overlay"
DEBU[0000] Cached value indicated that overlay is supported
DEBU[0000] Cached value indicated that metacopy is not being used
DEBU[0000] Cached value indicated that native-diff is usable
DEBU[0000] backingFs=extfs, projectQuotaSupported=false, useNativeDiff=true, usingMetacopy=false
DEBU[0000] Failed to unmount 6aa849167c4b098e283c9f0048b8e93d51773c6992dd6befc655abd8952c2fb0 overlay: /work/home/qthuin1/.local/share/containers/storage/overlay/6aa849167c4b098e283c9f0048b8e93d51773c6992dd6befc655abd8952c2fb0/merged - invalid argument
DEBU[0000] Failed to remove mountpoint 6aa849167c4b098e283c9f0048b8e93d51773c6992dd6befc655abd8952c2fb0 overlay: /work/home/qthuin1/.local/share/containers/storage/overlay/6aa849167c4b098e283c9f0048b8e93d51773c6992dd6befc655abd8952c2fb0/merged - directory not empty
fac40992a23edbd0810ca692a78926703346b198c26a153711fe554bf498e956
DEBU[0000] Cached value indicated that overlay is supported
DEBU[0000] [graphdriver] trying provided driver "overlay"
.
.
.

**Comment by UlrichLohrmann** [comment] 2022-07-08 08:36
Additional information.

I rolled back my buildah version to

`
buildah version 1.23.1 (image-spec 1.0.1-dev, runtime-spec 1.0.2-dev)
`

When running buildah --version after downgrade to 1.23.1 I got the following message:

`
WARN[0000] Failed to decode the keys ["network.network_backend"] from "/usr/share/containers/containers.conf".
`

So I added a comment character to that line in /usr/share/containers/containers.conf

.
[network]
.
#network_backend = ""
#network_backend = "cni"
.


Now new Images are not longer empty using the same Linux account that created empty images before the downgrade of Buildah.

**Comment by flouthoc** [comment] 2022-07-08 08:41
@UlrichLohrmann @nhojjohn I don't think this bug persists on upstream or more recent versions. I tried this `rootless+native overlay`

```console
[fl@fedora bin]$ buildah unshare
[root@fedora bin]# CONT=$(buildah from scratch)
[root@fedora bin]# MNT=$(buildah mount $CONT)
[root@fedora bin]# dd if=/dev/zero of=$MNT/file count=1 bs=10M
1+0 records in
1+0 records out
10485760 bytes (10 MB, 10 MiB) copied, 0.0062796 s, 1.7 GB/s
[root@fedora bin]# buildah umount $CONT
4bd63ada5d339775e9872a58d8e71adab29f66d013197fa9c3bee28cf5e6624e
[root@fedora bin]# buildah commit $CONT foo
Getting image source signatures
Copying blob 28a0c27d0be8 done  
Copying config 6c89ddb7b6 done  
Writing manifest to image destination
Storing signatures
6c89ddb7b634de8041213ab0b3627b02701b5ede9bc0cb257a6081050a394f62
[root@fedora bin]# buildah images foo
REPOSITORY      TAG      IMAGE ID       CREATED         SIZE
localhost/foo   latest   6c89ddb7b634   4 seconds ago   10.5 MB
[root@fedora bin]# buildah --version
buildah version 1.27.0-dev (image-spec 1.0.2-dev, runtime-spec 1.0.2-dev)
[root@fedora bin]# buildah version
Version:         1.27.0-dev
Go Version:      go1.18.3
Image Spec:      1.0.2-dev
Runtime Spec:    1.0.2-dev
CNI Spec:        1.0.0
libcni Version:  v1.1.1
image Version:   5.21.2-dev
Git Commit:      3a8223522f9cc9a997b059e2eab7d7ae517e9ffb
Built:           Fri Jul  8 13:18:43 2022
OS/Arch:         linux/amd64
BuildPlatform:   linux/amd64
[root@fedora bin]# 
```

**Comment by nhojjohn** [comment] 2022-07-08 08:50
@flouthoc  Is that example with upstream as "you" or from an account you have sudo'd to?   The above works on 1.24.2 for me too if I run it me (with a proper login).  One uses /run/user/$uid for the overlay whilst the later /var/tmp/containers-user-$uid.

**Comment by flouthoc** [comment] 2022-07-08 08:59
@nhojjohn I think i missed this bit my invocation was from a proper logged in account.

**Comment by flouthoc** [comment] 2022-07-08 09:11
I am able to reproduce the bug when invoked from a user without a login session.

**Comment by flouthoc** [comment] 2022-07-11 06:18
@UlrichLohrmann @nhojjohn Above PR https://github.com/containers/buildah/pull/4101 should fix this.

**Comment by UlrichLohrmann** [comment] 2022-07-11 06:35
What can I do to get this change? We use Red Hat Enterprise update Repositories and I think it will take a while until this change is available there? Can I change some local configuration in order to get things work as expected?

**Comment by flouthoc** [comment] 2022-07-11 07:06
@UlrichLohrmann I think you will  have to wait for a release but my idea was to manually build a buildah with needed patch and test it but no issues at all i have verified it in session without login.

**Comment by flouthoc** [comment] 2022-07-11 10:52
@nhojjohn Thanks for trying out the patch :)

**Comment by rhatdan** [comment] 2022-07-11 15:26
Is this fixed in main?  Should we close?

**Comment by flouthoc** [comment] 2022-07-11 15:31
@rhatdan I think fix for this is here so its not yet merged on upstream: https://github.com/containers/buildah/pull/4101

**Closed** 2022-07-11 17:01 UTC
