### ISSUE TITLE
Build source code failed

### ISSUE THREAD

**Issue by fanux** [containers/buildah#3907] opened 2022-04-11 07:11 UTC
```
yum install gpgme gpgme-devel btrfs-tools btrfs-progs-devel device-mapper device-mapper-devel libseccomp libseccomp-devel
make buildah
```
```
[root@iZ2ze4vo1tjx7vf1b0ab2tZ buildah]# make buildah
GO111MODULE=on go build -mod=vendor -ldflags '-X main.GitCommit=7ede3f9 -X main.buildInfo=1649660920 -X main.cniVersion=v1.0.1 ' -gcflags "" -o bin/buildah -tags "seccomp      systemd" ./cmd/buildah
# pkg-config --cflags  -- libseccomp libseccomp
Package libseccomp was not found in the pkg-config search path.
Perhaps you should add the directory containing `libseccomp.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libseccomp' found
Package libseccomp was not found in the pkg-config search path.
Perhaps you should add the directory containing `libseccomp.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libseccomp' found
pkg-config: exit status 1
# github.com/proglottis/gpgme
vendor/github.com/proglottis/gpgme/data.go:187:12: could not determine kind of name for C.gogpgme_data_seek
vendor/github.com/proglottis/gpgme/data.go:53:53: could not determine kind of name for C.gpgme_off_t
cgo: 
gcc errors for preamble:
In file included from vendor/github.com/proglottis/gpgme/data.go:6:0:
./go_gpgme.h:15:1: error: unknown type name 'gpgme_off_t'
 extern gpgme_off_t gogpgme_data_seek(gpgme_data_t dh, gpgme_off_t offset, int whence);
 ^
./go_gpgme.h:15:55: error: unknown type name 'gpgme_off_t'
 extern gpgme_off_t gogpgme_data_seek(gpgme_data_t dh, gpgme_off_t offset, int whence);
                                                       ^

make: *** [bin/buildah] 错误 2
```

**Comment by flouthoc** [comment] 2022-04-11 07:26
Hi @fanux , Thanks for creating the issue following issues seems to be duplicate of https://github.com/containers/buildah/issues/3839 . Could you take a look at the link which i have shared. I am closing this issue since this seems to be a duplicate but please feel free to re-open if something is unresolved.

**Closed by flouthoc** 2022-04-11 07:26 UTC

**Comment by fanux** [comment] 2022-04-11 07:46
```
make BUILDTAGS=containers_image_openpgp
```
Works, thanks!
