### ISSUE TITLE
buildah bud error adding layer /var/lib/apt/lists/auxfiles/.wh..wh..opq: invalid argument

### ISSUE THREAD

**Issue by Yannik** [containers/buildah#2327] opened 2020-04-23 22:06 UTC
**Description**

Trying to build with a Dockerfile which uses `FROM docker.io/php:7.3-fpm` fails with the following error:
```
error creating build container: Error committing the finished image: error adding layer with blob "sha256:3625177cdabb7600f00575d5a11d128cad1705d0b7e62b3720e150fbfde24962": Error processing tar file(exit status 1): open /var/lib/apt/lists/auxfiles/.wh..wh..opq: invalid argument
```
**Steps to reproduce the issue:**
1. podman run --device /dev/fuse --rm -it quay.io/buildah/stable sh
2. echo 'FROM docker.io/php:7.3-fpm' > Dockerfile
3. buildah bud

**Describe the results you received:**
The aforementioned error

**Describe the results you expected:**
No error.

**Output of `rpm -q buildah` or `apt list buildah`:**

```
buildah-1.14.3-1.fc31.x86_64
```

`podman-1.9.0-1.fc31.x86_64` is installed on the host.

Other Information: I found a similar issue with kaniko: https://github.com/GoogleContainerTools/kaniko/issues/1073#issuecomment-613641983

This also happens if I use `podman run --privileged --rm -it quay.io/buildah/stable sh`.
Also happens when I enable cgroupsv2.

**Comment by giuseppe** [comment] 2020-04-27 07:19
I assumed it was an issue in fuse-overlayfs but it doesn't seem the case, so I've moved the issue back to buildah.

Using fuse-overlayfs on top of fuse-overlayfs doesn't work.  The inner fuse-overlayfs cannot create whiteout files.  You need to use a volume for `/var/lib/containers/storage`.

**Comment by rhatdan** [comment] 2020-04-27 14:09
Is that the solution to this issue then, and should we close this issue?

**Comment by Yannik** [comment] 2020-04-27 14:22
>  You need to use a volume for /var/lib/containers/storage.

This does work as a workaround, but shouldn't the issue itself be fixed?

**Comment by rhatdan** [comment] 2020-04-27 20:30
Ok I saw this earlier today when trying to run buildah inside of a rootless container, when the system was running out of UIDs.

**Comment by rhatdan** [comment] 2020-04-27 20:35
The issue is you are trying to use a usernamespace while in a user namespace with similar size.  
Perhaps we should cut down the UID Map inside of the container down from 65k.

If inside of the container we setup /etc/subuid and /etc/subgid to map 5000 UIDs starting at UID 5000, it might work.  Currently we attempt to do it starting at 100000, which is already outside of the rootless containers uids.

**Comment by giuseppe** [comment] 2020-04-28 07:23
> This does work as a workaround, but shouldn't the issue itself be fixed?

that is not a workaround.  fuse-overlayfs won't work on top of itself, in the same way overlay doesn't allow to be mounted on top of another overlay file system.  Whiteout files created in the upper mount would confuse the lower mount.

**Comment by rhatdan** [comment] 2020-08-06 17:22
I believe this issue is satisfied, reopen if I am mistaken.

**Closed by rhatdan** 2020-08-06 17:22 UTC
