### ISSUE TITLE
--build-args do not work as expected within docker "ADD" blocks :  buildah version 1.11.2

### ISSUE THREAD

**Issue by tiernemi** [containers/buildah#1871] opened 2019-09-27 08:45 UTC
Having updated to version 1.11.2 of buildah the build args in a dockerfile do not resolve to their correct value in ADD blocks. I have created a minimal repro as follows

1. Create a file called abc.txt
2. Create a dockerfile as follows
```Dockerfile
FROM centos
ARG testArg
ADD ${testArg}.txt .
```
3. Run the following command
```bash
buildah bud --build-arg testArg=abc
```

You should receive the following output
```
STEP 1: FROM centos
STEP 2: ARG testArg
STEP 3: ADD ${testArg}.txt .
error dry-running "ADD ${testArg}.txt .": no files found matching "/home/tiernemi/buildah_test/${testArg}.txt": no such file or directory
ERRO exit status 1                                
```

When running the following command with docker
```bash
docker build . --build-arg testArg=abc
```
It succeeds with no issue.

**Comment by TomSweeneyRedHat** [comment] 2019-09-27 14:54
@tiernemi Thanks for the issue, especially since you've a nice reproducer.  Will take a look.

**Comment by TomSweeneyRedHat** [comment] 2019-09-27 15:14
@tiernemi I'm able to reproduce and it looks like the ARG part of things are working appropriately as I'm able to do `RUN echo $testArg` just before the `ADD` line and that resolves OK.  Do you by chance know if this worked in earlier versions of Buildah?

**Comment by tiernemi** [comment] 2019-09-27 15:19
It was working using the previous version of buildah in our pipeline. Version 1.10.1-2.

**Comment by TomSweeneyRedHat** [comment] 2019-09-27 16:44
Thanks @tiernemi, I think I've found a PR that went into 1.11.0 that may have caused the issue, looking further.

**Comment by dustymabe** [comment] 2019-10-18 22:09
we can close this now that #1874 merged?

**Comment by TomSweeneyRedHat** [comment] 2019-10-18 22:14
@dustymabe yes we can!  I was holding off until we got a release together for Podman, but just verified this is in Buildah v1.11.3 which has been vendored upstream.  Thanks for the poke.

**Closed by TomSweeneyRedHat** 2019-10-18 22:14 UTC
Labels: from Podman
