### ISSUE TITLE
Debian packing conflicts with upstream

### ISSUE THREAD

**Issue by EvanCarroll** [containers/buildah#2797] opened 2020-11-16 23:39 UTC
If you have upstream `podman` installed, it will conflict with the version of buildah you provide,

```
dpkg: error processing archive /var/cache/apt/archives/containers-golang_0.6.0~1_all.deb (--unpack):
 trying to overwrite '/usr/share/containers/seccomp.json', which is also in package podman 2.0.6+dfsg1-2
Selecting previously unselected package containers-image.
```
Not just does it conflict with podman though, it'll logically conflict with the `buildah` upstream,

```
dpkg: error processing archive /var/cache/apt/archives/containers-image_5.5.1~1_all.deb (--unpack):
 trying to overwrite '/etc/containers/registries.conf', which is also in package buildah 1.15.2-1
```

The easy way to fix this is just to call your package something that **is not** buildah to avoid the namespace collision, for example. In this space for example, we have `docker.io` which debian distributed and `docker-ce` which docker upstream distributes (and they conflict with each other in the meta)

Temporary Workaround
====

Of course, it's probably also a [good idea to suggest the `--purge removal` of the upstream packages as step 1 on the Install docs](https://github.com/containers/buildah/blob/master/install.md#debian)

    sudo apt-get --purge remove buildah podman containers-common golang-github-containers-common

**Comment by rhatdan** [comment] 2020-11-17 11:19
Not sure how this is an upstream issue. Seems to be a Debian packaging issue, or are you looking for documentation changes?



@vrothberg Thoughs?

**Comment by vrothberg** [comment] 2020-11-17 12:42
I am also not sure what to do. Mixing third-party repos with the standard repos (on conflicting packages) does not sound like a good idea.

However, we may be able to relax the file conflicts a bit. @lsm5 @siretart, WDYT?

**Comment by lsm5** [comment] 2020-11-17 13:25
@EvanCarroll are you on debian testing or unstable by any chance?

I prefer to get rid of the entire OBS stack of packages for a distro if those packages are provided in the distro's default repos. That would make both my life and the user's life easier. I think it's only Debian testing and unstable that match this description at the moment.

**Comment by EvanCarroll** [comment] 2020-11-17 23:05
I am on Debian testing.

**Comment by EvanCarroll** [comment] 2020-11-17 23:30
> I prefer to get rid of the entire OBS stack of packages for a distro if those packages are provided in the distro's default repos. That would make both my life and the user's life easier. I think it's only Debian testing and unstable that match this description at the moment. However, the issue with this might be that if you were to upgrade from debian stable to testing or unstable, you might end up with an older podman.

Please no!

The distro's packages lag by weeks, months, and years. You don't want to just drop support in a fast moving ecosystem because someone else has older packages. When a bug fix happens, what is your answer going to be to people on these distros? Just wait? Just make your packages conflict with the upstream packages. Then people add your repo. They add your package. And all is well! It just works. Very easy, prefix all the packages with `ocs-`  in obs and and have them conflict with the upstream packages by the same name that lack `ocs-`.

**Comment by lsm5** [comment] 2020-11-18 03:27
> Please no!
> 
> The distro's packages lag by weeks, months, and years. You don't want to just drop support in a fast moving ecosystem because someone else has older packages. When a bug fix happens, what is your answer going to be to people on these distros? Just wait? Just make your packages conflict with the upstream packages. Then people add your repo. They add your package. And all is well! It just works. Very easy, prefix all the packages with `ocs-` in obs and and have them conflict with the upstream packages by the same name that lack `ocs-`.

As much as I'd like to continue, I simply don't have enough time to keep maintaining OBS. Others on the containers team are slammed with other things as well.

Do let me know if you or someone you know can lend a hand with this, I could really use the additional help. Alternatively, maybe more people could participate in the debian packaging process to ship official distro packages faster.

**Comment by lsm5** [comment] 2020-12-08 18:45
Alright, so it seems like we'll need to re-enable the repos for newer Ubuntus again mainly for CI purposes and I will also re-enable the newer Debians while I'm at it since it's effectively zero additional effort on top of Ubuntu. 

But I won't be able to handle issues like this one where people install podman from the default distro repos and buildah from OBS. Renaming OBS packages is a no-go as well since it will break users on existing distros and I cannot maintain copies of the build sources for different versions.

So, going forward, I suggest users prefer all packages from OBS or none at all. This would be easy to ensure given that OBS will always be ahead of the distro packages. I will update the docs to reflect this.

That said, I would still encourage community members to participate in the Debian upstream packaging and testing efforts to speed up updates for official packages so that everyone can benefit from it. I guess @siretart is the best resource for help and advice on Debian participation.

Hope that helps.

/cc @cevich @TomSweeneyRedHat

**Comment by lsm5** [comment] 2020-12-08 20:27
Closing ...

**Closed by lsm5** 2020-12-08 20:27 UTC
Labels: debian, packaging

**Comment by lsm5** [comment] 2020-12-08 21:10
repos re-enabled https://build.opensuse.org/project/show/devel:kubic:libcontainers:stable . I'll update docs tomorrow.

**Comment by ljubisap** [comment] 2020-12-11 14:07
@lsm5 is there a previous version of `skopeo` package available. After this change, I started to get these kinds of errors in my Docker builds:
`#9 4.869 The following information may help to resolve the situation:
#9 4.869
#9 4.869 The following packages have unmet dependencies:
#9 4.959  skopeo : Depends: libc6 (>= 2.28) but 2.24-11+deb9u4 is to be installed
#9 4.972 E: Unable to correct problems, you have held broken packages.`

**Comment by lsm5** [comment] 2020-12-11 14:33
@ljubisap could you open a new issue along with reproducer please?
