### ISSUE TITLE
[BUG] podman inspect .Image crashes

### ISSUE THREAD

**Issue by GoodDingo** [containers/buildah#1907] opened 2019-10-11 12:42 UTC
**Podman fails on go template format where docker works**

**`Error: Template parsing error: template: image:1:7: executing "image" at <.Image>: can't evaluate field Image in type *libpod.InspectContainerData`**

I very much like this project and want to replace all docker with podman on our Jenkins agents.
Jenkins is using Docker CLI, hence this is possible in theory (with proper `docker` wrapper that mocks version and maybe a little bit more back to Jenkins).

Jenkins calls this:
```
docker inspect -f . base-image.cr.example.com/whatever
docker -v   ## <--  fails here if version below 1.7 (needs mocking)
docker run -t -d -u 1234:5678 -u 0:0 -w /path/to/workspace -v /path/to/workspace:/path/to/workspace:rw,z -v /path/to/workspace@tmp:/path/to/workspace@tmp:rw,z -e BUILD_DISPLAY_NAME=#10 -e BUILD_ID=10 -e BUILD_NUMBER=10 ...  base-image.cr.example.com/whatever cat
docker top 23e9deadbeefd57d8137d692cdf16528fadedecade4244feb4b8b5bca112ba3b
docker inspect -f {{.Config.Hostname}} 23e9deadbeefd57d8137d692cdf16528fadedecade4244feb4b8b5bca112ba3b
docker inspect -f {{.Name}} 23e9deadbeefd57d8137d692cdf16528fadedecade4244feb4b8b5bca112ba3b
docker inspect -f {{json .Created}} 23e9deadbeefd57d8137d692cdf16528fadedecade4244feb4b8b5bca112ba3b
docker inspect -f {{.Image}} 23e9deadbeefd57d8137d692cdf16528fadedecade4244feb4b8b5bca112ba3b   ## <-- fails here on podman bug
```

**Steps to reproduce the issue:**
1. With docker
```
$  CONTAINER_ID=$(docker run -td --name docker-container  docker.io/library/alpine  cat)

$  docker inspect -f '{{json .Image}}' $CONTAINER_ID
"sha256:961769676411f082461f9ef46626dd7a2d1e2b2a38e6a44364bcbecf51e66dd4"

$  docker inspect -f '{{.Image}}' $CONTAINER_ID
sha256:961769676411f082461f9ef46626dd7a2d1e2b2a38e6a44364bcbecf51e66dd4
```
2. With podman
```
$  CONTAINER_ID=$(podman run -td --name podman-container  docker.io/library/alpine  cat)

$  podman inspect -f '{{json .Image}}' $CONTAINER_ID
Error: Template parsing error: template: image:1:7: executing "image" at <.Image>: can't evaluate field Image in type *libpod.InspectContainerData

$  podman inspect -f '{{.Image}}' $CONTAINER_ID
Error: Template parsing error: template: image:1:2: executing "image" at <.Image>: can't evaluate field Image in type *libpod.InspectContainerData
```

**Describe the results you received:**
exit_code: 125
stdout: 
stderr: `Error: Template parsing error: template: image:1:2: executing "image" at <.Image>: can't evaluate field Image in type *libpod.InspectContainerData`

**Describe the results you expected:**
exit_code: 0
stdout: actual image id
stderr:

**Output of `apt list buildah podman`:**

```
buildah/xenial,now 1.11.0-1~ubuntu16.04~ppa1 amd64 [installed]
podman/xenial,now 1.6.1-1~ubuntu16.04~ppa3 amd64 [installed]
```

**Output of `buildah version`:**

```
Version:         1.12.0-dev
Go Version:      go1.10.4
Image Spec:      1.0.1
Runtime Spec:    1.0.1-dev
CNI Spec:        0.4.0
libcni Version:
Git Commit:
Built:           Thu Sep  5 16:05:58 2019
OS/Arch:         linux/amd64
```

**Output of `podman version` :**

```
Version:            1.6.1
RemoteAPI Version:  1
Go Version:         go1.10.4
OS/Arch:            linux/amd64
```

**Output of `cat /etc/*release`:**

```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.6 LTS"

NAME="Ubuntu"
VERSION="16.04.6 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.6 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```

**Output of `uname -a`:**

```
Linux my-hostname 4.4.0-1095-aws #106-Ubuntu SMP Wed Sep 18 13:33:48 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Output of `cat /etc/containers/storage.conf`:**

```
# storage.conf is the configuration file for all tools
# that share the containers/storage libraries
# See man 5 containers-storage.conf for more information

# The "container storage" table contains all of the server options.
[storage]

# Default Storage Driver
driver = "overlay"

# Temporary storage location
runroot = "/var/run/containers/storage"

# Primary read-write location of container storage
graphroot = "/var/lib/containers/storage"

[storage.options]
# AdditionalImageStores is used to pass paths to additional read-only image stores
# Must be comma separated list.
additionalimagestores = [
]

# Size is used to set a maximum size of the container image.  Only supported by
# certain container storage drivers (currently overlay, zfs, vfs, btrfs)
size = ""

# OverrideKernelCheck tells the driver to ignore kernel checks based on kernel version
override_kernel_check = "true"
```

**Comment by nalind** [comment] 2019-10-11 13:27
This looks like https://github.com/containers/libpod/issues/4193.

**Comment by TomSweeneyRedHat** [comment] 2019-10-11 14:21
I concur with @nalind.  This is a duplicate of https://github.com/containers/libpod/issues/4193 and I'm going to close this.  @GoodDingo thanks for the issue report.

**Closed by TomSweeneyRedHat** 2019-10-11 14:21 UTC
