### ISSUE TITLE
RFE - let `buildah commit` generate image IDs

### ISSUE THREAD

**Issue by vrothberg** [containers/buildah#1424] opened 2019-03-20 10:30 UTC
`buildah commit` requires specifying an image ID which is a problem in automation as the user is confronted with generating hopefully unique IDs (see https://github.com/SUSE/kiwi/pull/1013#issuecomment-474383203 for a background discussion).

To make `buildah commit` more friendly in automation environments, I would love to have some flag (e.g., `--generate-id`) that generates an ID automatically, just as `buildah bud` does.

Cc: @davidcassany @TomSweeneyRedHat @nalind @umohnani8 @rhatdan

**Comment by rhatdan** [comment] 2019-03-20 13:40
@TomSweeneyRedHat We also need similar changes in podman commit.

**Comment by TomSweeneyRedHat** [comment] 2019-03-20 13:50
My question here is what's expected for the repository:tag of the committed image?  In Docker it sets them to <none>:<none>.  Would that be good here and Podman too?

Also Docker does that by default if  a repository:tag isn't specified.  I think I'd prefer doing that rather than creating an option for this.

**Comment by rhatdan** [comment] 2019-03-20 13:51
Yes I would follow the Docker behavior make the specification of the image reference optional.

**Comment by TomasTomecek** [comment] 2019-03-31 16:50
I hope that I understand this right, but the problem is that `buildah commit` requires an image name. It would be awesome if the name argument was optional and buildah would not set any afterwards resulting into a nameless image. E.g. this what bender does now and it clutters the output quite a bit:
```
localhost/packit-20190507-160521                         latest               03c3e1bddf33         Feb 7, 2019 16:05      673 MB                                            
localhost/packit-20190507-160544                         latest               a54d06efbeba         Feb 7, 2019 16:05      676 MB                                            
localhost/packit-20190607-160612                         latest               ed12304334e0         Feb 7, 2019 16:06      745 MB                                            
localhost/packit-20190607-160633                         latest               4b089426a1c4         Feb 7, 2019 16:06      748 MB                                            
localhost/packit-20190607-160651                         latest               6cd6b78dc4db         Feb 7, 2019 16:06      748 MB                                            
localhost/packit-20190707-160707                         latest               e0a35db19c8d         Feb 7, 2019 16:07      748 MB                                            
localhost/packit-20190707-160725                         latest               1e18476d602d         Feb 7, 2019 16:07      748 MB                                            
```
A ton of layers which should have been hidden, ideally.

`docker commit` accepts image name optionally:
```
Usage:  docker commit [OPTIONS] CONTAINER [REPOSITORY[:TAG]]
```

**Comment by nalind** [comment] 2019-04-03 16:35
@TomSweeneyRedHat would you mind if I took this one?

**Comment by TomSweeneyRedHat** [comment] 2019-04-03 16:50
Go for it @nalind.  Thanks for checking.

**Comment by rhatdan** [comment] 2019-06-08 18:22
Looks like this is fixed.

**Closed by rhatdan** 2019-06-08 18:22 UTC
