### ISSUE TITLE
Tidy Demo's, Rootless Accomodated?

### ISSUE THREAD

**Issue by andrewgdunn** [containers/buildah#3912] opened 2022-04-12 19:03 UTC
**Description**

On Fedora 35, running as non-root. Fresh install without any cached short name aliases (e.g. `~/.cache/containers/short-name-aliases.conf`) the `demo/buildah_multi_stage.sh` script fails: 

```
++ buildah bud -t multifromfile:latest -f ./Dockerfile.multi .
error creating build container: short-name resolution enforced but cannot prompt without a TTY
```
This could be resolved by putting `docker.io/` in the `from` invocations. Reference [container-image-short-names](https://www.redhat.com/sysadmin/container-image-short-names).

It also fails at the second portion of the demo:

```
Let's mount the container getting the root directory
cannot mount using driver overlay in rootless mode. You need to run it in a `buildah unshare` session
```
This to me is more tricky, there is some discussion in #1279 that I felt might help, also [this documentation](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/building_running_and_managing_containers/assembly_building-container-images-with-buildah_building-running-and-managing-containers#proc_modifying-a-container-using-buildah-mount_assembly_building-container-images-with-buildah) but ultimately I couldn't get my head around how to do this inline.

If I was able to sort out both of these problems I would have offered a PR, however I was stumped by the rootless mount challenges.

**Comment by andrewgdunn** [comment] 2022-04-12 19:09
I guess I should point out that in [the readme](https://github.com/containers/buildah/blob/main/demos/README.md?plain=1#L28) maybe it's intended that these demos are run as root and rootless is not a reasonable thing to try with them in their current form?

**Comment by rhatdan** [comment] 2022-04-12 20:12
The should work in both modes, the issue is no one has run them since the shortnames change.

**Comment by andrewgdunn** [comment] 2022-04-12 23:03
I don't think it actually works with rootless right now, there isn't any unshare directives in the scripts right?

```
$ podman --version
podman version 3.4.4
$ buildah --version
buildah version 1.23.3 (image-spec 1.0.1-dev, runtime-spec 1.0.2-dev)
```

```
$ podman unshare cat /proc/self/uid_map 
         0       1000          1
         1     100000      65536
```

```
Let's build the container with Buildah, first GoLang
Let's mount the container getting the root directory
cannot mount using driver overlay in rootless mode. You need to run it in a `buildah unshare` session
Let's get x/net/html into the container
   redact

Copy app.go into the container
cp: cannot create regular file '/go': Permission denied

**Comment by rhatdan** [comment] 2022-04-13 11:41
Yes it should be rewritten to say use buildah unshare before the mount and then do everything without the unshare environment in rootless mode.

**Comment by rhatdan** [comment] 2022-05-17 19:35
@TomSweeneyRedHat PTAL

**Comment by rhatdan** [comment] 2022-06-17 13:54
@flouthoc Could you clean this up or hand it off to an intern?

**Comment by flouthoc** [comment] 2022-06-20 09:35
For `buildah_multi_stage.sh` we can use unshare only for mounting and for `buildah-scratch-demo` since it uses pkg managers we need unshare entire invocation but since it uses only scratch and no image so it works.

Following PR should close this issue: https://github.com/containers/buildah/pull/4065

**Closed** 2022-06-23 13:44 UTC
