### ISSUE TITLE
buildah bud --manifest missing variant

### ISSUE THREAD

**Issue by vl-shopback** [containers/buildah#3821] opened 2022-03-15 01:22 UTC
**Description**
missing variant in manifest when you use command buildah bud --manifest 

**Steps to reproduce the issue:**
```
buildah --version
buildah version 1.21.3 (image-spec 1.0.1-dev, runtime-spec 1.0.2-dev)


IMAGE=test:v2
buildah manifest create $IMAGE
buildah bud --override-arch arm64 --tag $IMAGE-arm64
buildah manifest add $IMAGE --arch arm64 --variant v8 $IMAGE-arm64
buildah manifest inspect $IMAGE
{
    "schemaVersion": 2,
    "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
    "manifests": [
        {
            "mediaType": "application/vnd.oci.image.manifest.v1+json",
            "size": 494,
            "digest": "sha256:00fa441e3f8d5112cbe51ed8a0f7327f6d18dbcc2ff864252577ce293abb82d7",
            "platform": {
                "architecture": "arm64",
                "os": "linux",
                "variant": "v8"
            }
        }
    ]
}

IMAGE=test:v3
buildah manifest create $IMAGE
buildah bud --manifest $IMAGE --arch arm64 --variant v8
buildah manifest inspect $IMAGE
{
    "schemaVersion": 2,
    "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
    "manifests": [
        {
            "mediaType": "application/vnd.oci.image.manifest.v1+json",
            "size": 494,
            "digest": "sha256:7be8bf4ab843e99967ea70e3e349971bbe4857329f03a49fb64a2b277a35a143",
            "platform": {
                "architecture": "arm64",
                "os": "linux"
            }
        }
    ]
}
```

**Describe the results you received:**
"buildah bud --manifest" missed variant in manifest content

**Describe the results you expected:**
"buildah bud --manifest" should generate same manifest content as "buildah manifest add" command

**Output of `rpm -q buildah` or `apt list buildah`:**

```
buildah/unknown,now 100:1.21.3-1 amd64 [installed]
buildah/unknown 100:1.21.3-1 arm64
buildah/unknown 100:1.21.3-1 armhf
buildah/unknown 100:1.21.3-1 s390x
```

**Output of `buildah version`:**

```
buildah version 1.21.3 (image-spec 1.0.1-dev, runtime-spec 1.0.2-dev)
```

**Output of `podman version` if reporting a `podman build` issue:**

```
(paste your output here)
```

**Output of `cat /etc/*release`:**

```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.3 LTS"
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

**Output of `uname -a`:**

```
Linux ip-172-31-3-112 5.13.0-1017-aws #19~20.04.1-Ubuntu SMP Mon Mar 7 12:53:12 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

```

**Output of `cat /etc/containers/storage.conf`:**

```
[storage]
driver = "overlay"
runroot = "/run/containers/storage"
graphroot = "/var/lib/containers/storage"
[storage.options]
additionalimagestores = [
]
[storage.options.overlay]
mountopt = "nodev,metacopy=on"
[storage.options.thinpool]
```

**Comment by flouthoc** [comment] 2022-03-15 06:08
Hi @vl-shopback. I tried reproducing it but this is not present in the newer versions or upstream. Could you please use upstream ? I am closing this issue since this seems to be fixed. But please feel free to re-open if you feel something is not resolved.

**Closed by flouthoc** 2022-03-15 06:08 UTC
