### ISSUE TITLE
--memory not used with `buildah bud`

### ISSUE THREAD

**Issue by daveisfera** [containers/buildah#2244] opened 2020-03-24 18:54 UTC
**Description**
`--memory` does not appear to flow to the `RUN` commands in a `Dockerfile`

**Steps to reproduce the issue:**
1. Run `build bud --memory=2G --memory-swap=2G web`

**Describe the results you received:**
It runs out of memory:
```
<--- Last few GCs --->
 f[1:0x5588a216dba0]    87105 ms: Mark-sweep 510.0 (514.8) -> 509.6 (516.1) MB, 669.2 / 0.0 ms  (+ 200.6 ms in 30 steps since start of marking, biggest step 15.0 ms, walltime since start of marking 896 ms) (average mu = 0.105, current mu = 0.030) allocation[1:0x5588a216dba0]    88057 ms: Mark-sweep 511.3 (516.1) -> 510.8 (517.1) MB, 770.2 / 0.0 ms  (+ 148.7 ms in 27 steps since start of marking, biggest step 12.7 ms, walltime since start of marking 952 ms) (average mu = 0.070, current mu = 0.034) allocation

<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x5588a0244ed9]
    1: StubFrame [pc: 0x5588a01c9f55]
Security context: 0x2c3b610c08d1 <JSObject>
    2: /* anonymous */ [0x1e559e6b74a1] [/usr/src/app/node_modules/acorn/dist/acorn.js:~4905] [pc=0x2b334feeaa9a](this=0x35a3367ec229 <Parser map = 0x1e2a27686429>)
    3: /* anonymous */ [0x1e559e6b3621] [/usr/src/app/node_modules/acorn/dist/acorn.js:~617] [pc=0x2b3350aca28b](this=0x35a3367ec229 <Parser map = 0x1e2a2768...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
```

**Describe the results you expected:**
2 GB of memory would be available to the `node` process, like it is when running `docker build --memory=2G --memory-swap=2G web`

**Output of `rpm -q buildah` or `apt list buildah`:**
```
buildah-1.14.3-1.1.el7.x86_64
```

**Output of `buildah version`:**
```
Version:         1.14.3
Go Version:      go1.13.6
Image Spec:      1.0.1-dev
Runtime Spec:    1.0.1-dev
CNI Spec:        0.4.0
libcni Version:  
image Version:   5.2.1
Git Commit:      
Built:           Thu Jan  1 00:00:00 1970
OS/Arch:         linux/amd64
```

**Output of `podman version` if reporting a `podman build` issue:**
```
Version:            1.8.2
RemoteAPI Version:  1
Go Version:         go1.13.6
OS/Arch:            linux/amd64
```

**Output of `cat /etc/*release`:**
```
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
Amazon Linux release 2 (Karoo)
```

**Output of `uname -a`:**
```
Linux ip-172-31-23-128.us-west-2.compute.internal 4.14.171-136.231.amzn2.x86_64 #1 SMP Thu Feb 27 20:22:48 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Output of `cat /etc/containers/storage.conf`:**
(Added `grep . | grep -v "^#"` to minimize it)
```
[storage]
driver = "overlay"
runroot = "/var/run/containers/storage"
graphroot = "/var/lib/containers/storage"
[storage.options]
additionalimagestores = [
]
[storage.options.overlay]
mountopt = "nodev"
[storage.options.thinpool]
```

**Comment by rhatdan** [comment] 2020-03-25 18:08
Does this build if you do not specify the memory?

**Comment by daveisfera** [comment] 2020-03-28 01:44
I just tried that and yes, but then the memory isn't limited and that can cause problems on our build server when multiple builds are running

**Comment by TomSweeneyRedHat** [comment] 2020-03-28 17:27
Most likely related to #1213

**Comment by TomSweeneyRedHat** [comment] 2020-03-28 18:46
I'll take another run at it.  If I recall, we were handing everything down OK, but somehwere in the code that does the actual creation of the image, the memory size/swap weren't being retained.

**Comment by TomSweeneyRedHat** [comment] 2020-05-05 23:34
I've run this down using cgroup v1, need to do the same in cgroup v2 tomorrow.  From what I can tell, this is operating as expected.  i.e. if you want to limit the memory size or swap, you need to specify those in the `buildah bud` command to limit them when the `RUN` statements are invoked in a Dockerfile build.  You then need to use those options again in the `podman run` command to limit them in the container.  I just tried using Buildah v1.14.8 and Podman v1.9.0,  these two are doing the same functionality as Docker.  

I'll follow up with cgroupV2 tomorrow, it stores the memory limits in different places than cgroup v1.

### Using this Dockerfile.alpine
```
# cat Dockerfile.alpine
FROM alpine AS tommer
RUN cat /sys/fs/cgroup/memory/memory.limit_in_bytes`
```
### Docker:
```
# docker build -m 5mb -t tom -f ~/Dockerfile.alpine .
Sending build context to Docker daemon  10.24kB
Step 1/2 : FROM alpine AS tommer
 ---> f70734b6a266
Step 2/2 : RUN cat /sys/fs/cgroup/memory/memory.limit_in_bytes
 ---> Running in 46ca5dff9e9e
5242880
Removing intermediate container 46ca5dff9e9e
 ---> 813f193f3f1b
Successfully built 813f193f3f1b
Successfully tagged tom:latest

# docker run -d tom sleep 120
fb30428ef5dea5373d2afe2a66fd036c6da36851f86d0f1df8515e576e249c0c

# docker exec -it fb30428ef5dea5373d2afe2a66fd036c6da36851f86d0f1df8515e576e249c0c /bin/sh
/ #  cat /sys/fs/cgroup/memory/memory.limit_in_bytes
9223372036854771712
# docker run -m 5mb -d tom sleep 120
b2f2c27f33650a93bd144537841789136054a40cc34b132396483acc7c3bb04b

# docker exec -it b2f2c27f33650a93bd144537841789136054a40cc34b132396483acc7c3bb04b /bin/sh
/ #  cat /sys/fs/cgroup/memory/memory.limit_in_bytes
5242880
```
### Buildah/Podman
```
# buildah bud -m 5mb -t tom -f ~/Dockerfile.alpine .
STEP 1: FROM alpine AS tommer
STEP 2: RUN cat /sys/fs/cgroup/memory/memory.limit_in_bytes
5242880
STEP 3: COMMIT tom
Getting image source signatures
Copying blob 3e207b409db3 skipped: already exists  
Copying blob f458a79f2e8a done  
Copying config 1360292387 done  
Writing manifest to image destination
Storing signatures
--> 1360292387e
1360292387e7eae6e90f87cfff8593165afcdf4c6677049968fa04d15ab2d070

# podman run  -d tom sleep 120
4f05c99b717c709cfca4830ee1a125b50211adb57e64700c9a9ac1e3b6f327a4

# podman exec -it 4f05c99b717c709cfca4830ee1a125b50211adb57e64700c9a9ac1e3b6f327a4 cat /sys/fs/cgroup/memory/memory.limit_in_bytes
9223372036854771712

# podman run -m 5mb -d tom sleep 120
0f2a0dde38819d87a2e7917d8a9dbf7ac4fd17190fecbe1098e8fe07a2133f2c

# podman exec -it 0f2a0dde38819d87a2e7917d8a9dbf7ac4fd17190fecbe1098e8fe07a2133f2c /bin/sh
/ # cat /sys/fs/cgroup/memory/memory.limit_in_bytes
5242880
```

**Comment by daveisfera** [comment] 2020-05-06 03:57
Isn't that showing that `podman run` is doing the right thing, but I don't believe that means that `buildah bud` is enforcing the memory limit during the build like it should

**Comment by TomSweeneyRedHat** [comment] 2020-05-06 18:32
@daveisfera It is working for "bulidah bud" too.  In the example above for Buildah:

```
# buildah bud -m 5mb -t tom -f ~/Dockerfile.alpine .
STEP 1: FROM alpine AS tommer
STEP 2: RUN cat /sys/fs/cgroup/memory/memory.limit_in_bytes
5242880
```

If you don't pass in the `-m 5mb`, it will instead return `9223372036854771712`

**Comment by daveisfera** [comment] 2020-05-06 18:43
Is there a version after `buildah-1.14.3-1.1.el7.x86_64` that fixed this?

**Comment by rhatdan** [comment] 2020-05-06 18:47
Upstream is at buildah-1.14.8

**Comment by TomSweeneyRedHat** [comment] 2020-05-06 21:35
@daveisfera I've been testing this on Fedora 30 and Fedora 31 and both 1.14.8 and 1.14.3 both are working for me.  I just realized that you're using "Amazon Linux" and that's not one I've used before.  Do you by chance have the ability to spin up a Fedora 30+ VM and see how it goes there for you?

The settings for the memory are handle by cgroup.  Do you happen to know if your linux uses cgroup v1 or cgroup v2?  Both should work, but you'd need to look at this:

`cat /sys/fs/cgroup/$(sed -e 's|0::||' < /proc/self/cgroup)/memory.max`

@giuseppe if you have any thoughts, please chime in.

**Comment by giuseppe** [comment] 2020-05-07 07:29
I don't see it specified above.  Is buildah running as root or rootless user?

**Comment by daveisfera** [comment] 2020-05-07 15:52
I'm using the default install, so I believe it's using the root user

**Comment by rhatdan** [comment] 2020-05-07 19:18
The default install supports both.  The question is are you executing

$ buildah bud .
or
$ sudo buildah bud .

The problem is running buildah rootless on a cgroupv1 machine will not set the cgroups, since rootless users are not allowed to use cgroups.

**Comment by daveisfera** [comment] 2020-05-07 19:20
I was running `sudo buildah bud`

**Comment by giuseppe** [comment] 2020-05-08 08:49
> ****
> 2 GB of memory would be available to the `node` process, like it is when running `docker build --memory=2G --memory-swap=2G web`

in the error I am seeing an OOM error.  So it looks like either a memory limit was in place (or the memory allocation failed for different reasons).  The 2gb are a hard limit on the memory the container can use, it is not an allocation for 2gb of memory, so the memory allocation can fail before the container reaches 2gb if not enough memory is available.

Could you repeat the same tests @TomSweeneyRedHat pointed out?  So we can sort out if the wrong limit was applied.

**Comment by rhatdan** [comment] 2020-08-04 17:30
Closing this for lack of input.  Reopen if you can provide more data.

**Closed by rhatdan** 2020-08-04 17:30 UTC
