### ISSUE TITLE
tutorial 1 - Unable to read consumer identity

### ISSUE THREAD

**Issue by TidyData** [containers/buildah#1973] opened 2019-11-10 03:58 UTC
**Description**

Using a fresh workstation development install of RHEL 8.1 I am working through the buildah [tutorial 1 guide](https://github.com/containers/buildah/blob/master/docs/tutorials/01-intro.md) and installing bash and coreutil within the container's mount is not working.

**Steps to reproduce the issue:**
1. `sudo -s`
2. `newcontainer=$(buildah from scratch)`
3. `scratchmnt=$(buildah mount $newcontainer)`
4. `dnf install --installroot $scratchmnt --releasever 30 bash coreutils --setopt install_weak_deps=false -y`

I ran it as normal user at first with no `sudo` but after researching and finding #1469 I restarted and ran as root with the same results.  Full bash dump at bottom of the issue.

**Describe the results you received:**
The main error seems to be unable to read consumer identity when trying to install using the --installroot option.  It seems to work fine without the option for the base OS.

**Describe the results you expected:**

expected it to install bash and coreutils within the buildah container's mount

**Output of `rpm -q buildah` or `apt list buildah`:**

```
buildah-1.9.0-5.module+el8.1.0+4240+893c1ab8.x86_64
```

**Output of `buildah version`:**

```
Version:         1.9.0
Go Version:      go1.12.8
Image Spec:      1.0.0
Runtime Spec:    1.0.0
CNI Spec:        0.4.0
libcni Version:  
Git Commit:      
Built:           Wed Dec 31 16:00:00 1969
OS/Arch:         linux/amd64
```

**Output of `podman version` if reporting a `podman build` issue:**

```
Version:            1.4.2-stable2
RemoteAPI Version:  1
Go Version:         go1.12.8
OS/Arch:            linux/amd64
```

**Output of `cat /etc/*release`:**

```
NAME="Red Hat Enterprise Linux"
VERSION="8.1 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.1"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.1 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8.1:GA"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.1
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.1"
Red Hat Enterprise Linux release 8.1 (Ootpa)
Red Hat Enterprise Linux release 8.1 (Ootpa)
```

**Output of `uname -a`:**

```
Linux dev-0 4.18.0-147.el8.x86_64 #1 SMP Thu Sep 26 15:52:44 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Output of `cat /etc/containers/storage.conf`:**

```
# storage.conf is the configuration file for all tools
# that share the containers/storage libraries
# See man 5 containers-storage.conf for more information
# The "container storage" table contains all of the server options.
[storage]

# Default Storage Driver
driver = "overlay"

# Temporary storage location
runroot = "/var/run/containers/storage"

# Primary Read/Write location of container storage
graphroot = "/var/lib/containers/storage"

[storage.options]
# Storage options to be passed to underlying storage drivers

# AdditionalImageStores is used to pass paths to additional Read/Only image stores
# Must be comma separated list.
additionalimagestores = [
]

# Size is used to set a maximum size of the container image.  Only supported by
# certain container storage drivers.
size = ""

# OverrideKernelCheck tells the driver to ignore kernel checks based on kernel version
override_kernel_check = "true"

# Remap-UIDs/GIDs is the mapping from UIDs/GIDs as they should appear inside of
# a container, to UIDs/GIDs as they should appear outside of the container, and
# the length of the range of UIDs/GIDs.  Additional mapped sets can be listed
# and will be heeded by libraries, but there are limits to the number of
# mappings which the kernel will allow when you later attempt to run a
# container.
#
# remap-uids = 0:1668442479:65536
# remap-gids = 0:1668442479:65536

# Remap-User/Group is a name which can be used to look up one or more UID/GID
# ranges in the /etc/subuid or /etc/subgid file.  Mappings are set up starting
# with an in-container ID of 0 and the a host-level ID taken from the lowest
# range that matches the specified name, and using the length of that range.
# Additional ranges are then assigned, using the ranges which specify the
# lowest host-level IDs first, to the lowest not-yet-mapped container-level ID,
# until all of the entries have been used for maps.
#
# remap-user = "storage"
# remap-group = "storage"

[storage.options.thinpool]
# Storage Options for thinpool

# autoextend_percent determines the amount by which pool needs to be
# grown. This is specified in terms of % of pool size. So a value of 20 means
# that when threshold is hit, pool will be grown by 20% of existing
# pool size.
# autoextend_percent = "20"

# autoextend_threshold determines the pool extension threshold in terms
# of percentage of pool size. For example, if threshold is 60, that means when
# pool is 60% full, threshold has been hit.
# autoextend_threshold = "80"

# basesize specifies the size to use when creating the base device, which
# limits the size of images and containers.
# basesize = "10G"

# blocksize specifies a custom blocksize to use for the thin pool.
# blocksize="64k"

# directlvm_device specifies a custom block storage device to use for the
# thin pool. Required if you setup devicemapper
# directlvm_device = ""

# directlvm_device_force wipes device even if device already has a filesystem
# directlvm_device_force = "True"

# fs specifies the filesystem type to use for the base device.
# fs="xfs"

# log_level sets the log level of devicemapper.
# 0: LogLevelSuppress 0 (Default)
# 2: LogLevelFatal
# 3: LogLevelErr
# 4: LogLevelWarn
# 5: LogLevelNotice
# 6: LogLevelInfo
# 7: LogLevelDebug
# log_level = "7"

# min_free_space specifies the min free space percent in a thin pool require for
# new device creation to succeed. Valid values are from 0% - 99%.
# Value 0% disables
# min_free_space = "10%"

# mkfsarg specifies extra mkfs arguments to be used when creating the base
# device.
# mkfsarg = ""

# mountopt specifies extra mount options used when mounting the thin devices.
# mountopt = ""

# use_deferred_removal Marking device for deferred removal
# use_deferred_removal = "True"

# use_deferred_deletion Marking device for deferred deletion
# use_deferred_deletion = "True"

# xfs_nospace_max_retries specifies the maximum number of retries XFS should
# attempt to complete IO when ENOSPC (no space) error is returned by
# underlying storage device.
# xfs_nospace_max_retries = "0"
```

** full bash dump **
```bash
[username@compname ~]$ sudo -s
[sudo] password for username: 
[root@compname username]# buildah images
REPOSITORY                 TAG      IMAGE ID       CREATED       SIZE
docker.io/library/fedora   latest   f0858ad3febd   12 days ago   201 MB
[root@compname username]# buildah containers
CONTAINER ID  BUILDER  IMAGE ID     IMAGE NAME                       CONTAINER NAME
3ca6f2d07c60     *     f0858ad3febd docker.io/library/fedora:latest  fedora-working-container
[root@compname username]# newcontainer=$(buildah from scratch)
[root@compname username]# buildah containers
CONTAINER ID  BUILDER  IMAGE ID     IMAGE NAME                       CONTAINER NAME
3ca6f2d07c60     *     f0858ad3febd docker.io/library/fedora:latest  fedora-working-container
be1c6e0f8375     *                  scratch                          working-container
[root@compname username]# buildah run $newcontainer bash
container_linux.go:345: starting container process caused "exec: \"bash\": executable file not found in $PATH"
error running container: error creating container for [bash]: : exit status 1
error while running runtime: exit status 1
[root@compname username]# scratchmnt=$(buildah mount $newcontainer)
[root@compname username]# echo $scratchmnt
/var/lib/containers/storage/overlay/<redacted>0b32d06101e8890ab2a38012783c41e66cbd74251b391e8de3175/merged
[root@compname username]# dnf install --installroot $scratchmnt --releasever 30 bash coreutils --setopt install_weak_deps=false -y
Updating Subscription Management repositories.
Unable to read consumer identity
This system is not registered to Red Hat Subscription Management. You can use subscription-manager to register.
Red Hat Enterprise Linux 8 for x86_64 - AppStream (RPMs)                 7.1  B/s |  10  B     00:01    
Failed to download metadata for repo 'rhel-8-for-x86_64-appstream-rpms'
Error: Failed to download metadata for repo 'rhel-8-for-x86_64-appstream-rpms'
```
as expected since the above command didn't work, the below wouldn't work...
```bash
[root@compname username]# buildah run $newcontainer bash
container_linux.go:345: starting container process caused "exec: \"bash\": executable file not found in $PATH"
error running container: error creating container for [bash]: : exit status 1
error while running runtime: exit status 1
```

**Comment by rhatdan** [comment] 2020-08-05 14:28
@TidyData @TomSweeneyRedHat Is this fixed now?

**Comment by TomSweeneyRedHat** [comment] 2020-08-05 20:24
This works just fine on the distributions that I tried except RHEL.  I think the issue is that RHEL is looking for the subscription manager creds and is not finding them within the container. 

I first installed a fresh RHEL 8.1 VM and tried what @TidyData did:
```
# dnf install --installroot $scratchmnt --releasever 30 bash coreutils --setopt install_weak_deps=false -y
Updating Subscription Management repositories.
Unable to read consumer identity
This system is not registered to Red Hat Subscription Management. You can use subscription-manager to register.
Error: There are no enabled repositories in "/etc/yum.repos.d", "/etc/yum/repos.d", "/etc/distro.repos.d".
```

 I then tried to install bash on the host and ran into the same error:
```
# dnf install bash
Updating Subscription Management repositories.
Unable to read consumer identity
This system is not registered to Red Hat Subscription Management. You can use subscription-manager to register.
Error: There are no enabled repositories in "/etc/yum.repos.d", "/etc/yum/repos.d", "/etc/distro.repos.d".
```

So I configured subscription manager:
```
# subscription-manager register --username={myusername@redhat.com} --password={mypassword} --serverurl=subscription.rhn.stage.redhat.com --baseurl=cdn.stage.redhat.com 
# subscription-manager attach --pool={poolID}
```

and installed bash on the host successfully:
```
# dnf install bash
Updating Subscription Management repositories.
Red Hat Enterprise Linux 8 for x86_64 - AppStream (RPMs)                                                                    5.1 MB/s |  21 MB     00:04    
Red Hat Enterprise Linux 8 for x86_64 - BaseOS (RPMs)                                                                       5.9 MB/s |  22 MB     00:03    
Last metadata expiration check: 0:00:06 ago on Wed 05 Aug 2020 03:57:45 PM EDT.
Package bash-4.4.19-10.el8.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
```

But when I reran the dnf command to the container, I still ran into the same error:
```
# dnf install --installroot $scratchmnt --releasever 30 bash coreutils --setopt install_weak_deps=false -y
Updating Subscription Management repositories.
Unable to read consumer identity
This system is not registered to Red Hat Subscription Management. You can use subscription-manager to register.
Red Hat Enterprise Linux 8 for x86_64 - AppStream (RPMs)                                                                    373  B/s | 259  B     00:00    
Failed to download metadata for repo 'rhel-8-for-x86_64-appstream-rpms'
Error: Failed to download metadata for repo 'rhel-8-for-x86_64-appstream-rpms'
```

So it looks to me that we're running into a RHEL Subscription Manager restriction.  I don't think there's anything our group can do with this, should I move this to a Bugzilla against the subscription manager or do you have a contact @rhatdan ?

**Comment by rhatdan** [comment] 2020-08-06 19:58
Yes lets bring in the subscription manager people.  But this should be a bugzilla not an issue.
@TidyData Could you copy this information into a bugzilla on subscription manager.  CC Myself and Tom and then we can carry on the conversation there with the subscription manager team.

**Comment by TomSweeneyRedHat** [comment] 2020-08-19 22:09
@TidyData if you have not yet made a BZ, please do not at this point.  I've just created https://bugzilla.redhat.com/show_bug.cgi?id=1870376

**Comment by TidyData** [comment] 2020-08-20 03:45
@TomSweeneyRedHat I did make one should I close it out?  The initial response was to read the container RHEL 8 manual...

https://bugzilla.redhat.com/show_bug.cgi?id=1867426

I made a BZ, then some crisis distracted me and I never posted here... sorry for the delay.

anyways, have a nice day

**Comment by TomSweeneyRedHat** [comment] 2020-08-20 13:23
Thanks @TidyData will take a look at that.

**Comment by TomSweeneyRedHat** [comment] 2020-09-02 21:44
@TidyData per the discussion in the https://bugzilla.redhat.com/show_bug.cgi?id=1867426, this is working as expected.  The issue is that dnf doesn't know what to install as you used a version (30) that RHEL's dnf is not aware of for itself.  If you pick a RHEL version for the --releaserver option it should work.  Or if you specify fedora instead of scratch it works too:

```
# newcontainer=$(buildah from fedora)
Getting image source signatures
Copying blob c7def56d621e done
Copying config a368cbcfa6 done
Writing manifest to image destination
Storing signatures

# scratchmnt=$(buildah mount $newcontainer)

# dnf install --installroot $scratchmnt --releasever 30 bash coreutils --setopt install_weak_deps=false -y
Fedora 30 openh264 (From Cisco) - x86_64         10 kB/s | 5.1 kB     00:00    
Fedora Modular 30 - x86_64                      2.2 MB/s | 1.9 MB     00:00    
Fedora Modular 30 - x86_64 - Updates            836 kB/s | 3.6 MB     00:04    
Fedora 30 - x86_64 - Updates                    9.5 MB/s |  29 MB     00:03    
Fedora 30 - x86_64                              9.6 MB/s |  61 MB     00:06    
Package bash-5.0.17-1.fc32.x86_64 is already installed.
Package coreutils-8.32-4.fc32.1.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
```

Or change your dnf command to:

```
# dnf install --installroot $scratchmnt --releasever 8.1 bash coreutils --setopt install_weak_deps=false -y
```
using a RHEL version and this will work too.

**Closed by TomSweeneyRedHat** 2020-09-02 21:44 UTC
