### ISSUE TITLE
buildah mount ctr in rootless mode should work.

### ISSUE THREAD

**Issue by rhatdan** [containers/buildah#1279] opened 2019-01-14 23:16 UTC
We should enter the usernamespace before mounting and it would work fine.  If we do similar with other commands we should be able to get most of buildah commands to work.

**Comment by rhatdan** [comment] 2019-01-14 23:19
```
$ buildah mount alpine-working-container
cannot mount using driver overlay in rootless mode
ERRO[0000] exit status 1                            
```
```
$ buildah unshare
# buildah mount alpine-working-container
/home/dwalsh/.local/share/containers/storage/overlay/bcef5f32e15f3dc982bd1239c03030a23a29fbb941a86ba211252acc8a660d92/merged
exit
```
```
$ touch /home/dwalsh/.local/share/containers/storage/overlay/bcef5f32e15f3dc982bd1239c03030a23a29fbb941a86ba211252acc8a660d92/merged/dan
```
```
 buildah umount alpine-working-container
472be9b00a55524077005980063b8dcd786494f5a0fab84ceefeb9a76fb2b675
```

**Comment by rhatdan** [comment] 2019-01-15 13:37
So can we either change buildah mount to reexec itself as
```
buildah mount fedora-working-container
buildah unshare buildah mount fedora-working-container
```

**Comment by giuseppe** [comment] 2019-01-15 14:44
that will break the non interactive use case: `ctr=$(buildah mount fedora-working-container)` as buildah mount will re-exec and create the `unshare` session

**Comment by SergeyBear** [comment] 2019-02-13 15:01
Hello!

+1 for invoking unshare silently in mount in rootless mode, because non-interactive case already broken:
    
    id=$(buildah from centos)
    mount=$(buildah unshare buildah mount ${id})

returns:

    Main config did not have a override_install_langs attr. before setopt
    Main config did not have a override_install_langs attr. before setopt
    Error: This command has to be run under the root user.

Fedora 29 and buildah-1.6-2.git5f95bd9.fc29.x86_64

**Comment by giuseppe** [comment] 2019-02-13 15:05
@SergeyBear that won't work.

You need to use unshare before using any other buildah command.

@TomasTomecek already solved the issue he was having that way.  I think we can close this issue

**Comment by SergeyBear** [comment] 2019-02-13 15:33
@giuseppe oh, I see, like that it worked:

    buildah unshare ./build.sh

Thant you!

**P.S.** But imho, it would be nice not to bother about different tricks and rootless mode worked out of the box.

**Comment by giuseppe** [comment] 2019-02-13 15:36
@SergeyBear the problem is that what we want to achieve is not permitted.  Once the process exits, there is no mount point that will survive it, and this is done for good reasons as an unprivileged user cannot mount stuff on the host.

We need to stay in the same namespace, where the mount exists and is accessible.

I am not trying to avoid fixing it, it is just not possible :-)

**Comment by SergeyBear** [comment] 2019-02-13 15:40
@giuseppe please, don't get me wrong, I'm just saying from perspective of user which I'm now :-)

**Comment by rhatdan** [comment] 2019-02-13 22:51
I think we need to fix this via documentation.  In rootless mode buildah mount should throw and error explainign how you need to do this in rootless mode.
```
$ buildah mount $ctr
Error: Buildah mount in rootless mode needs to be run within a buildah unshare
session.

First execute
# buildah unshare
# buildah mount $ctr
...
# buildah commit $ctr image
# exit

Alternatively you can create a bash script and execute it from `buildah unshare ./buildscript.sh`
```

**Comment by rhatdan** [comment] 2019-02-13 22:52
@SergeyBear I agree with you people are stumbling over this, and we at least need to make it clear what is going on.

**Comment by giuseppe** [comment] 2019-02-14 09:37
we already have an error when trying to mount overlay directly without an `unshare` environment, and we have also the documentation for it: https://github.com/containers/buildah/commit/b4f712fa756aeb10169d4b43eee83edc894d1604

I've opened another PR to improve the error message: https://github.com/containers/buildah/pull/1339

**Closed** 2019-02-17 20:14 UTC

**Comment by AndydeCleyre** [comment] 2019-02-18 20:23
So is it possible, rootlessly, to use mount in non-interactive scripts (in arbitrary languages), somehow saving the environment created by `unshare`, so that it can explicitly be provided to other (potentially non-buildah) operations? It seems the `env` vars are not sufficient, so what else can be "exported" of the created environment so that a separate "session" may also access the mounted filesystem?

**Comment by rhatdan** [comment] 2019-02-18 21:37
You can just mount the same mount point in a different session
buildah unshare
buildah mount ctr
Go to town.

**Comment by AndydeCleyre** [comment] 2019-02-19 05:01
@rhatdan Thanks, but I'm thinking of a case that doesn't totally support sessions in the sense of multiple commands directly affecting each other's "environments". What defines the environment (or is that the wrong question)?

**Comment by rhatdan** [comment] 2019-02-19 22:18
I think you really need to describe what you want to do.

**Comment by AndydeCleyre** [comment] 2019-02-20 18:30
For example, certain cases of using a configuration management tool like Ansible making multiple SSH connections to run various steps, some of which need access to the mounted container filesystem.

**Comment by AndydeCleyre** [comment] 2019-07-30 20:33
@rhatdan

In addition to the case mentioned above, similarly: what would it take to mount the container to a path on the host, then use Python to perform file operations to alter the container, using something like [Plumbum](https://plumbum.readthedocs.io/)?

Is there another way to mount the container filesystem that allows more access from external programs?

**Comment by rhatdan** [comment] 2019-07-30 20:39
Access will be controlled via standard Linux protections. The mount point is defined within the tool, you can not mount to arbitrary locations, although you could bind mount the mount point to other locations.  once the image is mounted any process on the system can use it as long as it is in the same mount namespace and can see the mountpoint,  governed by DAC/User permissions.

**Comment by AndydeCleyre** [comment] 2019-07-30 21:33
Thank you for the quick explanation!

The mount location as-is is no problem. Somehow I missed the ways unshare can be used to run any arbitrary process. Is there a good and non-evil way to pack the unshare command into the shebang? Something like

```bash
#!/bin/env/buildah unshare -- /bin/env python3
```

**Comment by rhatdan** [comment] 2019-07-31 11:46
Why not create a command called bunshare

```
#!/bin/sh
exec $@
```
bunshare /bin/env python3

**Comment by AndydeCleyre** [comment] 2019-07-31 20:27
Well I'm looking to make scripts directly executable, and also able to mount containers. I'd rather not add extra files or path manipulations or special instructions on executing if not strictly necessary. 

And either I'm really misunderstanding the suggestion, or you left out `buildah unshare` altogether.

**Comment by rhatdan** [comment] 2019-08-01 10:19
Yes I guess my example should have been
exec buildah unshare -- $@


Upstream buildah unshare now has support for --mount CTRID.

**Comment by AndydeCleyre** [comment] 2019-08-02 18:52
FWIW, this works with `env` from modern GNU coreutils:

```bash
#!/usr/bin/env -S buildah unshare -- python3
```

**Comment by rhatdan** [comment] 2019-08-03 10:25
@AndydeCleyre Would you be interesting in writing up a short blog?  It might be of more interest if you wrote it using  podman rather then buildah.  I think podman has more users, but it would be exactly the same.
```
#!/usr/bin/env -S podman unshare -- python3
```
