### ISSUE TITLE
f32: "error copying layers ... error extracting image"

### ISSUE THREAD

**Issue by edsantiago** [containers/buildah#2275] opened 2020-04-04 12:42 UTC
buildah-1.14.6-1.fc32 [failed gating tests](https://jenkins-continuous-infra.apps.ci.centos.org/blue/organizations/jenkins/fedora-f32-build-pipeline/detail/fedora-f32-build-pipeline/255/pipeline/#step-248-log-583) with:
```

not ok 112 bud with COPY of single file creates absolute path with correct permissions
[2020-04-04T07:21:12.051Z]     # (from function `die' in file /usr/share/buildah/test/system/helpers.bash, line 174,
[2020-04-04T07:21:12.051Z]     #  from function `run_buildah' in file /usr/share/buildah/test/system/helpers.bash, line 162,
[2020-04-04T07:21:12.051Z]     #  in test file /usr/share/buildah/test/system/bud.bats, line 1111)
[2020-04-04T07:21:12.051Z]     #   `run_buildah bud --signature-policy ${TESTSDIR}/policy.json -t ${imgName} ${TESTSDIR}/bud/copy-create-absolute-path' failed
[2020-04-04T07:21:12.051Z]     # # [checking for: ubuntu]
[2020-04-04T07:21:12.051Z]     # # [restoring from cache: /tmp/buildah-image-cache.13132 / ubuntu]
[2020-04-04T07:21:12.051Z]     # Getting image source signatures
[2020-04-04T07:21:12.051Z]     # Copying blob sha256:bd25f1a1b0fed8e87ec48b23ad2c3739f581a8bc7d150ed0355d64b0005d5334
[2020-04-04T07:21:12.051Z]     # Copying blob sha256:319cf87c5aaaed9955879180d516cfceaaaee59a3a72da2da1ddcfd0091c0008
[2020-04-04T07:21:12.051Z]     # Copying blob sha256:61a33eacb101dc8f82feaa6ee0d133028a3e5ca435e37eabcfb6fbc34f0de122
[2020-04-04T07:21:12.051Z]     # Copying blob sha256:887fe6f52b3555c6f4db6e2ab96b98dc7bb865ecdfec97762fc6f835a2027403
[2020-04-04T07:21:12.051Z]     # Copying config sha256:84d0de4598f42a1cff7431817398c1649e571955159d9100ea17c8a091e876ee
[2020-04-04T07:21:12.051Z]     # Writing manifest to image destination
[2020-04-04T07:21:12.051Z]     # Storing signatures
[2020-04-04T07:21:12.051Z]     # Loaded image(s): localhost/ubuntu
[2020-04-04T07:21:12.051Z]     # $ /usr/bin/buildah bud --signature-policy /usr/share/buildah/test/system/policy.json -t ubuntu-image /usr/share/buildah/test/system/bud/copy-create-absolute-path
[2020-04-04T07:21:12.051Z]     # STEP 1: FROM ubuntu
[2020-04-04T07:21:12.051Z]     # STEP 2: COPY distutils.cfg /usr/lib/python3.7/distutils/distutils.cfg
[2020-04-04T07:21:12.051Z]     # STEP 3: RUN stat -c "permissions=%a" /usr/lib/python3.7/distutils
[2020-04-04T07:21:12.051Z]     # permissions=755
[2020-04-04T07:21:12.051Z]     # STEP 4: COMMIT ubuntu-image
[2020-04-04T07:21:12.051Z]     # error committing container for step {Env:[PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin] Command:run Args:[stat -c "permissions=%a" /usr/lib/python3.7/distutils] Flags:[] Attrs:map[] Message:RUN stat -c "permissions=%a" /usr/lib/python3.7/distutils Original:RUN stat -c "permissions=%a" /usr/lib/python3.7/distutils}: error copying layers and metadata for container "32c297fa6050dfb003b42c9baf17fd303f7a9c2165924eab8aa14aa7c2087b48": Error initializing source containers-storage:ubuntu-working-container: error extracting layer "9e8b048be6f2e6fb1eb13375c594501e8b183685e145643d5a520b96e9afa6c7": no such file or directory
[2020-04-04T07:21:12.051Z]     # [ rc=1 (** EXPECTED 0 **) ]
[2020-04-04T07:21:12.051Z]     # #/vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
[2020-04-04T07:21:12.051Z]     # #| FAIL: exit code is 1; expected 0
[2020-04-04T07:21:12.051Z]     # #\^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
I don't have time today to set up a virt and try to reproduce it. Even if it's a flake, I really don't like the looks of it.

Although it's tempting to blame `$TMPDIR`, I've seen lots of TMPDIR-related failures with buildah tests and this doesn't look like that: for one, when TMPDIR is too small, there are lots more errors. Here, there's only this one.

**Comment by edsantiago** [comment] 2020-04-06 14:47
Cannot reproduce manually. f32 virt with buildah-1.14.6-1.fc32; copied out the two `bud with COPY` tests into a separate `.bats` file, ran in loop for two hours.

Leaving this open because even if this is a transient, it's still an error that deserves attention from a buildah expert. If there's something else I can do to provide more information, or perhaps something I can try differently to reproduce, please lmk.

**Comment by vrothberg** [comment] 2020-04-06 14:49
@nalind, this looks like something for your pair of eyes.

**Comment by edsantiago** [comment] 2020-04-06 19:11
This is really weird. Now it's [rawhide failing](https://jenkins-continuous-infra.apps.ci.centos.org/blue/organizations/jenkins/fedora-rawhide-build-pipeline/detail/fedora-rawhide-build-pipeline/10539/pipeline/#step-248-log-588), same test, but completely different place. This time it's failing in `_prefetch()` which is podman, not buildah:
```
# [podman load from a file cached in /tmp]
# Storing signatures
#   lstat /tmp/tmp19342b1942dcf0c2070ab34f/root/vfs/dir/3c1fcef44107cd6175b87987b91eea89bf7eb2f01c3221da322b787f95c0808a/usr/src: no such file or directory
# Error: error pulling "": unable to pull dir:/tmp/buildah-image-cache.13148/ubuntu-.tar: error determining pull goal for image "dir:/tmp/buildah-image-cache.13148/ubuntu-.tar": error parsing dest reference name "localhost/tmp/buildah-image-cache.13148/ubuntu-.tar": error parsing named reference "localhost/tmp/buildah-image-cache.13148/ubuntu-.tar": invalid reference format
```
I have no idea what to make of this, but it seems eerily connected and worth logging.

**Comment by vrothberg** [comment] 2020-04-07 09:24
@edsantiago, can you point me to source of these tests? I recall _some_ issues of broken symlinks in Ubuntu images last year.

**Comment by edsantiago** [comment] 2020-04-07 12:33
Failing test is [bud.bats:1159](https://github.com/containers/buildah/blob/master/tests/bud.bats#L1159)

The unexpected `prefetch` failure is in [helpers.bash:71](https://github.com/containers/buildah/blob/master/tests/helpers.bash#L71)

Is there any reason to use ubuntu in these tests?

**Comment by vrothberg** [comment] 2020-04-08 08:49
Thanks, @edsantiago. I must have ran low on coffee as I was vgrepping in libpod instead of buildah. Going to look at it now :+1:

**Comment by vrothberg** [comment] 2020-04-08 09:09
I begin to feel it's not the Ubuntu image as the Ubuntu image has not been changed in the past 19 days. Also when converting the image into an oci-archive and loading that, I get the same checksums for the layers (see below):
```
buildah (master) $ podman load -i ubuntu-.tar
Getting image source signatures
Copying blob bd25f1a1b0fe done  
Copying blob 319cf87c5aaa done  
Copying blob 61a33eacb101 done  
Copying blob 887fe6f52b35 done  
Copying config 84d0de4598 done  
Writing manifest to image destination
Storing signatures
Loaded image(s): localhost/ubuntu
```

... same layers as in the logs:
```
[2020-04-06T18:16:25.179Z]     # Getting image source signatures
[2020-04-06T18:16:25.179Z]     # Copying blob sha256:bd25f1a1b0fed8e87ec48b23ad2c3739f581a8bc7d150ed0355d64b0005d5334
[2020-04-06T18:16:25.179Z]     # Copying blob sha256:319cf87c5aaaed9955879180d516cfceaaaee59a3a72da2da1ddcfd0091c0008
[2020-04-06T18:16:25.179Z]     # Copying blob sha256:61a33eacb101dc8f82feaa6ee0d133028a3e5ca435e37eabcfb6fbc34f0de122
[2020-04-06T18:16:25.180Z]     # Copying blob sha256:887fe6f52b3555c6f4db6e2ab96b98dc7bb865ecdfec97762fc6f835a2027403
[2020-04-06T18:16:25.180Z]     # Copying config sha256:84d0de4598f42a1cff7431817398c1649e571955159d9100ea17c8a091e876ee
[2020-04-06T18:16:25.180Z]     # Writing manifest to image destination
[2020-04-06T18:16:25.180Z]     # Storing signatures
[2020-04-06T18:16:25.180Z]     #   lstat /tmp/tmp19342b1942dcf0c2070ab34f/root/vfs/dir/3c1fcef44107cd6175b87987b91eea89bf7eb2f01c3221da322b787f95c0808a/usr/src: no such file or directory
```

**Comment by vrothberg** [comment] 2020-04-08 09:19
Running a test script locally which is loading the tar in a loop. Let's see if I can reproduce.

@edsantiago, how often are you seeing this error?

**Comment by giuseppe** [comment] 2020-04-08 10:34
no luck trying to reproduce it locally.  It seems unlikely to be caused by the size of TMPDIR.  I've tried to reproduce it with different sizes for TMPDIR and the test fails at different places but I could always see an error like "no space left on device".

**Comment by vrothberg** [comment] 2020-04-08 10:42
Same here. I ran the script for 90 minutes without a failure :(

**Comment by edsantiago** [comment] 2020-04-08 11:24
>how often are you seeing this error?

Only the one time reported in the initial comment, plus the probably-unrelated `prefetch`. As mentioned earlier, I was unable to reproduce it on a rawhide VM.

**Comment by rhatdan** [comment] 2020-08-05 15:43
Well since this has not happened again, Closing.  @edsantiago feel free to reopen if I mistaken.

**Closed by rhatdan** 2020-08-05 15:43 UTC
