### ISSUE TITLE
buildah bud doesn't work from current master on f28 (likely due to overlayfs)

### ISSUE THREAD

**Issue by EmilienM** [containers/buildah#1332] opened 2019-02-11 16:19 UTC
**Description**

Running buildah bud from master on fedora 28 doesn't work, and it works fine with buildah 1.6.

**Steps to reproduce the issue:**
Run the demo script: https://github.com/containers/buildah/blob/master/demos/buildah-bud-demo.sh

**Describe the results you received:**
```
buildah bud -t buildahbuddemo .
STEP 1: FROM docker://docker.io/fedora:latest
STEP 2: MAINTAINER William Henry
STEP 3: RUN dnf -y update; dnf -y clean all
STEP 4: RUN dnf -y install nginx --setopt install_weak_deps=false; dnf -y clean all                                                                           
STEP 5: RUN echo "daemon off;" >> /etc/nginx/nginx.conf
error building at step {Env:[PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin DISTTAG=f29container FGC=f29 FBR=f29] Command:run Args:[echo "daemon off;" >> /etc/nginx/nginx.conf] Flags:[] Attrs:map[] Message:RUN echo "daemon off;" >> /etc/nginx/nginx.conf Original:RUN echo "daemon off;" >> /etc/nginx/nginx.conf}: error while running runtime: exit status 1
```

**Describe the results you expected:**
Build should work.

**Output of `buildah version`:**

```
buildah version 1.7-dev (image-spec 1.0.0, runtime-spec 1.0.0)
```

**Output of `podman version` if reporting a `podman build` issue:**

```
Version:       1.0.0
Go Version:    go1.10.7
Git Commit:    "327964bfa96f91f39042b87b3e52388f448fd66e"
Built:         Mon Jan 14 20:38:13 2019
OS/Arch:       linux/amd64
```

**Output of `cat /etc/*release`:**

```
Fedora release 28 (Twenty Eight)
```

**Output of `uname -a`:**

```
Linux buildah.rdocloud 4.16.3-301.fc28.x86_64 #1 SMP Mon Apr 23 21:59:58 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Output of `cat /etc/containers/storage.conf`:**
default config

**Output of `buildah info`:**

```
{
    "host": {
        "Distribution": {
            "distribution": "fedora",
            "version": "28"
        },
        "MemTotal": 8363163648,
        "MenFree": 3868377088,
        "SwapFree": 0,
        "SwapTotal": 0,
        "arch": "amd64",
        "cpus": 4,
        "hostname": "buildah.rdocloud",
        "kernel": "4.16.3-301.fc28.x86_64",
        "os": "linux",
        "rootless": true,
        "uptime": "93h 50m 55.02s (Approximately 3.88 days)"
    },
    "store": {
        "ContainerStore": {
            "number": 0
        },
        "GraphDriverName": "vfs",
        "GraphOptions": null,
        "GraphRoot": "/home/fedora/.local/share/containers/storage",
        "GraphStatus": {},
        "ImageStore": {
            "number": 2
        },
        "RunRoot": "/run/user/1000"
    }
}
```

**Comment by rhatdan** [comment] 2019-02-11 16:21
Could you show us the error you are seeing?

**Comment by EmilienM** [comment] 2019-02-11 16:23
@rhatdan done

**Comment by EmilienM** [comment] 2019-02-11 16:28
```
DEBU[0000] Running ["runc" "create" "--bundle" "/tmp/buildah623609880" "--pid-file" "/tmp/buildah623609880/pid" "--no-new-keyring" "buildah-buildah623609880"] 
DEBU[0000] Running ["runc" "start" "buildah-buildah623609880"] 
/bin/sh: /etc/nginx/nginx.conf: No such file or directory
ERRO[0004] exit status 1                                
-bash: Fedora: command not found
```

**Comment by EmilienM** [comment] 2019-02-11 17:09
I'm trying again on a fresh environment...

**Comment by EmilienM** [comment] 2019-02-11 17:21
```
STEP 1: FROM docker://docker.io/fedora:latest                                                                                                           │······
DEBU[0000] error parsing image name "docker.io/fedora:latest" as given, trying with transport "docker://": Invalid image name "docker.io/fedora:latest",│······
 unknown transport "docker.io/fedora"                                                                                                                   │······
DEBU[0000] parsed reference into "[overlay@/home/fedora/.local/share/containers/storage+/run/user/1000:overlay.mount_program=/usr/bin/fuse-overlayfs]doc│······
ker.io/library/fedora:latest"                                                                                                                           │······
DEBU[0000] parsed reference into "[overlay@/home/fedora/.local/share/containers/storage+/run/user/1000:overlay.mount_program=/usr/bin/fuse-overlayfs]doc│······
ker.io/library/fedora:latest"                                                                                                                           │······
DEBU[0000] exporting opaque data as blob "sha256:26ffec5b4a8ad65083424903b7aa175953329413fe5cc4c0dac6fedbe81f2fbb"                                      │······
DEBU[0000] overlay: mount_data=lowerdir=/home/fedora/.local/share/containers/storage/overlay/l/HCXBIWMSS3KF33Y52UWCNI6OX3,upperdir=/home/fedora/.local/s│······
hare/containers/storage/overlay/f07ea5eb0818ae70fe665904b4fe87870725c4aebed862df325b4e24ea2cd10c/diff,workdir=/home/fedora/.local/share/containers/stora│······
ge/overlay/f07ea5eb0818ae70fe665904b4fe87870725c4aebed862df325b4e24ea2cd10c/work,context="system_u:object_r:container_file_t:s0:c374,c413"              │······
ERRO[0000] error unmounting /home/fedora/.local/share/containers/storage/overlay/f07ea5eb0818ae70fe665904b4fe87870725c4aebed862df325b4e24ea2cd10c/merged│······
: invalid argument                                                                                                                                      │······
error mounting new container: error mounting build container "c479ccf462d858570076ec404413d4075421bb4ffe688e5790ecbd8aa5fe4dd2": error creating overlay │······
mount to /home/fedora/.local/share/containers/storage/overlay/f07ea5eb0818ae70fe665904b4fe87870725c4aebed862df325b4e24ea2cd10c/merged: exit status 1    │······
ERRO[0000] exit status 1 
```

still failing.

**Comment by TomSweeneyRedHat** [comment] 2019-02-11 17:50
I hopped on @EmilienM vm for a bit and found this:
```
 [fedora@buildah ~]$ cat Dockerfile.alpine
FROM alpine
[fedora@buildah ~]$ buildah bud -t tom -f ~/Dockerfile.alpine .
STEP 1: FROM alpine
ERRO[0000] error unmounting /home/fedora/.local/share/containers/storage/overlay/d078ed780208ecddfbe6c4b3782b60b406d238783f767d8e2460b0617b10deca/merged: invalid argument 
error mounting new container: error mounting build container "07c1d6f699b2a1092af3bc471a7ffe60551561174ad5507ed15477f213c0efba": error creating overlay mount to /home/fedora/.local/share/containers/storage/overlay/d078ed780208ecddfbe6c4b3782b60b406d238783f767d8e2460b0617b10deca/merged: exit status 1
ERRO[0000] exit status 1  
```

I built a F28 vm, did 'dnf -y update' on it, then installed Buildah from GitHub.  The above build worked fine for me on both root and non-root on that vm.  I tried the demo script too and that worked fine on my vm.

@EmilienM tried to run the demo script as root and hit `container exited on segmentation fault`.  
He then went on and tried running his own scripts as root and that seemed to work fine.

@giuseppe any thoughts on the error message?  It smells like some kind of non-root user hiccup to me, but could be proven wrong.

**Comment by rhatdan** [comment] 2019-02-11 18:04
Does he have fuse-overlay installed or a bad config in ~/.config/containers/storage.conf?

**Comment by EmilienM** [comment] 2019-02-11 18:19
(containers-venv) [fedora@buildah ~]$ rpm -qa|grep fuse-overlayfs 
fuse-overlayfs-0.3-1.dev.git6d269aa.fc28.x86_64

**Comment by EmilienM** [comment] 2019-02-11 18:19
and no custom config, running defaults everywhere

**Comment by TomSweeneyRedHat** [comment] 2019-02-11 18:51
Talking with @EmilienM via IRC, he informed me that he's been referencing  https://www.scrivano.org/2018/07/13/fuse-overlayfs-moved-to-github-com-containers/ and trying a command like:

buildah  --storage-opt overlay2.fuse_program=/usr/bin/fuse-overlayfs bud -t tom -f Dockerfile.fedora .

Without success as of v1.7.  This worked in v1.6.

**Comment by EmilienM** [comment] 2019-02-11 18:52
cat .config/containers/storage.conf
```
[storage]
  driver = "overlay"
  runroot = "/run/user/1000"
  graphroot = "/home/fedora/.local/share/containers/storage"
  [storage.options]
    mount_program = "/usr/bin/fuse-overlayfs"
```

**Comment by giuseppe** [comment] 2019-02-11 20:03
I think this is a regression introduced by 3e175b1f7acff69b551ec5cf51e9cc25ef8d5ea2

it is already fixed upstream with 310363c1146b65e6b7f21134283905d8d6caaf47

Can someone confirm that v1.7 includes the first commit but not the second?

**Comment by giuseppe** [comment] 2019-02-11 20:34
@EmilienM the kernel 4.16.3-301.fc28.x86_64 you are using is too old.

FUSE file systems in a user namespaces are supported since Linux 4.18

**Comment by TomSweeneyRedHat** [comment] 2019-02-11 20:40
I see all of 310363c in upstream and also all of 3e175b1.  I'm thinking it's the kernel.  Sound like something we should add to the known issues page if so.

**Comment by TomSweeneyRedHat** [comment] 2019-02-11 20:40
didn't mean to close this.

**Comment by EmilienM** [comment] 2019-02-12 02:16
my issue is actually with rootless containers.

I got this runc error:

```
DEBU[0000] Running ["runc" "create" "--bundle" "/tmp/buildah037487595" "--pid-file" "/tmp/buildah037487595/pid" "--no-new-keyring" "--console-socket" "/tmp/buildah037487595/console.sock" "buildah-buildah037487595"]                                                                                                        
DEBU[0000] Running ["runc" "start" "buildah-buildah037487595"]                                                                                                 DEBU[0000] socket descriptor is for "/dev/ptmx"                                                                                                                DEBU[0000] control messages: [{{20 1 1} [14 0 0 0]}]                                                                                                           
DEBU[0000] fds: [14]                                                                                                                                           container exited on segmentation fault 
```

If I build with sudo, it works fine.

Full trace: http://paste.openstack.org/show/L7QNKnVKKi4TWWrXO1Xw/

**Comment by giuseppe** [comment] 2019-02-12 08:29
the segfault looks like an issue we had with SELinux also on Fedora 29.

Are you running in permissive mode?

**Comment by EmilienM** [comment] 2019-02-12 11:55
No, enforced.

---
Emilien Macchi

**Comment by rhatdan** [comment] 2019-02-12 14:49
Does it work in permissive, if yes, then could you attach the AVCs/.
ausearch -m avc -ts recent

**Comment by bogdando** [comment] 2019-02-12 17:20
As this is "installing from trunk" a testing effort, I wanted to ask for how exactly **Output of `podman version` if reporting a `podman build` issue** info correlates to **Output of `buildah version`**? I know buildah vendors podman and does not use the system installed version of it, right? Therefore, those versions prolly say nothing? Shall buildah's podman vendored version always match to the system installed podman for a proper testing? How to extract the vendored version used for buildah to compare those?

**Comment by EmilienM** [comment] 2019-02-12 17:30
@rhatdan switched to permissive, and ran again:
```
time->Tue Feb 12 17:21:20 2019
type=AVC msg=audit(1549992080.093:6821): avc:  denied  { getopt } for  pid=23526 comm="dnf" laddr=10.0.2.100 lport=53852 faddr=140.211.169.206 fport=443 scontext=system_u:system_r:container_t:s0:c278,c513 tcontext=system_u:system_r:container_t:s0:c278,c513 tclass=tcp_socket permissive=1
----
time->Tue Feb 12 17:21:20 2019
type=AVC msg=audit(1549992080.093:6822): avc:  denied  { getattr } for  pid=23526 comm="dnf" laddr=10.0.2.100 lport=53852 faddr=140.211.169.206 fport=443 scontext=system_u:system_r:container_t:s0:c278,c513 tcontext=system_u:system_r:container_t:s0:c278,c513 tclass=tcp_socket permissive=1
----
time->Tue Feb 12 17:22:20 2019
type=AVC msg=audit(1549992140.884:6827): avc:  denied  { setattr } for  pid=23526 comm="dnf" name=".build-id" dev="fuse" ino=3408800 scontext=system_u:system_r:container_t:s0:c278,c513 tcontext=system_u:object_r:fusefs_t:s0 tclass=dir permissive=1
----
time->Tue Feb 12 17:22:20 2019
type=AVC msg=audit(1549992140.885:6828): avc:  denied  { create } for  pid=23526 comm="dnf" name="68c248ced41419fcea3e5ba9158eb57fe14a5f;5c6300cb" scontext=system_u:system_r:container_t:s0:c278,c513 tcontext=system_u:object_r:fusefs_t:s0 tclass=lnk_file permissive=1
----
time->Tue Feb 12 17:22:20 2019
type=AVC msg=audit(1549992140.886:6829): avc:  denied  { setattr } for  pid=23526 comm="dnf" name="68c248ced41419fcea3e5ba9158eb57fe14a5f;5c6300cb" dev="fuse" ino=3674609 scontext=system_u:system_r:container_t:s0:c278,c513 tcontext=system_u:object_r:fusefs_t:s0 tclass=lnk_file permissive=1
----
time->Tue Feb 12 17:22:20 2019
type=AVC msg=audit(1549992140.886:6830): avc:  denied  { rename } for  pid=23526 comm="dnf" name="68c248ced41419fcea3e5ba9158eb57fe14a5f;5c6300cb" dev="fuse" ino=3674609 scontext=system_u:system_r:container_t:s0:c278,c513 tcontext=system_u:object_r:fusefs_t:s0 tclass=lnk_file permissive=1
----
time->Tue Feb 12 17:24:14 2019
type=AVC msg=audit(1549992254.278:6832): avc:  denied  { unlink } for  pid=31859 comm="yum" name="ld-linux-x86-64.so.2" dev="fuse" ino=3411025 scontext=system_u:system_r:container_t:s0:c278,c513 tcontext=system_u:object_r:fusefs_t:s0 tclass=lnk_file permissive=1
----
time->Tue Feb 12 17:21:20 2019
type=AVC msg=audit(1549992080.093:6821): avc:  denied  { getopt } for  pid=23526 comm="dnf" laddr=10.0.2.100 lport=53852 faddr=140.211.169.206 fport=443 scontext=system_u:system_r:container_t:s0:c278,c513 tcontext=system_u:system_r:container_t:s0:c278,c513 tclass=tcp_socket permissive=1
----
time->Tue Feb 12 17:21:20 2019
type=AVC msg=audit(1549992080.093:6822): avc:  denied  { getattr } for  pid=23526 comm="dnf" laddr=10.0.2.100 lport=53852 faddr=140.211.169.206 fport=443 scontext=system_u:system_r:container_t:s0:c278,c513 tcontext=system_u:system_r:container_t:s0:c278,c513 tclass=tcp_socket permissive=1
----
time->Tue Feb 12 17:22:20 2019
type=AVC msg=audit(1549992140.884:6827): avc:  denied  { setattr } for  pid=23526 comm="dnf" name=".build-id" dev="fuse" ino=3408800 scontext=system_u:system_r:container_t:s0:c278,c513 tcontext=system_u:object_r:fusefs_t:s0 tclass=dir permissive=1
----
time->Tue Feb 12 17:22:20 2019
type=AVC msg=audit(1549992140.885:6828): avc:  denied  { create } for  pid=23526 comm="dnf" name="68c248ced41419fcea3e5ba9158eb57fe14a5f;5c6300cb" scontext=system_u:system_r:container_t:s0:c278,c513 tcontext=system_u:object_r:fusefs_t:s0 tclass=lnk_file permissive=1
----
time->Tue Feb 12 17:22:20 2019
type=AVC msg=audit(1549992140.886:6829): avc:  denied  { setattr } for  pid=23526 comm="dnf" name="68c248ced41419fcea3e5ba9158eb57fe14a5f;5c6300cb" dev="fuse" ino=3674609 scontext=system_u:system_r:container_t:s0:c278,c513 tcontext=system_u:object_r:fusefs_t:s0 tclass=lnk_file permissive=1
----
time->Tue Feb 12 17:22:20 2019
type=AVC msg=audit(1549992140.886:6830): avc:  denied  { rename } for  pid=23526 comm="dnf" name="68c248ced41419fcea3e5ba9158eb57fe14a5f;5c6300cb" dev="fuse" ino=3674609 scontext=system_u:system_r:container_t:s0:c278,c513 tcontext=system_u:object_r:fusefs_t:s0 tclass=lnk_file permissive=1
----
time->Tue Feb 12 17:24:14 2019
type=AVC msg=audit(1549992254.278:6832): avc:  denied  { unlink } for  pid=31859 comm="yum" name="ld-linux-x86-64.so.2" dev="fuse" ino=3411025 scontext=system_u:system_r:container_t:s0:c278,c513 tcontext=system_u:object_r:fusefs_t:s0 tclass=lnk_file permissive=1
----
time->Tue Feb 12 17:24:13 2019
type=AVC msg=audit(1549992253.156:6831): avc:  denied  { setfcap } for  pid=31859 comm="yum" capability=31  scontext=system_u:system_r:container_t:s0:c278,c513 tcontext=system_u:system_r:container_t:s0:c278,c513 tclass=cap_userns permissive=1
```

It manages to build, but not to push the image to a local docker registry v2:
```
buildah --debug push --tls-verify=False 127.0.0.1:8787/master/fedora-binary-base:2019-02-11 docker://127.0.0.1:8787/master/fedora-binary-base:2019-02-11

Getting image source signatures
DEBU[0000] Manifest has MIME type application/vnd.oci.image.manifest.v1+json, ordered candidate list [application/vnd.oci.image.manifest.v1+json, application/vnd.docker.distribution.manifest.v2+json, application/vnd.docker.distribution.manifest.v1+prettyjws, application/vnd.docker.distribution.manifest.v1+json] 
DEBU[0000] ... will first try using the original manifest unmodified 
DEBU[0000] Checking /v2/master/fedora-binary-base/blobs/sha256:17beab58d693a5e55591675c3dcc5b575a44e476d125408102ce75348011f807 
DEBU[0000] GET https://127.0.0.1:8787/v2/               
DEBU[0000] Ping https://127.0.0.1:8787/v2/ err Get https://127.0.0.1:8787/v2/: http: server gave HTTP response to HTTPS client (&url.Error{Op:"Get", URL:"https://127.0.0.1:8787/v2/", Err:(*errors.errorString)(0xc4202f6010)}) 
DEBU[0000] GET https://127.0.0.1:8787/v1/_ping          
DEBU[0000] Ping https://127.0.0.1:8787/v1/_ping err Get https://127.0.0.1:8787/v1/_ping: http: server gave HTTP response to HTTPS client (&url.Error{Op:"Get", URL:"https://127.0.0.1:8787/v1/_ping", Err:(*errors.errorString)(0xc4202f61d0)}) 
DEBU[0000] Checking /v2/master/fedora-binary-base/blobs/sha256:419fd4aba856c9936ae53d96fabea5ac4ea38da4737068fce83c46bbd7f5c800 
Copying blob 17beab58d693: 0 B / 257.17 MiB [-------------------------------] 0s
Copying blob 419fd4aba856: 0 B / 264.99 MiB [-------------------------------] 0s
```

docker-distribution-2.6.2-7.git48294d9.fc28.x86_64
```
Redirecting to /bin/systemctl status docker-distribution.service
● docker-distribution.service - v2 Registry server for Docker
   Loaded: loaded (/usr/lib/systemd/system/docker-distribution.service; enabled; vendor preset: disabled)
   Active: active (running) since Tue 2019-02-12 01:58:56 UTC; 15h ago
 Main PID: 579 (registry)
    Tasks: 14 (limit: 4915)
   Memory: 288.6M
   CGroup: /system.slice/docker-distribution.service
           └─579 /usr/bin/registry serve /etc/docker-distribution/registry/config.yml
```

**Comment by EmilienM** [comment] 2019-02-12 17:41
More logs: https://paste.fedoraproject.org/paste/oaAz~nodFQ~kaHtQwQSOqg

**Comment by EmilienM** [comment] 2019-02-12 18:02
A demo of the proof that it works fine in buildah 1.6 and not on master:
https://asciinema.org/a/yQ7PbHGvMjdQP8GXQb4xhPF35

**Comment by TomSweeneyRedHat** [comment] 2019-02-12 18:50
@boaz0 It's complicated.  Buildah is vendored into Podman and Libpod which is the library that Podman uses, is vendored into Buildah.  So the `podman version` value shows the version of Podman that you're running.  If you do `podman info`, one of the values in that output is "BuildahVersion" which is the version of Buildah that was vendored into that particular Podman.

How to correlate based solely on that info is tricky at best.  @rhatdan brought that up recently and we've chatted about ways to lessen the trickiness going forward.  If you'd like to talk about this further, I'm happy to do so, but please open up an RFE issue, I don't want to get a separate thread going in this particular PR.

**Comment by rhatdan** [comment] 2019-02-13 05:57
The AVCs indicate container-selinux is either old or did not install correctly.

yum -y update container-selinux --enaberepo=updates-testing
yum -y reinstall container-selinux

Make sure nothing blows up when you do this.
rpm -q container-selinux

**Comment by bogdando** [comment] 2019-02-13 10:08
@TomSweeneyRedHat thank you for explaining the versioning schemes. I raised that topic here only as it happened that this particular bug (and the submission form) seems missing then the vendored libpod version to be shown for ``buildah info``, and ``podman info`` to show the vendored buildah version. So these numbers might be good to have and check if things are set nicely. That is only important though perhaps when installing things from source instead of packages.

**Comment by giuseppe** [comment] 2019-02-13 11:23
it seems you have a user file that overrides the global configuration:

```
time="2019-02-12T17:40:56Z" level=debug msg="registry "127.0.0.1:8787" is not marked as blocked in registries configuration "/home/fedora/.config/containers/registries.conf"" 
```

you can either use `/home/fedora/.config/containers/registries.conf` or delete it then the global configuration file will be used

**Comment by rhatdan** [comment] 2019-02-13 11:25
I did not know we supported local versions of this file.  We probably need to think about this.  We should check the global blocked registries, and enforce them on the local podman.  Since if an admin says no image from hackme.com then we should enforce this on rootless and rootful,

**Comment by EmilienM** [comment] 2019-02-13 23:12
@giuseppe I don't understand your comment. I didn't touch any config file and with Buildah 1.6 everything works fine (see my demo, linked in https://github.com/containers/buildah/issues/1332#issuecomment-462867917).

I removed `/home/fedora/.config/containers/registries.conf`, my `/etc/containers/registries.conf` has:

```
[registries.insecure]
registries = ['127.0.0.1:8787', 'localhost:8787']
```

And I'm running Buildah as root, and it fails:
```
Stdout: 'Get https://127.0.0.1:8787/v2/: http: server gave HTTP response to HTTPS client\n'
```

So there is an actual bug for when the registry is HTTP.

**Comment by giuseppe** [comment] 2019-02-14 08:53
> @giuseppe I don't understand your comment. I didn't touch any config file and with Buildah 1.6 everything works fine (see my demo, linked in [#1332 (comment)](https://github.com/containers/buildah/issues/1332#issuecomment-462867917)).
> 
> I removed `/home/fedora/.config/containers/registries.conf`, my `/etc/containers/registries.conf` has:
> 
> ```
> [registries.insecure]
> registries = ['127.0.0.1:8787', 'localhost:8787']
> ```
> 
> And I'm running Buildah as root, and it fails:

in the demo I see you are running rootless?  So that could have changed, since now we have the possibility of having a per-user `registries.conf` file, that overrides the global one.

If you are also seeing the same problem when running as root, then it is something different.

This is what I see locally with buildah from master:
```
$ cat /etc/containers/registries.conf 
 [...]
[registries.insecure]
#registries = ['localhost:5000']
 [...]

$ sudo ~/gopath/src/github.com/containers/buildah/buildah push tmp docker://localhost:5000/foo
Getting image source signatures
Copying blob 503e53e365f3: 0 B / 5.52 MiB [---------------------------------] 0s
Copying blob 16949929c3f6: 0 B / 11.13 MiB [--------------------------------] 0s
Get https://localhost:5000/v2/: http: server gave HTTP response to HTTPS client

$ sudo sed -i -e's|#registries|registries|' /etc/containers/registries.conf # Uncomment the line in registries.conf

$ sudo ~/gopath/src/github.com/containers/buildah/buildah push tmp docker://localhost:5000/foo
Getting image source signatures
Copying blob 503e53e365f3: 5.52 MiB / 5.52 MiB [============================] 0s
Copying blob 16949929c3f6: 11.13 MiB / 11.13 MiB [==========================] 0s
Copying config 71858c14eb90: 704 B / 704 B [================================] 0s
Writing manifest to image destination
Storing signatures
Successfully pushed //localhost:5000/foo:latest@sha256:96f22c635d804c820dbc36a9493ece74076bbf57a0df6955db2d4879dd20ec4d

```


Could you attach the log of `buildah --debug push ...` when you are running as root?

**Comment by EmilienM** [comment] 2019-02-14 15:18
@giuseppe 

```
(containers-venv) [fedora@buildah ~]$ sudo buildah --debug push --tls-verify=False 127.0.0.1:8787/master/fedora-binary-base:2019-02-11 docker://127.0.0.1:8787/master/fedora-binary-base:2019-02-11
DEBU[0000] [graphdriver] trying provided driver "overlay" 
DEBU[0000] overlay test mount with multiple lowers succeeded 
DEBU[0000] overlay test mount indicated that metacopy is not being used 
DEBU[0000] backingFs=extfs, projectQuotaSupported=false, useNativeDiff=true, usingMetacopy=false 
DEBU[0000] registry "127.0.0.1:8787" is not marked as blocked in registries configuration "/etc/containers/registries.conf" 
DEBU[0000] parsed reference into "[overlay@/var/lib/containers/storage+/var/run/containers/storage:overlay.mountopt=nodev]127.0.0.1:8787/master/fedora-binary-base:2019-02-11" 
DEBU[0000] Using registries.d directory /etc/containers/registries.d for sigstore configuration 
DEBU[0000]  Using "default-docker" configuration        
DEBU[0000]   Using file:///var/lib/atomic/sigstore      
DEBU[0000] Looking for TLS certificates and private keys in /etc/docker/certs.d/127.0.0.1:8787 
DEBU[0000] Using blob info cache at /var/lib/containers/cache/blob-info-cache-v1.boltdb 
DEBU[0000] IsRunningImageAllowed for image containers-storage:[overlay@/var/lib/containers/storage]127.0.0.1:8787/master/fedora-binary-base:2019-02-11@8f8ea4757483a88f4d5f39e7b694408bdbc4aae92fc5fa47abc6ffef240dfb76 
DEBU[0000]  Using default policy section                
DEBU[0000]  Requirement 0: allowed                      
DEBU[0000] Overall: allowed                             
Getting image source signatures
DEBU[0000] Manifest has MIME type application/vnd.oci.image.manifest.v1+json, ordered candidate list [application/vnd.oci.image.manifest.v1+json, application/vnd.docker.distribution.manifest.v2+json, application/vnd.docker.distribution.manifest.v1+prettyjws, application/vnd.docker.distribution.manifest.v1+json] 
DEBU[0000] ... will first try using the original manifest unmodified 
DEBU[0000] Checking /v2/master/fedora-binary-base/blobs/sha256:17beab58d693a5e55591675c3dcc5b575a44e476d125408102ce75348011f807 
DEBU[0000] GET https://127.0.0.1:8787/v2/               
DEBU[0000] Ping https://127.0.0.1:8787/v2/ err Get https://127.0.0.1:8787/v2/: http: server gave HTTP response to HTTPS client (&url.Error{Op:"Get", URL:"https://127.0.0.1:8787/v2/", Err:(*errors.errorString)(0xc00018e730)}) 
DEBU[0000] GET https://127.0.0.1:8787/v1/_ping          
DEBU[0000] Ping https://127.0.0.1:8787/v1/_ping err Get https://127.0.0.1:8787/v1/_ping: http: server gave HTTP response to HTTPS client (&url.Error{Op:"Get", URL:"https://127.0.0.1:8787/v1/_ping", Err:(*errors.errorString)(0xc00018e8e0)}) 
DEBU[0000] Checking /v2/master/fedora-binary-base/blobs/sha256:10405dd0a16381f017288248e72c7826ed9da999149ea2f7846bbeabaf3fb2da 
Copying blob 17beab58d693: 0 B / 257.17 MiB [-------------------------------] 0s
Copying blob 10405dd0a163: 0 B / 265.90 MiB [-------------------------------] 0s
Get https://127.0.0.1:8787/v2/: http: server gave HTTP response to HTTPS client
```

```
(containers-venv) [fedora@buildah ~]$ sudo cat /etc/containers/registries.conf
# This is a system-wide configuration file used to
# keep track of registries for various container backends.
# It adheres to TOML format and does not support recursive
# lists of registries.

# The default location for this configuration file is /etc/containers/registries.conf.

# The only valid categories are: 'registries.search', 'registries.insecure', 
# and 'registries.block'.

[registries.search]
registries = ['docker.io', 'registry.fedoraproject.org', 'quay.io', 'registry.access.redhat.com', 'registry.centos.org']

# If you need to access insecure registries, add the registry's fully-qualified name.
# An insecure registry is one that does not have a valid SSL certificate or only does HTTP.
[registries.insecure]
registries = ['127.0.0.1:8787', 'localhost:8787']


# If you need to block pull access from a registry, uncomment the section below
# and add the registries fully-qualified name.
#
# Docker only
[registries.block]
registries = []
```

**Comment by giuseppe** [comment] 2019-02-14 15:48
interesting, it seems that `--tls-verify=False` causes the issue.  It is not honored and it also inhibit the change in the `registries.conf` file.

@mtrmac do you know what is going on here?

**Comment by mtrmac** [comment] 2019-02-14 18:55
> interesting, it seems that `--tls-verify=False` causes the issue. It is not honored and it also inhibit the change in the `registries.conf` file.

@baude 

- https://github.com/containers/buildah/blob/e4c4d465bff217c1101b672d9eae0bc507667a35/cmd/buildah/push.go#L31 is a confusing red herring, nothing ever uses the value. Why have it there?!
- https://github.com/containers/buildah/blob/e4c4d465bff217c1101b672d9eae0bc507667a35/pkg/parse/parse.go#L252-L257 is where the value is set, and it gets the polarity wrong.

(Besides fixing the polarity, I’d suggest _never_ using the string-based flag lookups (`FlagSet.GetBool` and the like); instead, have _all_ options be defined with the `*Var(&field, …)` options (defining a new `Value` types if necessary), so that CLI parsing into a `struct` and executing on the options is clearly separated, and ordinary Go tools for finding variable references work.)

Compare https://github.com/containers/skopeo/blob/b8b9913695702d9b426cc0e72641e6be9aab9965/cmd/skopeo/utils.go#L52-L138 + https://github.com/containers/skopeo/blob/b8b9913695702d9b426cc0e72641e6be9aab9965/cmd/skopeo/inspect.go#L41 — with urfave/cli, but the same design should work with cobra as well.

**Closed** 2019-02-20 19:38 UTC
