### ISSUE TITLE
"rm" fails with EIO on btrfs when piling up layers

### ISSUE THREAD

**Issue by dawagner** [containers/buildah#3832] opened 2022-03-22 14:50 UTC
**Description**

When piling up a large number of layers that remove/recreate folders, **using btrfs** as underlying filesystem, "rm" or "rmdir" fails to remove directories at some point, with EIO.

**Steps to reproduce the issue:**

The following script reproduces the issue:

```sh
#!/bin/bash
container=$(buildah from alpine:latest)
buildah run $container mkdir -p /a/b
buildah commit $container buildah-btrfs-rmdir-bug:0

for i in $(seq 0 50); do
  container=$(buildah from buildah-btrfs-rmdir-bug:$i);
  buildah run $container -- sh -c "rm -rf /a; mkdir -p /a/b; echo $i > /a/b/c";
  buildah commit $container buildah-btrfs-rmdir-bug:$((i + 1));
done
```

At some point, it fails with: `rm: can't remove '/a/b': I/O error`.

I can't reproduce the issue on ext4.

**Output of `rpm -q buildah` or `apt list buildah`:**

```
buildah-1.23.0-1.fc33.x86_64
```

**Output of `buildah version`:**

```
Version:         1.23.0
Go Version:      go1.15.14
Image Spec:      1.0.1-dev
Runtime Spec:    1.0.2-dev
CNI Spec:        0.4.0
libcni Version:  
image Version:   5.16.0
Git Commit:      
Built:           Thu Jan  1 01:00:00 1970
OS/Arch:         linux/amd64
BuildPlatform:   linux/amd64
```

**Output of `cat /etc/*release`:**

```
Fedora release 33 (Thirty Three)
NAME=Fedora
VERSION="33 (Workstation Edition)"
ID=fedora
VERSION_ID=33
VERSION_CODENAME=""
PLATFORM_ID="platform:f33"
PRETTY_NAME="Fedora 33 (Workstation Edition)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:33"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f33/system-administrators-guide/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=33
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=33
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Workstation Edition"
VARIANT_ID=workstation
Fedora release 33 (Thirty Three)
Fedora release 33 (Thirty Three)
```

**Output of `uname -a`:**

```
Linux *** 5.14.18-100.fc33.x86_64 #1 SMP Fri Nov 12 17:38:44 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Output of `cat /etc/containers/storage.conf`:**

```
[storage]

# Default Storage Driver, Must be set for proper operation.
driver = "overlay"

# Temporary storage location
runroot = "/run/containers/storage"

# Primary Read/Write location of container storage
graphroot = "/var/lib/containers/storage"

# Storage path for rootless users
#
# rootless_storage_path = "$HOME/.local/share/containers/storage"

[storage.options]

additionalimagestores = [
]

[storage.options.overlay]

# mountopt specifies comma separated list of extra mount options

mountopt = "nodev"

[storage.options.thinpool]
```

**Comment by rhatdan** [comment] 2022-03-22 14:59
@giuseppe PTAL

**Comment by giuseppe** [comment] 2022-03-23 10:18
could you try with a newer Fedora?  Fedora 33 is EOL

**Comment by giuseppe** [comment] 2022-03-25 08:22
closing the issue since it is likely caused by the kernel on a not supported system.

Please reopen if it still exists with a newer kernel

**Closed by giuseppe** 2022-03-25 08:22 UTC
