### ISSUE TITLE
'org.opencontainers.image.base.digest' label is wrong with '--layers' option

### ISSUE THREAD

**Issue by Michkov** [containers/buildah#4657] opened 2023-03-13 10:24 UTC
**Description**

When running buildah bud with --layers option then "org.opencontainers.image.base.digest" is not set properly.
Dockerfile:
```
FROM registry.access.redhat.com/ubi9/openjdk-17:1.13-10.1669632202

RUN echo $RANDOM > /usr/test
RUN echo $RANDOM > /usr/test2
RUN echo $RANDOM > /usr/test3
```

**Steps to reproduce the issue:**
1. Build Docker file from description - `buildah build --no-cache -t test:abc .`
2. Check  "org.opencontainers.image.base.digest"
3. Build Docker file from description - `buildah build --no-cache --layers -t test:abc .`
4. Check  "org.opencontainers.image.base.digest"

**Describe the results you received:**
Base digests are different:
2. sha256:08eb4a3026631e9114e057aa96825593c6314f8132aeb3ab068f38b56f9d5a26
4. sha256:49a96f7b362bb04ba64d74e50390f26141cfbc820492501c9caac753c8426181

**Describe the results you expected:**
Base digests should be same:
2. sha256:08eb4a3026631e9114e057aa96825593c6314f8132aeb3ab068f38b56f9d5a26
4. sha256:08eb4a3026631e9114e057aa96825593c6314f8132aeb3ab068f38b56f9d5a26

**Output of `rpm -q buildah` or `apt list buildah`:**

```
buildah-1.29.1-1.fc37.x86_64
buildah-1.26.2-1.el9_0.x86_64
```

**Comment by flouthoc** [comment] 2023-03-13 11:03
I tried reproducing this issue and it does not persists on the `upstream` `main` branch, could you please try again with the latest version

**Comment by Michkov** [comment] 2023-03-13 11:24
@flouthoc correct, I cannot reproduce it in main branch.

**Comment by flouthoc** [comment] 2023-03-13 11:30
Cool I'm closing this issue since this is fixed in upstream.

**Closed by flouthoc** 2023-03-13 11:30 UTC
