### ISSUE TITLE
User is not in group after useradd, in sucsessive RUN commands.

### ISSUE THREAD

**Issue by ligowigo** [containers/buildah#3988] opened 2022-05-12 23:59 UTC
**Description**

When a new user is added with group membership it does not have that membership until the container is started. In the below examples when the `groups` command is run after the `useradd` the user is not in the sudo group. However in the expected results (collected with docker) the user is in the sudo group.

When I start the container after the build and run `groups` it is in the sudo group. 

**Steps to reproduce the issue:**
Build this Dockerfile
```
FROM registry.hub.docker.com/library/debian:latest

RUN useradd -rm -d /home/controls -s /bin/bash -g root -G sudo -u 1001 controls
USER controls
RUN groups
```

**Describe the results you received:**
```
STEP 1: FROM registry.hub.docker.com/library/debian:latest
Getting image source signatures
Copying blob 67e8aa6c8bbc done
Copying config c4905f2a4f done
Writing manifest to image destination
Storing signatures
STEP 2: RUN useradd -rm -d /home/controls -s /bin/bash -g root -G sudo -u 1001 controls
--> 892703446c5
STEP 3: USER controls
--> dbfc0a07306
STEP 4: RUN groups
root                                           <------ NOT in sudo group
STEP 5: COMMIT
--> 1c6cfa1c078
```

**Describe the results you expected:**
Docker output
```
Step 1/4 : FROM ubuntu:latest
latest: Pulling from library/ubuntu
125a6e411906: Pull complete
Digest: sha256:26c68657ccce2cb0a31b330cb0be2b5e108d467f641c62e13ab40cbec258c68d
Status: Downloaded newer image for ubuntu:latest
 ---> d2e4e1f51132
Step 2/4 : RUN useradd -rm -d /home/controls -s /bin/bash -g root -G sudo -u 1001 controls
 ---> Running in e94abedf08d5
Removing intermediate container e94abedf08d5
 ---> 734b556469df
Step 3/4 : USER controls
 ---> Running in f30c9094b85b
Removing intermediate container f30c9094b85b
 ---> 6aeeacd718b0
Step 4/4 : RUN groups
 ---> Running in c2d2e4ef20e1
root sudo                                                 <------ IN sudo group as expected
Removing intermediate container c2d2e4ef20e1
 ---> 0e74000dde32
Successfully built 0e74000dde32
```

**Output of `rpm -q buildah` or `apt list buildah`:**

```
buildah/stable,now 1.19.6+dfsg1-1+b6 amd64 [installed,automatic]
```

**Output of `buildah version`:**

```
Version:         1.19.6
Go Version:      go1.15.9
Image Spec:      1.0.1
Runtime Spec:    1.0.2-dev
CNI Spec:        0.4.0
libcni Version:
image Version:   5.10.3
Git Commit:
Built:           Wed Dec 31 16:00:00 1969
OS/Arch:         linux/amd64

```

**Output of `podman version` if reporting a `podman build` issue:**

```
Version:      3.0.1
API Version:  3.0.0
Go Version:   go1.15.15
Built:        Wed Dec 31 16:00:00 1969
OS/Arch:      linux/amd64
```

**Output of `cat /etc/*release`:**

```
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

**Output of `uname -a`:**

```
Linux x1cymac 5.10.0-14-amd64 #1 SMP Debian 5.10.113-1 (2022-04-29) x86_64 GNU/Linux
```

**Output of `cat /etc/containers/storage.conf`:**

```
Don't have that file.
```

**Comment by Dexus** [comment] 2022-05-13 06:35
I cant reproduce this with 1.26.1

```
[root@archbuild test]# nano Dockerfile
FROM registry.hub.docker.com/library/debian:latest

RUN useradd -rm -d /home/controls -s /bin/bash -g root -G sudo -u 1001 controls
USER controls
RUN groups

[root@archbuild test]# buildah build -t demo/test
STEP 1/4: FROM registry.hub.docker.com/library/debian:latest
Trying to pull registry.hub.docker.com/library/debian:latest...
Getting image source signatures
Copying blob 67e8aa6c8bbc done  
Copying config c4905f2a4f done  
Writing manifest to image destination
Storing signatures
STEP 2/4: RUN useradd -rm -d /home/controls -s /bin/bash -g root -G sudo -u 1001 controls
STEP 3/4: USER controls
STEP 4/4: RUN groups
root sudo
COMMIT demo/test
Getting image source signatures
Copying blob 78658088978a skipped: already exists  
Copying blob 6149ae3fa3fe done  
Copying config 02da77c8a3 done  
Writing manifest to image destination
Storing signatures
--> 02da77c8a39
Successfully tagged localhost/demo/test:latest
02da77c8a3921a54c962d2e0dc46e7a4573fcd5ae259d257f789b329a4d33159

[root@archbuild test]# buildah --version
buildah version 1.26.1 (image-spec 1.0.2-dev, runtime-spec 1.0.2-dev)
```

**Comment by flouthoc** [comment] 2022-05-13 07:31
Hi @ligowigo , @Dexus is correct I don't think this bug persists on upstream anymore. Afaik something for rootless was fixed here: https://github.com/containers/buildah/pull/3593 but currently this bug does not exists on upstream for both rootless and rootful.

I am closing this issue but please feel free to re-open if you feel something is unresolved.
Thanks

**Closed by flouthoc** 2022-05-13 07:31 UTC
