### ISSUE TITLE
better error message for conflicting storage driver settings

### ISSUE THREAD

**Issue by dustymabe** [containers/buildah#1157] opened 2018-11-06 03:37 UTC
**Description**

If I tell rootless podman to use overlay rather than vfs but I had already run podman before I changed the configuration then I get an error message that is confusing:

```
[dustymabe@dhcp137-98 weechat]$ rpm -q kernel podman
kernel-4.18.16-300.fc29.x86_64
podman-0.10.1-1.gite4a1553.fc29.x86_64
[dustymabe@dhcp137-98 weechat]$ cat ~/.config/containers/storage.conf 
[storage]
driver = "overlay"

[storage.options]
mount_program = "/usr/bin/fuse-overlayfs"
[dustymabe@dhcp137-98 weechat]$ ls /usr/bin/fuse-overlayfs 
/usr/bin/fuse-overlayfs
[dustymabe@dhcp137-98 weechat]$ 
[dustymabe@dhcp137-98 weechat]$ bash build.sh 
+ podman build -t weechat --layers ./
could not get runtime: database graph driver name vfs does not match our graph driver name overlay: database configuration mismatch
```

We could change the error message to be more helpful like:

```
Configuration specifies overlay storage driver but detected vfs at ~/.local/share/containers/storage/
Please change the configuration or clean up storage at ~/.local/share/containers/storage/ before continuing.
```

Also related is whether or not we should support multiple drivers at one time (discussion started [here](https://github.com/containers/buildah/issues/1040#issuecomment-434317794)), but I think that should be a separate ticket/discussion.

**Comment by rhatdan** [comment] 2018-11-06 11:54
I would prefer to support multiple storages, but this is a better solution then what we have now.
@TomSweeneyRedHat Could you fix this.

**Comment by rhatdan** [comment] 2018-11-27 19:42
@TomSweeneyRedHat Any progress on this?
@QiWang19 If tom does not have time, could you look at it?

**Comment by TomSweeneyRedHat** [comment] 2018-11-27 19:48
@rhatdan I'd taken a very quick look at this and didn't see a quick/easy fix so stacked it up.  Hopefully I can be proven wrong.  @QiWang19 if you want to grab it, feel free.

**Comment by QiWang19** [comment] 2018-11-27 19:54
@TomSweeneyRedHat :ok_hand:  I'll also take a look at it

**Comment by rhatdan** [comment] 2018-11-28 15:20
I have a PR to allow users to use multiple storage drivers, which would eliminate this error.

**Comment by TomSweeneyRedHat** [comment] 2019-01-29 19:37
@rhatdan I think you fixed this.  Can you tag your PR here if so and close this?

**Comment by rhatdan** [comment] 2019-01-30 08:48
It has not been merged yet and it was for podman.   But why is this a buildah issue?  Buildah does not have this issue.  It is caused by the libpod database.

**Closed by rhatdan** 2019-01-30 08:48 UTC
