### ISSUE TITLE
debian packaging: file conflict between buildah and containers common

### ISSUE THREAD

**Issue by astronouth7303** [containers/buildah#2371] opened 2020-05-23 16:39 UTC
**Description**

There is a conflict between the `buildah` and `containers-common`. Both are shipping `/etc/containers/policy.json`.

```
% sudo apt install buildah
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Suggested packages:
  containers-storage
The following NEW packages will be installed:
  buildah
0 upgraded, 1 newly installed, 0 to remove and 1 not upgraded.
Need to get 0 B/6838 kB of archives.
After this operation, 26.4 MB of additional disk space will be used.
(Reading database ... 222686 files and directories currently installed.)
Preparing to unpack .../buildah_1.11.6-1_amd64.deb ...
Unpacking buildah (1.11.6-1) ...
dpkg: error processing archive /var/cache/apt/archives/buildah_1.11.6-1_amd64.deb (--unpack):
 trying to overwrite '/etc/containers/policy.json', which is also in package containers-common 1.0.0~2
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Errors were encountered while processing:
 /var/cache/apt/archives/buildah_1.11.6-1_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

Note that this is not the kind of error that happens for residual config or if the user changes the config from what was installed.

I am using the project kubic mirror. However, in the past suse has bounced the debian side of project kubic back to upstream.

Package versions:

* `buildah` (1.11.6-1)
* `containers-common` (`1.0.0~2`, dependency of podman)
* `podman` (`1.8.0~2`, blocked from upgrading to `1.9.2~3`)

```
% apt list buildah containers-common                 
Listing... Done
buildah/testing 1.11.6-1 amd64
buildah/unknown 1.14.9~1 arm64
buildah/unknown 1.14.9~1 armhf
buildah/testing 1.11.6-1 i386
buildah/unknown 1.14.9~1 ppc64el
containers-common/unknown,now 1.0.0~2 all [installed,automatic]
```

<details>
<summary>The podman issue</summary>
I don't think this is the primary issue, but I figured I'd include it anyways.

```
% sudo apt upgrade podman   
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 podman : Depends: catatonit but it is not going to be installed
          Depends: conmon (>= 2.0.16~1) but 2.0.9-1 is to be installed
          Depends: containernetworking-plugins (>= 0.8.6~1) but 0.8.5-1 is to be installed
          Depends: podman-plugins but it is not going to be installed
          Recommends: crun but it is not going to be installed
```

* `conmon` 2.0.16 isn't available in any of the repos for amd64 (just arm and ppc)
* `containernetworking-plugins` is similar

```
% apt list containernetworking-plugins podman-plugins
Listing... Done
containernetworking-plugins/testing,now 0.8.5-1 amd64 [installed,automatic]
containernetworking-plugins/unknown 0.8.6~1 arm64
containernetworking-plugins/unknown 0.8.6~1 armhf
containernetworking-plugins/testing 0.8.5-1 i386
containernetworking-plugins/unknown 0.8.6~1 ppc64el
podman-plugins/unknown 0.0.0~1 amd64
podman-plugins/unknown 0.0.0~1 arm64
podman-plugins/unknown 0.0.0~1 armhf
podman-plugins/unknown 0.0.0~1 ppc64el
```
</details>

(I'm deliberately omitting the rest of the template because this is a packaging issue not a runtime issue, or it's been given above.)

**Comment by vrothberg** [comment] 2020-05-25 08:40
Thanks for the report!

@lsm5 PTAL

**Comment by lsm5** [comment] 2020-05-25 14:24
> I am using the project kubic mirror. However, in the past suse has bounced the debian side of project kubic back to upstream.

Not quite sure what you mean by `bounced back to upstream` here.

> 
> Package versions:
> 
>     * `buildah` (1.11.6-1)

This seems to be from the default debian repository and not Kubic. Would you mind uninstalling this and retrying `apt install buildah containers-common`. AFAICT, that should fetch the latest buildah from kubic which won't conflict with containers-common.

Once this is working, we can revisit the podman install issue.

**Comment by lsm5** [comment] 2020-05-25 14:31
@astronouth7303 Btw, just to confirm, if stability and production-use are your main requirements and you can't afford any occasional hiccups, I'd recommend sticking with the version from the default debian repos, even if they are way behind upstream releases. podman I guess has landed in the debian unstable repos as well.

**Comment by astronouth7303** [comment] 2020-05-25 14:39
> This seems to be from the default debian repository and not Kubic. Would you mind uninstalling this and retrying apt install buildah containers-common. AFAICT, that should fetch the latest buildah from kubic which won't conflict with containers-common.

From my `apt list` output, that's the version available for amd64. Which is weird, because I can see it [in the repo](http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/Debian_Testing/amd64/). And yes, I did just update and check because kubic uploaded buildah packages today.

**Comment by astronouth7303** [comment] 2020-05-25 14:39
> @astronouth7303 Btw, just to confirm, if stability and production-use are your main requirements and you can't afford any occasional hiccups, I'd recommend sticking with the version from the default debian repos, even if they are way behind upstream releases. podman I guess has landed in the debian unstable repos as well.

I'm already running debian testing. :stuck_out_tongue:

**Comment by lsm5** [comment] 2020-05-25 14:45
> > This seems to be from the default debian repository and not Kubic. Would you mind uninstalling this and retrying apt install buildah containers-common. AFAICT, that should fetch the latest buildah from kubic which won't conflict with containers-common.
> 
> From my `apt list` output, that's the version available for amd64. Which is weird, because I can see it [in the repo](http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/Debian_Testing/amd64/). And yes, I did just update and check because kubic uploaded buildah packages today.
> 
> And the current status of buildah on that box is uninstalled.

Weird, how about an `apt clean all` followed by the usual apt update and apt install?

This is what I see:
```
buildah/unknown,now 1.14.9~1 amd64 [installed]
buildah/unknown 1.14.9~1 arm64
buildah/unknown 1.14.9~1 armhf
buildah/unknown 1.14.2~1 ppc64el
```

**Comment by lsm5** [comment] 2020-05-25 18:01
@astronouth7303 I'm gonna close this. I'm able to install buildah 1.14.9, podman 1.9.3 and containers-common 1.0.0 from the kubic testing repo without issues.

Please re-open if the latest builds don't solve the issue for you.

**Closed by lsm5** 2020-05-25 18:01 UTC
Labels: obs, packaging

**Comment by tomtom94** [comment] 2022-05-21 13:59
@vrothberg @lsm5 I just encountered the issue in my VM Ubuntu 20.04 LTS

Since last Friday I got that
```
Unpacking containers-common (100:1-22) ...
dpkg: error processing archive /tmp/apt-dpkg-install-HDkSYr/22-containers-common_100%3a1-22_all.deb (--unpack):
 trying to overwrite '/etc/containers/policy.json', which is also in package golang-github-containers-common 0.44.4+ds1-1
```

**3 days ago my VM was installing perfectly but I had to delete and recreate it 😞** since then the exact same install batch doesn't work for my exam online.

This is due to (if ever you wanna reproduce)
```
# Install cri-o
sudo apt-get update && sudo apt-get upgrade -y
export OS=xUbuntu_20.04
export VERSION=1.23
echo "deb http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/$VERSION/$OS/ /" | sudo tee -a /etc/apt/sources.list.d/cri-0.list
curl -L http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/$VERSION/$OS/Release.key | sudo apt-key add -
echo "deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/$OS/ /" | sudo tee -a /etc/apt/sources.list.d/libcontainers.list
sudo apt-get update
sudo apt-get install -y cri-o cri-o-runc podman buildah
```

The last command line above will throw you this
```
Errors were encountered while processing:
 /tmp/apt-dpkg-install-HDkSYr/22-containers-common_100%3a1-22_all.deb
needrestart is being skipped since dpkg has failed
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

Need help 😂
