### ISSUE TITLE
Option flags expecting integers eat their neighbouring flags and generate parsing errors

### ISSUE THREAD

**Issue by pixdrift** [containers/buildah#673] opened 2018-05-10 12:54 UTC
**Description**
I found the following when generating test cases for some of the option flags. For the `CommonBuildOptions` flags that are of type `int`, if provided no input they attempt to incorrectly parse the neighbouring flag as the parameter/value. Additionally, if they are provided invalid input (ie. non integer) they provide a parser error.

**Steps to reproduce the issue:**
1. Execute `buildah bud` with any of the `int` type flags (cpu-period cpu-quota, cpu-shares) with no value in isolation (correct error handling).
```
buildah bud --cpu-quota
Incorrect Usage: flag needs an argument: -cpu-quota
```
2. Execute `buildah bud` with the same flag with non-integer input (it fails to parse)
```
buildah bud --cpu-quota donut
Incorrect Usage: invalid value "donut" for flag -cpu-quota: strconv.ParseInt: parsing "donut": invalid syntax
```
3. Execute `buildah bud` with the same flag with non-integer input and a following flag (it's eaten like donut, rather than interpreting as another option and displaying an error that the value is empty)
```
buildah bud --cpu-quota --pull-always
Incorrect Usage: invalid value "--pull-always" for flag -cpu-quota: strconv.ParseInt: parsing "--pull-always": invalid syntax
```

**Describe the results you received:**
Parsing errors, and incorrect interpretation of a following flag as a parameter.

**Describe the results you expected:**
An error stating that the flag cannot be blank, or must be a valid integer.

**Output of `rpm -q buildah` or `apt list buildah`:**

```
buildah-1.0-201805081247.gitfe204e4.el7.x86_64
```

**Output of `buildah version`:**

```
# buildah version
Version:       1.0
Go Version:    go1.8.3
Image Spec:    1.0.0
Runtime Spec:  1.0.0
Git Commit:    fe204e4
Built:         Wed May  9 22:58:38 2018
OS/Arch:       linux/amd64
```

**Output of `cat /etc/*release`:**

```
CentOS Linux release 7.4.1708 (Core)
```

**Comment by TomSweeneyRedHat** [comment] 2018-05-10 13:49
@pixdrift Thanks for the issue.  @umohnani8 do you have time to look at this?  If not let me know and I'll dive in.

**Comment by rhatdan** [comment] 2018-05-10 13:52
I don't see these errors as being all that bad.  @pixdrift What would you want the output to be?

**Comment by umohnani8** [comment] 2018-05-10 14:50
@TomSweeneyRedHat sure I can work on it. But I agree with @rhatdan the errors look fine to me, I guess after the "invalid value..." I can add something like "expecting an integer".

**Comment by pixdrift** [comment] 2018-05-10 21:13
@rhatdan, if the next item starts with '--' (ie. there is no option provided) I would expect it to return the same error.
`Incorrect Usage: flag needs an argument: -cpu-quota`

ie. it should determine that no argument was given, rather than trying to interpret the next flag as an argument.

If the next item is a string rather than an integer, I would expect an error like @umohnani8 has described
`--cpuquota is expecting an integer`

There is also another minor issue here.. you can see the error message has stripped one of the `-` from `--cpu-quota` in the error message. This can be misleading because it makes the user believe they may have supplied an incorrect option.

.. and one last issue.. it appears you can specify '--' options to the command line using a single `-` value, not sure if that is expected behaviour but it also came up when I was writing tests.

**Comment by rhatdan** [comment] 2018-08-02 20:38
@vrothberg Could you look into this one?  Since you are an expert on urfave/CLI now?  :^)

**Comment by vrothberg** [comment] 2018-08-06 07:01
> @vrothberg Could you look into this one? Since you are an expert on urfave/CLI now? :^)

Sure, I'll take a look.

**Comment by vrothberg** [comment] 2018-08-06 07:14
The root of the issue is in go's stdlib in the `flag` package: https://golang.org/src/flag/flag.go?s=8120:8324#L912

I don't think we should patch `urfave/cli`, but rather go for a fix in the `flag` package and see what the go maintainers think about that. However, we are "bug compatible" with Docker:

```
# docker run --cpu-quota abc123 alpine ls
invalid argument "abc123" for --cpu-quota: strconv.ParseInt: parsing "abc123": invalid syntax
```

I suggest to keep the issue open and use that as a reference for a potential PR for `flag`.

**Comment by rhatdan** [comment] 2018-11-27 19:36
@vrothberg can we close this issue?

**Comment by vrothberg** [comment] 2018-11-28 07:59
> @vrothberg can we close this issue?

Yes, we can. Sorry, I forgot closing it. I opened an issue for golang that resulted in [this change](https://go-review.googlesource.com/c/go/+/143257/). This means that the quality of those error messages now depends on the version of go the binaries are compiled with :^)

**Closed by vrothberg** 2018-11-28 07:59 UTC
