### ISSUE TITLE
can we use caches more aggressively for build args?

### ISSUE THREAD

**Issue by dustymabe** [containers/buildah#1931] opened 2019-10-18 22:22 UTC
**Description**
Trying to understand caching behavior with `podman build --build-args`. It seems as if caching is not re-using layers that it could. If a build arg changes we should be able to re-use all cached layers up until the build arg is first used.

```
$ cat Dockerfile 
FROM fedora:30
ARG FIRSTARG
RUN echo ${FIRSTARG} > /root/firstarg
ARG SECONDARG
RUN echo ${SECONDARG} > /root/secondarg

$ sudo podman build -t example --build-arg FIRSTARG=a --build-arg SECONDARG=b . 
STEP 1: FROM fedora:30
STEP 2: ARG FIRSTARG   
e1286bd44fd0f5549c30752ba99122092d7a53e72e944273733749ef7977e83d
STEP 3: RUN echo ${FIRSTARG} > /root/firstarg
695c5a0538beefad1618db6990b5b4ecca21c4df72dbcff2f7b05e8bf862d056
STEP 4: ARG SECONDARG
c39d81c2575561aaef7dd0aa30de216e6a83447e70f6b6db4e74d1d01cc14f0f
STEP 5: RUN echo ${SECONDARG} > /root/secondarg
STEP 6: COMMIT example                                                                                             
ba1baea24a91a1f4725c973bc306f1e5ef10124817b80991637d8f6d900151d7
            
$ sudo podman build -t example --build-arg FIRSTARG=a --build-arg SECONDARG=c .        
STEP 1: FROM fedora:30                            
STEP 2: ARG FIRSTARG
--> Using cache e1286bd44fd0f5549c30752ba99122092d7a53e72e944273733749ef7977e83d
STEP 3: RUN echo ${FIRSTARG} > /root/firstarg
93a41b2904109e12f776c532fd060cb93f48cddd1dacb7d7495bc609a0c1f51b
STEP 4: ARG SECONDARG
221f0e4abd2bc04ac70cd80ec9e2c4fa3bf48afb453dabed3c703d921785ebd6
STEP 5: RUN echo ${SECONDARG} > /root/secondarg
STEP 6: COMMIT example        
73ca1b6f148d226c9cc3febc269dc0c6d86d897c7cf83f9a19751c67c4c21397
```

Why did step3 in the second build not use the cache? This is a simple example, but it's causing me some issues (time and bandwidth wasted) in a more complex case because no caches are used and I keep running the `dnf update -y` steps over and over again.

**Describe the results you received:**

Less caching was used than expected

**Describe the results you expected:**

Caches would be used up until the first use of the changed build arg.

**Output of `rpm -q buildah` or `apt list buildah`:**

```
podman-1.6.1-2.fc31.x86_64
```

**Output of `podman version` if reporting a `podman build` issue:**

<details>

```
[vagrant@vanilla-f31 example]$ sudo podman version
Version:            1.6.1
RemoteAPI Version:  1
Go Version:         go1.13
OS/Arch:            linux/amd64
[vagrant@vanilla-f31 example]$ sudo podman info
host:
  BuildahVersion: 1.11.2
  CgroupVersion: v2
  Conmon:
    package: conmon-2.0.1-1.fc31.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.1, commit: 5e0eadedda9508810235ab878174dca1183f4013'
  Distribution:
    distribution: fedora
    version: "31"
  MemFree: 360198144
  MemTotal: 4126666752
  OCIRuntime:
    package: crun-0.10.2-1.fc31.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 0.10.2
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +YAJL
  SwapFree: 0
  SwapTotal: 0
  arch: amd64
  cpus: 4
  eventlogger: journald
  hostname: vanilla-f31
  kernel: 5.3.6-300.fc31.x86_64
  os: linux
  rootless: false
  uptime: 28h 27m 23.76s (Approximately 1.17 days)
registries:
  blocked: null
  insecure: null
  search:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  ConfigFile: /etc/containers/storage.conf
  ContainerStore:
    number: 24
  GraphDriverName: overlay
  GraphOptions:
    overlay.mountopt: nodev,metacopy=on
  GraphRoot: /var/lib/containers/storage
  GraphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "true"
  ImageStore:
    number: 70
  RunRoot: /var/run/containers/storage
  VolumePath: /var/lib/containers/storage/volumes
```
<\details>

**Output of `uname -a`:**

```
Linux vanilla-f31 5.3.6-300.fc31.x86_64 #1 SMP Mon Oct 14 12:26:42 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by dustymabe** [comment] 2019-10-23 03:09
note that this represents a behavior difference from `docker build` with docker as provided by the `moby-engine-18.09.8-2.ce.git0dd43dd.fc31.x86_64` package:

```
[vagrant@vanilla-f31 foo]$ sudo docker build -t example --build-arg FIRSTARG=a --build-arg SECONDARG=b .
Sending build context to Docker daemon  2.048kB
Step 1/5 : FROM registry.fedoraproject.org/fedora:30
 ---> 071ac0765f8a
Step 2/5 : ARG FIRSTARG
 ---> Running in 6bb8d6a076f0
Removing intermediate container 6bb8d6a076f0
 ---> 5ef0f8be47b8
Step 3/5 : RUN echo ${FIRSTARG} > /root/firstarg
 ---> Running in 67711dfe912b
Removing intermediate container 67711dfe912b
 ---> 994db204483a
Step 4/5 : ARG SECONDARG
 ---> Running in 920e6e856f4e
Removing intermediate container 920e6e856f4e
 ---> e5b9ec302706
Step 5/5 : RUN echo ${SECONDARG} > /root/secondarg
 ---> Running in 243e529ed472
Removing intermediate container 243e529ed472
 ---> 29e3e58a6dfc
Successfully built 29e3e58a6dfc
Successfully tagged example:latest
[vagrant@vanilla-f31 foo]$ 
[vagrant@vanilla-f31 foo]$ sudo docker build -t example --build-arg FIRSTARG=a --build-arg SECONDARG=c .
Sending build context to Docker daemon  2.048kB
Step 1/5 : FROM registry.fedoraproject.org/fedora:30
 ---> 071ac0765f8a
Step 2/5 : ARG FIRSTARG
 ---> Using cache
 ---> 5ef0f8be47b8
Step 3/5 : RUN echo ${FIRSTARG} > /root/firstarg
 ---> Using cache
 ---> 994db204483a
Step 4/5 : ARG SECONDARG
 ---> Using cache
 ---> e5b9ec302706
Step 5/5 : RUN echo ${SECONDARG} > /root/secondarg
 ---> Running in 02639002b8dd
Removing intermediate container 02639002b8dd
 ---> 45134d59e69b
Successfully built 45134d59e69b
Successfully tagged example:latest

```

You can see caches were used all the way up to the changed arg was used.

**Comment by TomSweeneyRedHat** [comment] 2019-10-23 23:55
@dustymabe I was able to replicate what you're seeing, but I went and used `bulidah bud --layers` in place of `podman build`.  Going through the example you provided, I thought buildah not using the cache for the second run with the second argument made sense as the value passed into it had changed from 'b' to 'c'.  However, you're right, that's not what Docker does.  I'm just not 100% sure which is the correct behavior.  My thinking is the build shouldn't reuse the cache if the value of the variable changed, but Docker doesn't appear to do that.   If the value for the variable doesn't change, then we do reuse the cache.

@nalind or @rhatdan, WDYT?  Should we reuse the cache even if the value of the variable changes?

**Comment by rhatdan** [comment] 2019-10-24 12:58
@TomSweeneyRedHat Are you in the office, I would like you to show me exactly what is going ont.

**Comment by dustymabe** [comment] 2019-10-24 13:31
In my example only the 2nd argument (`SECONDARG`) changed and thus all layers before the use of the argument that changed should be re-used.

IOW from the example:

```
FROM fedora:30
ARG FIRSTARG
RUN echo ${FIRSTARG} > /root/firstarg
ARG SECONDARG
RUN echo ${SECONDARG} > /root/secondarg
```

we should be able to re-use all layers until the very last step (which is the first place where anything has changed).

All that is to say that I believe docker is behaving appropriately here and we can improve podman to be smarter about caching (and save people time/bandwidth).

**Comment by rhatdan** [comment] 2019-10-24 13:41
It looks like the code is working correct at least with this example:
```
First time, no cache
$ podman build -t example --build-arg FIRSTARG=a --build-arg SECONDARG=c . 
STEP 1: FROM fedora:30
STEP 2: ARG FIRSTARG
550907951cf0f4a3b78f9c9c0015882abf0650172853f6c7a79a4ca07e41162f
STEP 3: RUN echo ${FIRSTARG} > /root/firstarg
358443acb894c7494b60d6651db602ddebf271e3020ac300acc7dca7c8887f92
STEP 4: ARG SECONDARG
5546d22149103d33e40e30c06a2054dd09b24c180d7f842f40494a51687dccac
STEP 5: RUN echo ${SECONDARG} > /root/secondarg
STEP 6: COMMIT example
f545345f5175c21fa24288e7910c57a0f40534174925734b88965feee048cd16
```
```
Second time with exact same args, everything cached
$ podman build -t example --build-arg FIRSTARG=a --build-arg SECONDARG=c . 
STEP 1: FROM fedora:30
STEP 2: ARG FIRSTARG
--> Using cache 550907951cf0f4a3b78f9c9c0015882abf0650172853f6c7a79a4ca07e41162f
STEP 3: RUN echo ${FIRSTARG} > /root/firstarg
--> Using cache 358443acb894c7494b60d6651db602ddebf271e3020ac300acc7dca7c8887f92
STEP 4: ARG SECONDARG
--> Using cache 5546d22149103d33e40e30c06a2054dd09b24c180d7f842f40494a51687dccac
STEP 5: RUN echo ${SECONDARG} > /root/secondarg
--> Using cache f545345f5175c21fa24288e7910c57a0f40534174925734b88965feee048cd16
STEP 6: COMMIT example
f545345f5175c21fa24288e7910c57a0f40534174925734b88965feee048cd16
```
```
Third time with secondarg changed uses case up to use of SECCONDARG
$ podman build -t example --build-arg FIRSTARG=a --build-arg SECONDARG=d . 
STEP 1: FROM fedora:30
STEP 2: ARG FIRSTARG
--> Using cache 550907951cf0f4a3b78f9c9c0015882abf0650172853f6c7a79a4ca07e41162f
STEP 3: RUN echo ${FIRSTARG} > /root/firstarg
df1ae576f6d8eece537e26357fdbdcfd04dde5380c5cbc049815bf3e27d95251
STEP 4: ARG SECONDARG
6d7548b501b2da83d2fa4f25a6507afe39833019d019e57485825d1a0b19ade3
STEP 5: RUN echo ${SECONDARG} > /root/secondarg
STEP 6: COMMIT example
18a0c2a12bc01f8aeb4ecacf2ce3c56384268417a6c7354866c60ec25e469204
```

What am I missing?

**Comment by rhatdan** [comment] 2019-10-24 13:42
I think the problem is Step 3 should have been cached?

**Comment by dustymabe** [comment] 2019-10-24 13:45
> I think the problem is Step 3 should have been cached?

step 3 and step 4, according to the docker behavior

**Comment by dustymabe** [comment] 2019-10-24 13:47
of course this is a simple example, consider if the example is changed to:

```
FROM fedora:30
ARG FIRSTARG
RUN echo ${FIRSTARG} > /root/firstarg
RUN dnf update -y && dnf install -y ${FIRSTARG}
ARG SECONDARG
RUN echo ${SECONDARG} > /root/secondarg
```

Now we have a much bigger penalty for not using caching.

**Comment by rhatdan** [comment] 2019-10-24 13:50
I agree on step 3, and maybe on step 4 since the text did not change.  But step 5 obviously is different.

@TomSweeneyRedHat I think Step 5 should be the only non cached item.

**Comment by carbonin** [comment] 2020-03-27 19:36
@dustymabe I think this is fixed as of https://github.com/containers/buildah/pull/2220
This is what I get with your original Dockerfile with the latest `buildah` source:
```
$ cat Dockerfile 
FROM fedora:30
ARG FIRSTARG
RUN echo ${FIRSTARG}
ARG SECONDARG
RUN echo ${SECONDARG}

$ ../buildah bud --layers --build-arg FIRSTARG=a --build-arg SECONDARG=b
STEP 1: FROM fedora:30
STEP 2: ARG FIRSTARG
--> 25c0f2e465c
STEP 3: RUN echo ${FIRSTARG}
a
--> 83dae840cf5
STEP 4: ARG SECONDARG
--> 2458a13f861
STEP 5: RUN echo ${SECONDARG}
b
STEP 6: COMMIT
--> a8b2a0216ae
a8b2a0216ae28675e0f30b70154683848d8bc0e819f69d3efe7f26b7f2999cca

$ ../buildah bud --layers --build-arg FIRSTARG=a --build-arg SECONDARG=c
STEP 1: FROM fedora:30
STEP 2: ARG FIRSTARG
--> Using cache 25c0f2e465cb584ecbbe0401af0f90965fb0cd091094673c1e610465d92975f4
STEP 3: RUN echo ${FIRSTARG}
--> Using cache 83dae840cf53e0b9c288673d52bbc20d7116a2cada17f490fd332d81c261ccaa
STEP 4: ARG SECONDARG
--> Using cache 2458a13f8611568ea809fbcd1b690f22035f520a0321c34a7f96471584f26fbc
STEP 5: RUN echo ${SECONDARG}
c
STEP 6: COMMIT
--> 276b343f95c
276b343f95c686307830ed0a93704273462ac14748822bf4817cc4361ac9acaa
```

Specifically I think it's because of [this removal](https://github.com/containers/buildah/pull/2220/files#diff-2042b92e72d852f6e42ca15082b4d4daL1975-L1978) which used to record all the build args passed on the command line before any layer was run. I think this would have caused a cache miss even if we didn't hit the corresponding `ARG` command yet.

**Closed** 2020-03-27 19:45 UTC
