### ISSUE TITLE
podman build cannot mount devices, while podman run can.

### ISSUE THREAD

**Issue by hjmodi** [containers/buildah#4002] opened 2022-05-17 19:57 UTC
**Description**
Cannot attach devices with `podman build --device /dev/null:/var/tmp/flatpak-build/dev/null --no-cache .` . Getting error, `Error: error creating build executor: Renaming device /dev/null to /var/tmp/flatpak-build/dev/null is not supported in rootless containers` . However the same works with `podman run --device /dev/null:/var/tmp/flatpak-build/dev/null -ti --rm ubi8` giving the following result,

```
Resolved "ubi8" as an alias (/etc/containers/registries.conf.d/000-shortnames.conf)
Trying to pull registry.access.redhat.com/ubi8:latest...
Getting image source signatures
Checking if image destination supports signatures
Copying blob f70d60810c69 done  
Copying blob 545277d80005 done  
Copying config 1264065f6a done  
Writing manifest to image destination
Storing signatures
[root@f0398eb06c06 /]# ls /var/tmp/flatpak-build/dev/
null
[root@f0398eb06c06 /]# exit
```

**Steps to reproduce the issue:**
1. Run podman build and try to mount a device. i.e. `--device /dev/null:/var/tmp/flatpak-build/dev/null`
2.
3.

**Describe the results you received:**
Failed with `Error: error creating build executor: Renaming device /dev/null to /var/tmp/flatpak-build/dev/null is not supported in rootless containers`

**Describe the results you expected:**
To be able to mount device to a given location.

**Output of `rpm -q buildah` or `apt list buildah`:**

```
package buildah is not installed
```

**Output of `buildah version`:**

```
bash: buildah: command not found...
Install package 'buildah' to provide command 'buildah'? [N/y] n
```

**Output of `podman version` if reporting a `podman build` issue:**

```
Client:       Podman Engine
Version:      4.1.0
API Version:  4.1.0
Go Version:   go1.18
Built:        Fri May  6 12:15:54 2022
OS/Arch:      linux/amd64
```

**Output of `cat /etc/*release`:**

```
Fedora release 36 (Thirty Six)
NAME="Fedora Linux"
VERSION="36 (Workstation Edition)"
ID=fedora
VERSION_ID=36
VERSION_CODENAME=""
PLATFORM_ID="platform:f36"
PRETTY_NAME="Fedora Linux 36 (Workstation Edition)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:36"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f36/system-administrators-guide/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=36
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=36
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Workstation Edition"
VARIANT_ID=workstation
Fedora release 36 (Thirty Six)
Fedora release 36 (Thirty Six)
```

**Output of `uname -a`:**

```
Linux hmodi.users.ipa.redhat.com 5.17.6-300.fc36.x86_64 #1 SMP PREEMPT Mon May 9 15:47:11 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

**Output of `cat /etc/containers/storage.conf`:**

```
# This file is is the configuration file for all tools
# that use the containers/storage library. The storage.conf file
# overrides all other storage.conf files. Container engines using the
# container/storage library do not inherit fields from other storage.conf
# files.
#
#  Note: The storage.conf file overrides other storage.conf files based on this precedence:
#      /usr/containers/storage.conf
#      /etc/containers/storage.conf
#      $HOME/.config/containers/storage.conf
#      $XDG_CONFIG_HOME/containers/storage.conf (If XDG_CONFIG_HOME is set)
# See man 5 containers-storage.conf for more information
# The "container storage" table contains all of the server options.
[storage]

# Default Storage Driver, Must be set for proper operation.
driver = "overlay"

# Temporary storage location
runroot = "/run/containers/storage"

# Primary Read/Write location of container storage
# When changing the graphroot location on an SELINUX system, you must
# ensure  the labeling matches the default locations labels with the
# following commands:
# semanage fcontext -a -e /var/lib/containers/storage /NEWSTORAGEPATH
# restorecon -R -v /NEWSTORAGEPATH
graphroot = "/var/lib/containers/storage"


# Storage path for rootless users
#
# rootless_storage_path = "$HOME/.local/share/containers/storage"

[storage.options]
# Storage options to be passed to underlying storage drivers

# AdditionalImageStores is used to pass paths to additional Read/Only image stores
# Must be comma separated list.
additionalimagestores = [
]

# Remap-UIDs/GIDs is the mapping from UIDs/GIDs as they should appear inside of
# a container, to the UIDs/GIDs as they should appear outside of the container,
# and the length of the range of UIDs/GIDs.  Additional mapped sets can be
# listed and will be heeded by libraries, but there are limits to the number of
# mappings which the kernel will allow when you later attempt to run a
# container.
#
# remap-uids = 0:1668442479:65536
# remap-gids = 0:1668442479:65536

# Remap-User/Group is a user name which can be used to look up one or more UID/GID
# ranges in the /etc/subuid or /etc/subgid file.  Mappings are set up starting
# with an in-container ID of 0 and then a host-level ID taken from the lowest
# range that matches the specified name, and using the length of that range.
# Additional ranges are then assigned, using the ranges which specify the
# lowest host-level IDs first, to the lowest not-yet-mapped in-container ID,
# until all of the entries have been used for maps.
#
# remap-user = "containers"
# remap-group = "containers"

# Root-auto-userns-user is a user name which can be used to look up one or more UID/GID
# ranges in the /etc/subuid and /etc/subgid file.  These ranges will be partitioned
# to containers configured to create automatically a user namespace.  Containers
# configured to automatically create a user namespace can still overlap with containers
# having an explicit mapping set.
# This setting is ignored when running as rootless.
# root-auto-userns-user = "storage"
#
# Auto-userns-min-size is the minimum size for a user namespace created automatically.
# auto-userns-min-size=1024
#
# Auto-userns-max-size is the minimum size for a user namespace created automatically.
# auto-userns-max-size=65536

[storage.options.overlay]
# ignore_chown_errors can be set to allow a non privileged user running with
# a single UID within a user namespace to run containers. The user can pull
# and use any image even those with multiple uids.  Note multiple UIDs will be
# squashed down to the default uid in the container.  These images will have no
# separation between the users in the container. Only supported for the overlay
# and vfs drivers.
#ignore_chown_errors = "false"

# Inodes is used to set a maximum inodes of the container image.
# inodes = ""

# Path to an helper program to use for mounting the file system instead of mounting it
# directly.
#mount_program = "/usr/bin/fuse-overlayfs"

# mountopt specifies comma separated list of extra mount options
mountopt = "nodev,metacopy=on"

# Set to skip a PRIVATE bind mount on the storage home directory.
# skip_mount_home = "false"

# Size is used to set a maximum size of the container image.
# size = ""

# ForceMask specifies the permissions mask that is used for new files and
# directories.
#
# The values "shared" and "private" are accepted.
# Octal permission masks are also accepted.
#
#  "": No value specified.
#     All files/directories, get set with the permissions identified within the
#     image.
#  "private": it is equivalent to 0700.
#     All files/directories get set with 0700 permissions.  The owner has rwx
#     access to the files. No other users on the system can access the files.
#     This setting could be used with networked based homedirs.
#  "shared": it is equivalent to 0755.
#     The owner has rwx access to the files and everyone else can read, access
#     and execute them. This setting is useful for sharing containers storage
#     with other users.  For instance have a storage owned by root but shared
#     to rootless users as an additional store.
#     NOTE:  All files within the image are made readable and executable by any
#     user on the system. Even /etc/shadow within your image is now readable by
#     any user.
#
#   OCTAL: Users can experiment with other OCTAL Permissions.
#
#  Note: The force_mask Flag is an experimental feature, it could change in the
#  future.  When "force_mask" is set the original permission mask is stored in
#  the "user.containers.override_stat" xattr and the "mount_program" option must
#  be specified. Mount programs like "/usr/bin/fuse-overlayfs" present the
#  extended attribute permissions to processes within containers rather then the
#  "force_mask"  permissions.
#
# force_mask = ""

[storage.options.thinpool]
# Storage Options for thinpool

# autoextend_percent determines the amount by which pool needs to be
# grown. This is specified in terms of % of pool size. So a value of 20 means
# that when threshold is hit, pool will be grown by 20% of existing
# pool size.
# autoextend_percent = "20"

# autoextend_threshold determines the pool extension threshold in terms
# of percentage of pool size. For example, if threshold is 60, that means when
# pool is 60% full, threshold has been hit.
# autoextend_threshold = "80"

# basesize specifies the size to use when creating the base device, which
# limits the size of images and containers.
# basesize = "10G"

# blocksize specifies a custom blocksize to use for the thin pool.
# blocksize="64k"

# directlvm_device specifies a custom block storage device to use for the
# thin pool. Required if you setup devicemapper.
# directlvm_device = ""

# directlvm_device_force wipes device even if device already has a filesystem.
# directlvm_device_force = "True"

# fs specifies the filesystem type to use for the base device.
# fs="xfs"

# log_level sets the log level of devicemapper.
# 0: LogLevelSuppress 0 (Default)
# 2: LogLevelFatal
# 3: LogLevelErr
# 4: LogLevelWarn
# 5: LogLevelNotice
# 6: LogLevelInfo
# 7: LogLevelDebug
# log_level = "7"

# min_free_space specifies the min free space percent in a thin pool require for
# new device creation to succeed. Valid values are from 0% - 99%.
# Value 0% disables
# min_free_space = "10%"

# mkfsarg specifies extra mkfs arguments to be used when creating the base
# device.
# mkfsarg = ""

# metadata_size is used to set the `pvcreate --metadatasize` options when
# creating thin devices. Default is 128k
# metadata_size = ""

# Size is used to set a maximum size of the container image.
# size = ""

# use_deferred_removal marks devicemapper block device for deferred removal.
# If the thinpool is in use when the driver attempts to remove it, the driver
# tells the kernel to remove it as soon as possible. Note this does not free
# up the disk space, use deferred deletion to fully remove the thinpool.
# use_deferred_removal = "True"

# use_deferred_deletion marks thinpool device for deferred deletion.
# If the device is busy when the driver attempts to delete it, the driver
# will attempt to delete device every 30 seconds until successful.
# If the program using the driver exits, the driver will continue attempting
# to cleanup the next time the driver is used. Deferred deletion permanently
# deletes the device and all data stored in device will be lost.
# use_deferred_deletion = "True"

# xfs_nospace_max_retries specifies the maximum number of retries XFS should
# attempt to complete IO when ENOSPC (no space) error is returned by
# underlying storage device.
# xfs_nospace_max_retries = "0"
```

**Comment by hjmodi** [comment] 2022-05-17 19:59
Couldn't find `buildah` on my system but in podman issue tracker they've asked to file `podman build` issues here, so I'm reporting here.

**Comment by rhatdan** [comment] 2022-05-17 20:55
@flouthoc PTAL.

**Comment by flouthoc** [comment] 2022-05-18 08:22
Hi @hjmodi , I think `podman run` is not doing the correct behavior  here instead of populating https://github.com/opencontainers/runtime-spec/blob/main/config-linux.md#devices it is creating a bind mount which is not equivalent to creating a device. Also I think as mentioned in other issues like https://github.com/opencontainers/runtime-spec/issues/980 some devices don't expect bind mount at all so `podman run --device` might be producing faulty behavior for those devices.

I think creating/renaming a device is not supported in rootless mode since it needs `mknod` and afaik containers in user namespace are not allowed to do `mknod` however if there is no rename it should still work via falling back to bind mount.

If you still want to re-name this device i would suggest doing explicit bind mount  like

```console 
podman build -v /dev/null:/var/tmp/flatpak-build/dev/null --no-cache .
```

I am closing this issue since I think above workaround is right fix for this build issue but please feel-free to comment below or re-open this issue.

**Comment by owtaylor** [comment] 2022-05-18 16:59
The workaround seems to work for me - thanks! - but I don't really agree with the conclusion here:

* The problems mentioned in the runtime-spec issue only affect a few edge cases.
* In the end, the oci-spec *allows* using a bind mount - while that issue complains about that, the spec wording wasn't changed, and stands.
*  For rootless operation, the bind mount is how the standard set of devices in /dev is populated. Shouldn't the user be able to extend that to more devices / devices in other locations? I don't think forbidding it because some edge case (linking in /dev/pts entries, say) fails - if it doesn't work, the user isn't worse off.
*  It's quite confusing if the --device= option works as a bind mount for rootless 'podman run', but rootless buildah/'podman build' refuses to allow it. It can't be correct for one, and not for the other.

**Comment by rhatdan** [comment] 2022-05-18 17:51
I agree with Owen, lets fix this.

**Comment by flouthoc** [comment] 2022-05-18 19:17
@owtaylor Ah i see your argument makes sense to me. 

Although I still think that `podman run --devices` is doing the unexpected magic by taking charge away from `oci-runtime` and creating `bind mounts` explicitly instead of giving `devices` to runtime ( since runtime already handles devices ) but I guess since it confusing for end users so maybe we can add a similar exception to `buildah build` cause fixing `podman run` could break existing users.

Tagging @nalind @giuseppe just for info.

**Comment by hjmodi** [comment] 2022-05-19 13:17
@flouthoc If you agree, can we please reopen this and add it into a bucket or milestone?

**Comment by flouthoc** [comment] 2022-05-24 10:27
@hjmodi Above PR should close this.

**Closed** 2022-05-25 10:21 UTC

**Comment by hjmodi** [comment] 2022-06-01 22:12
Thanks for the quick fix. When will this be released?

**Comment by flouthoc** [comment] 2022-06-02 04:57
@hjmodi I am not sure about the time frame for next release but from previous discussion it seems like near August/July. cc @TomSweeneyRedHat @rhatdan @nalind

**Comment by rhatdan** [comment] 2022-06-02 18:10
podman 4.2 release candidates start first week in July and complete by August 1st.

**Comment by flouthoc** [comment] 2022-06-03 08:04
@hjmodi Would it be possible to use buildah directly and build it from source ? Since I'm unsure if release will prepone because of this but @rhatdan and @TomSweeneyRedHat could confirm this better.

**Comment by hjmodi** [comment] 2022-06-03 12:32
@rhatdan we need it for the OSBS 2.0(https://github.com/containerbuildsystem/atomic-reactor). We're using `podman-remote` to build images on builders with different arches. I don't think we'll be able to use the unreleased version since many other teams will depend on it.

**Comment by hjmodi** [comment] 2022-06-03 13:34
It's more of regression from my side because we did expect the `--device` option to work with `podman build` just as it worked with `podman run` and the same for `--volume` option, it works with `podman build` and `podman-remote run` I don't see why it doesn't work with `podman-remote build`. Furthermore, when I tried doing `podman-remote build --volume` it didn't throw any warning/error, so I'm not sure why is that the case as well.

**Comment by hjmodi** [comment] 2022-06-03 13:55
I guess I should file another issue for the `--volume` option not working with `podman-remote build`.

**Comment by rhatdan** [comment] 2022-06-03 14:55
Sure that is a bug, but not a regression.  Regression meant it worked at one point in a released version and now it does not. I am afraid you will have to wait. You could always ask for support via a bugzilla.

**Comment by hjmodi** [comment] 2022-06-03 16:09
@flouthoc just to be sure before opening a bugzilla #4014 will fix the issue for `podman-remote build` also correct?
