### ISSUE TITLE
Default of ARG ignored on second build

### ISSUE THREAD

**Issue by dulek** [containers/buildah#1206] opened 2018-11-28 17:10 UTC
**Description**

On second build from a given layer buildah is ignoring the default value of ARG

**Steps to reproduce the issue:**
1. Create 2 Dockerfiles:
```
FROM fedora:29
ARG FOO=bar
RUN echo foo:$FOO
```

and 
```
FROM fedora:29
ARG FOO=bar
RUN echo foobar:$FOO
```
2. Try to build first one and the second one.
3. Notice that for second the echo statement doesn't print default value of $FOO.

**Describe the results you received:**
```
stack@ubuntu:~$ sudo podman build -f 1.Dockerfile                                                                                                                                              
STEP 1: FROM fedora:29                                                                                                                                                                         
STEP 2: ARG FOO=bar                                                                                                                                                                            
--> 82973451a048dab792d566e86bc063fff3edf64e3de2e317aa0ae60d4925a260                                                                                                                           
STEP 3: FROM 82973451a048dab792d566e86bc063fff3edf64e3de2e317aa0ae60d4925a260
STEP 4: RUN echo foo:$FOO
foo:bar
--> 8eca5560ed3cc23704ab5744fae04ba785b71c3e6b5915afc9edab9c53644ccf
STEP 5: COMMIT
stack@ubuntu:~$ sudo podman build -f 2.Dockerfile
STEP 1: FROM fedora:29
STEP 2: ARG FOO=bar
--> Using cache 82973451a048dab792d566e86bc063fff3edf64e3de2e317aa0ae60d4925a260
STEP 3: FROM 82973451a048dab792d566e86bc063fff3edf64e3de2e317aa0ae60d4925a260
STEP 4: RUN echo foobar:$FOO
foobar:
--> 52fceb750d990a908a96b0c8fadb651c8f4304e06d1b073e7f7ee5e93c13f93c
STEP 5: COMMIT
```

**Describe the results you expected:**
```
stack@ubuntu:~$ sudo podman build -f 1.Dockerfile                                                                                                                                              
STEP 1: FROM fedora:29                                                                                                                                                                         
STEP 2: ARG FOO=bar                                                                                                                                                                            
--> 82973451a048dab792d566e86bc063fff3edf64e3de2e317aa0ae60d4925a260                                                                                                                           
STEP 3: FROM 82973451a048dab792d566e86bc063fff3edf64e3de2e317aa0ae60d4925a260
STEP 4: RUN echo foo:$FOO
foo:bar
--> 8eca5560ed3cc23704ab5744fae04ba785b71c3e6b5915afc9edab9c53644ccf
STEP 5: COMMIT
stack@ubuntu:~$ sudo podman build -f 2.Dockerfile
STEP 1: FROM fedora:29
STEP 2: ARG FOO=bar
--> Using cache 82973451a048dab792d566e86bc063fff3edf64e3de2e317aa0ae60d4925a260
STEP 3: FROM 82973451a048dab792d566e86bc063fff3edf64e3de2e317aa0ae60d4925a260
STEP 4: RUN echo foobar:$FOO
foobar:bar
--> 52fceb750d990a908a96b0c8fadb651c8f4304e06d1b073e7f7ee5e93c13f93c
STEP 5: COMMIT
```

**Output of `rpm -q buildah` or `apt list buildah`:**

```
buildah/bionic,now 1.5-1~dev~ubuntu18.04~ppa8 amd64 [installed,automatic]
```

**Output of `buildah version`:**

```
Version:         1.5-dev
Go Version:      go1.10.4
Image Spec:      1.0.0
Runtime Spec:    1.0.0
CNI Spec:        0.4.0
libcni Version:  
Git Commit:      
Built:           Mon Nov 19 22:00:09 2018
OS/Arch:         linux/amd64
```

**Output of `podman version` if reporting a `podman build` issue:**

```
Version:       0.11.2-dev
Go Version:    go1.10.4
OS/Arch:       linux/amd64
```

**Output of `cat /etc/*release`:**

```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.1 LTS"
NAME="Ubuntu"
VERSION="18.04.1 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.1 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

**Output of `uname -a`:**

```
Linux ubuntu 4.15.0-39-generic #42-Ubuntu SMP Tue Oct 23 15:48:01 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Output of `cat /etc/containers/storage.conf`:**

```
# storage.conf is the configuration file for all tools
# that share the containers/storage libraries
# See man 5 containers-storage.conf for more information

# The "container storage" table contains all of the server options.
[storage]

# Default Storage Driver
driver = "overlay"

# Temporary storage location
runroot = "/var/run/containers/storage"

# Primary read-write location of container storage
graphroot = "/var/lib/containers/storage"

[storage.options]
# AdditionalImageStores is used to pass paths to additional read-only image stores
# Must be comma separated list.
additionalimagestores = [
]

# Size is used to set a maximum size of the container image.  Only supported by
# certain container storage drivers (currently overlay, zfs, vfs, btrfs)
size = ""

# OverrideKernelCheck tells the driver to ignore kernel checks based on kernel version
override_kernel_check = "true"
```

**Comment by TomSweeneyRedHat** [comment] 2018-11-28 17:19
Thanks for the issue @dulek.  This smells like a layering issue to me.  @umohnani8 do you have time take a peak?

**Comment by dulek** [comment] 2018-11-28 17:22
Quick follow up, because (as always) I've got an idea immediately after submitting.

This only happens with `podman build`, I see that using `buildah bud` works as expected.

**Comment by dulek** [comment] 2018-11-28 17:33
@TomSweeneyRedHat: I've installed buildah as podman's dependency, so version should be the same in both cases.

```
stack@ubuntu:~$ apt depends podman
podman
  Depends: libseccomp2
  Depends: libdevmapper1.02.1
  Depends: libgpgme11
  Depends: buildah
  Depends: containernetworking-plugins (>= 0.7.3)
  Depends: cri-o-runc
  Depends: cri-o-1.12
  Depends: containers-common
```

**Comment by mheon** [comment] 2018-11-28 17:59
Hm. That seems like an outdated package - we no longer hard-depend on Buildah, and instead vendor a version of the code.

@TomSweeneyRedHat could it be something in Podman's `cmd/podman/build.go`? We don't vendor that from Buildah, so it might have become out of sync?

**Comment by mheon** [comment] 2018-11-28 18:00
@lsm5 Can you check the PPA to see if Podman still depends on Buildah there? If so, we can drop the dependency

**Comment by lsm5** [comment] 2018-11-28 18:11
On Wed, Nov 28, 2018 at 10:00:40AM -0800, Matthew Heon wrote:
> @lsm5 Can you check the PPA to see if Podman still depends on Buildah there? If so, we can drop the dependency

ack, pushed that change to my fork, new builds should be up in sometime.

> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/containers/buildah/issues/1206#issuecomment-442544883

-- 
Lokesh
IRC, GitHub: lsm5
GPG: 0xC7C3A0DD
https://keybase.io/lsm5

**Comment by TomSweeneyRedHat** [comment] 2018-11-28 18:33
@mheon the cmd/podman/build.go doesn't do much with the Dockerfile(s) other than to grab them and pass them along to Buildah, so I can't imagine it's a problem there, but maybe?  I think I'll wait and see how things shake out with the PPA changes where I think the problem is more likely and then will dive in more deeply if that doesn't cure it.

Thanks gents for the help/thoughts here.

**Comment by dulek** [comment] 2018-11-28 19:15
Okay, so it's possible that my podman installation is vendoring an older version of buildah, that still has this issue. At the moment I'm working this around just by using buildah directly. Just for context - I'm trying to set up OpenStack's kuryr-kubernetes CI that will build it's containers using buildah and test them against K8s configured with cri-o.

@lsm5, if you ping me once the packages are up, I'll be happy to retest this.

**Comment by rhatdan** [comment] 2019-03-08 13:48
I believe this is fixed, Closing.  Reopen if you still have the issue.

**Comment by dulek** [comment] 2019-03-26 17:18
@rhatdan: Hey, can we reopen this? Looks like I still experience this with those versions (latest from Ubuntu PPA):

```
stack@ubuntu:~$ buildah version
Version:         1.8-dev
Go Version:      go1.10.4
Image Spec:      1.0.0
Runtime Spec:    1.0.0
CNI Spec:        0.4.0
libcni Version:
Git Commit:
Built:           Sun Mar 24 23:03:14 2019
OS/Arch:         linux/amd64
stack@ubuntu:~$ podman version
Version:            1.2.0-dev
RemoteAPI Version:  1
Go Version:         go1.10.4
OS/Arch:            linux/amd64
```

I haven't complained for a while, as we were using `buildah bud` as a workaround. Unfortunately that stopped working due to #1447, so we're back to square one now.

**Comment by TomSweeneyRedHat** [comment] 2019-03-26 18:40
@dulek it's always OK to reopen an issue if warranted.

**Comment by jcantrill** [comment] 2019-03-27 14:08
I am seeing the same issue in a single stage `podman build` where we have an install file that does evaluates the build arg as as empty:
```
STEP 38: ARG OSE_ES_URL=https://github.com/jcantrill/openshift-elasticsearch-plugin/releases/download/6.6.2.1-SNAPSHOT/openshift-elasticsearch-plugin-6.6.2.1-SNAPSHOT.zip
--> Using cache 25a92539e000131a6cc062bf8a7f9e7a4d1cc2b3f6a7e53c0ebda07394d1db0b
STEP 39: FROM 25a92539e000131a6cc062bf8a7f9e7a4d1cc2b3f6a7e53c0ebda07394d1db0b
STEP 40: ARG PROMETHEUS_EXPORTER_URL=https://github.com/vvanholl/elasticsearch-prometheus-exporter/releases/download/${PROMETHEUS_EXPORTER_VER}/elasticsearch-prometheus-exporter-${PROMETHEUS_EXPORTER_VER}.zip
--> Using cache 86d35cc916ff34d15bb12a7dc59c82d0d9a61b0f8c55b1a4449c7deb37b18526
STEP 41: FROM 86d35cc916ff34d15bb12a7dc59c82d0d9a61b0f8c55b1a4449c7deb37b18526
STEP 42: ARG SG_URL
--> Using cache 493f9e69c12b422d1e76e0fadde4f35c22deba336447f9cfe0fc3bf171045c07
STEP 43: FROM 493f9e69c12b422d1e76e0fadde4f35c22deba336447f9cfe0fc3bf171045c07
STEP 44: RUN ln -s /usr/local/bin/logging ${HOME}/logging &&     ${HOME}/install.sh &&     rm -rf /tmp/lib
+ set -o nounset
+ source /opt/app-root/src/prep-install.origin
++ '[' -z '' ']'
++ OSE_ES_URL=https://github.com/fabric8io/openshift-elasticsearch-plugin/releases/download/openshift-elasticsearch-plugin-6.6.2.1/openshift-elasticsearch-plugin-6.6.2.1.zip
++ '[' -z '' ']'

```
Note `OSE_ES_URL` has a value and subsequently uses the default from our script instead of the value defined in the Dockerfile `OSE_ES_URL=https://github.com/fabric8io/openshift-elasticsearch-plugin/releases/download/openshift-elasticsearch-plugin-6.6.2.1/openshift-elasticsearch-plugin-6.6.2.1.zip`

**Comment by rhatdan** [comment] 2019-03-29 12:23
@dulek Is this because the fixed buildah has not been vendored into podman yet?

**Comment by rhatdan** [comment] 2019-06-08 18:16
I believe this is fixed in releases now.

**Closed by rhatdan** 2019-06-08 18:16 UTC
