### ISSUE TITLE
rootless podman build: issue copying in symlinks twice

### ISSUE THREAD

**Issue by dustymabe** [containers/buildah#1160] opened 2018-11-06 15:31 UTC
### Version info:

Fedora 29 Atomic Host with rootless podman on overlay storage with selinux in permissive mode

<details>

```
[vagrant@vanilla-f29-atomic container]$ rpm-ostree status
State: idle
Warning: failed to query journal: address not available
AutomaticUpdates: disabled
Deployments:
● ostree://fedora-atomic:fedora/29/x86_64/testing/atomic-host
                   Version: 29.20181105.0 (2018-11-05T02:49:51Z)
                BaseCommit: 7c4e99977aabfe6464df95c9b7dfec85420e1c7c29ac8b76d219ee4756146cce
              GPGSignature: Valid signature by 5A03B4DD8254ECA02FDA1637A20AA56B429476B4
           LayeredPackages: fuse-sshfs

  ostree://fedora-atomic:fedora/29/x86_64/atomic-host
                   Version: 29.20181025.1 (2018-10-25T14:46:54Z)
                BaseCommit: 4a999b4b303b47468ff1464051a14fd075d2e7b8bb647584b7cc80fed48cf27b
              GPGSignature: Valid signature by 5A03B4DD8254ECA02FDA1637A20AA56B429476B4
           LayeredPackages: fuse-sshfs
[vagrant@vanilla-f29-atomic container]$
[vagrant@vanilla-f29-atomic container]$ rpm -q podman kernel
podman-0.10.1.3-4.gitdb08685.fc29.x86_64
kernel-4.18.16-300.fc29.x86_64
[vagrant@vanilla-f29-atomic container]$ podman info
host:
  BuildahVersion: 1.5-dev
  Conmon:
    package: podman-0.10.1.3-4.gitdb08685.fc29.x86_64
    path: /usr/libexec/podman/conmon
    version: 'conmon version 1.12.0-dev, commit: 1f741a8b8381375b068b147605704a02a91167a2-dirty'
  Distribution:
    distribution: fedora
    version: "29"
  MemFree: 1208758272
  MemTotal: 4134961152
  OCIRuntime:
    package: runc-1.0.0-57.dev.git9e5aa74.fc29.x86_64
    path: /usr/bin/runc
    version: |-
      runc version 1.0.0-rc5+dev
      commit: ff195010cbfd3c62a98a3fd2f7a1e1594afdda1a
      spec: 1.0.1-dev
  SwapFree: 0
  SwapTotal: 0
  arch: amd64
  cpus: 4
  hostname: vanilla-f29-atomic
  kernel: 4.18.16-300.fc29.x86_64
  os: linux
  uptime: 11h 45m 39.78s (Approximately 0.46 days)
insecure registries:
  registries: []
registries:
  registries:
  - docker.io
  - registry.fedoraproject.org
  - quay.io
  - registry.access.redhat.com
  - registry.centos.org
store:
  ContainerStore:
    number: 6
  GraphDriverName: overlay
  GraphOptions:
  - overlay.mount_program=/usr/bin/fuse-overlayfs
  GraphRoot: /var/home/vagrant/.local/share/containers/storage
  GraphStatus:
    Backing Filesystem: xfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
  ImageStore:
    number: 10
  RunRoot: /run/user/1000/run
```

</details>

### Description:

I have a Dockerfile where I want to copy in  a few of the tiles in the current working directory, perform some operations, and then copy in the rest of the the contents of the current working directory. This gives me an error with rootless podman build:

```
[vagrant@vanilla-f29-atomic container]$ ls -l ./
total 12
-rw-rw-r--. 1 vagrant vagrant 84 Nov  6 15:17 Dockerfile
-rw-rw-r--. 1 vagrant vagrant  4 Nov  6 14:16 file1.txt
-rw-rw-r--. 1 vagrant vagrant  4 Nov  6 14:16 file2.txt
lrwxrwxrwx. 1 vagrant vagrant  9 Nov  6 15:17 file3.txt -> file1.txt
[vagrant@vanilla-f29-atomic container]$
[vagrant@vanilla-f29-atomic container]$ cat Dockerfile
FROM registry.fedoraproject.org/fedora:28
COPY ./file1.txt ./file3.txt /
COPY ./ /
[vagrant@vanilla-f29-atomic container]$
[vagrant@vanilla-f29-atomic container]$ cat file1.txt
foo
[vagrant@vanilla-f29-atomic container]$ cat file2.txt
foo
[vagrant@vanilla-f29-atomic container]$ ls -l file3.txt
lrwxrwxrwx. 1 vagrant vagrant 9 Nov  6 15:17 file3.txt -> file1.txt
[vagrant@vanilla-f29-atomic container]$ podman build -t foo .
STEP 1: FROM registry.fedoraproject.org/fedora:28
STEP 2: COPY ./file1.txt ./file3.txt /
--> Using cache f1a48ec444311e7d246fa87f1376ba121764e2e03e1881932245e77316a252a4
STEP 3: FROM f1a48ec444311e7d246fa87f1376ba121764e2e03e1881932245e77316a252a4
STEP 4: COPY ./ /
error building at step {Env:[DISTTAG=f28container FGC=f28 PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin] Command:copy Args:[./ /] Flags:[] Attrs:map[] Message:COPY ./ / Original:COPY ./ /}:
error copying "/var/home/vagrant/container" to "/var/home/vagrant/.local/share/containers/storage/overlay/1eabdb91fc68faf86371b069a96d748380980d28dfbd99518cf347d3e7632d91/merged": Error processing tar file(exit
 status 1): symlink file1.txt /file3.txt: file exists
```

If I switch and use root podman then it works fine:

```
[vagrant@vanilla-f29-atomic container]$ sudo podman build -t foo .
STEP 1: FROM registry.fedoraproject.org/fedora:28     
Getting image source signatures
Copying blob sha256:e69e955c514f72cef9e9e7db408266a32ba48133f0e2a27d5e4b52ed1995d864
 85.99 MB / 85.99 MB [======================================================] 4s
Copying config sha256:ded494ce3076e8f2d264235fdb09da5970921d8317f8fd024ab65821bf13e29f
 1.27 KB / 1.27 KB [========================================================] 0s
Writing manifest to image destination
Storing signatures               
STEP 2: COPY ./file1.txt ./file3.txt /
--> b8d36df28b30676737e9a2fbe5522cfea8740b945619b2db93df0e2584d4d12c
STEP 3: FROM b8d36df28b30676737e9a2fbe5522cfea8740b945619b2db93df0e2584d4d12c
STEP 4: COPY ./ /
--> 50da302acedfeff567ebd50e7077d7123f1c2faef82e3e428a4f5259c37db483
STEP 5: COMMIT foo
```

The real world scenario where I'm wanting to do this can be seen in [this Dockerfile](https://github.com/coreos/coreos-assembler/blob/ba61afb43afc62bc5e9accd7ab370ca1af34a008/Dockerfile).

**Comment by giuseppe** [comment] 2018-11-06 15:39
I think this is addressed by: https://github.com/containers/fuse-overlayfs/pull/24

**Comment by dustymabe** [comment] 2018-11-06 15:53
:+1:  - when that hits a fedora testing repo I can test. Let me know when that happens

**Comment by giuseppe** [comment] 2018-11-06 15:54
I am trying to reproduce locally, it might be related to Atomic Host where `/home` is a symlink and not related to the PR I've posted earlier

**Comment by giuseppe** [comment] 2018-11-06 20:56
@dustymabe I was able to reproduce it easily on a fresh DO droplet.  The issue is not in fuse-overlayfs but in the overlay backend trying to use mknod which is a privileged operation.  I've opened a PR for containers/storage here: https://github.com/containers/storage/pull/230

**Comment by dustymabe** [comment] 2018-11-06 21:40
thanks @giuseppe! glad I could help track down an issue so others don't hit it.

**Closed** 2018-11-12 10:49 UTC
