### ISSUE TITLE
Unable to build on rootless OpenSUSE

### ISSUE THREAD

**Issue by seanbow** [containers/buildah#1169] opened 2018-11-09 23:00 UTC
**Description**

I'm unable to use buildah to build a dockerfile. I am working in a fairly restricted OpenSUSE environment and so have installed buildah locally in my home directory. When running `buildah bud [...]` with literally any dockerfile the output is 

```
ERRO[0000] error reading allowed ID mappings: error reading subuid mappings for user "seanbow" and subgid mappings for group "seanbow": open /etc/subuid: no such file or directory
```

which makes sense because the file `/etc/subuid` does not exist...

**Steps to reproduce the issue:**
1. Run `buildah bud [...]` with any dockerfile input

**Describe the results you received:**

```
ERRO[0000] error reading allowed ID mappings: error reading subuid mappings for user "seanbow" and subgid mappings for group "seanbow": open /etc/subuid: no such file or directory
```

**Describe the results you expected:**

A successful build

**Output of `rpm -q buildah` or `apt list buildah`:**

```
package buildah is not installed
```
because I installed it from source locally in my home directory.

**Output of `buildah version`:**

```
Version:         1.5-dev
Go Version:      devel +2b534f28ce Fri Nov 9 17:37:16 2018 +0000
Image Spec:      1.0.0
Runtime Spec:    1.0.0
CNI Spec:        0.4.0
libcni Version:  v0.7.0-alpha1
Git Commit:      9add3c8f
Built:           Fri Nov  9 17:36:11 2018
OS/Arch:         linux/amd64
```

**Output of `podman version` if reporting a `podman build` issue:**

N/A

**Output of `cat /etc/*release`:**

```
NAME="openSUSE Leap"
VERSION="42.3"
ID=opensuse
ID_LIKE="suse"
VERSION_ID="42.3"
PRETTY_NAME="openSUSE Leap 42.3"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:leap:42.3"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"
openSUSE 42.3 (x86_64)
VERSION = 42.3
CODENAME = Malachite
```

**Output of `uname -a`:**

```
Linux LVN403-3 4.4.140-62-default #1 SMP Tue Jul 17 12:14:34 UTC 2018 (951943d) x86_64 x86_64 x86_64 GNU/Linux
```

**Output of `cat /etc/containers/storage.conf`:**

```
cat: /etc/containers/storage.conf: No such file or directory
```

**Comment by rhatdan** [comment] 2018-11-10 10:01
Enable to run as non root, you have to have entries for the user in the /etc/subuid and /etc/subgid files.
man subuid 
Should explain how to set this up.
@vrothberg PTAL

**Comment by vrothberg** [comment] 2018-11-12 07:54
Thanks for taking the time to open the issue, @seanbow.

How did you install buildah? It doesn't look like you're using the official openSUSE package which is currently:
```
Version:         1.4
Go Version:      go1.11.1
Image Spec:      1.0.0
Runtime Spec:    1.0.0
CNI Spec:        0.4.0
libcni Version:  v0.7.0-alpha1
Git Commit:      87239ae7046ea3a25f644cd0789b3d6678dc144d
Built:           Sun Nov  4 13:00:00 2018
OS/Arch:         linux/amd64
```

Notice that Buildah is currently only supported on openSUSE Tumbleweed (and Kubic). The devel project of the package is [devel:kubic](https://build.opensuse.org/package/show/devel:kubic/buildah), which has Leap 15 enabled for builds, which allows to install Buildah on Leap 15.

In your specific case, the required configuration files are missing. You can either install them on your and grab them from github.com/containers/{image,storage,libpod} or you can install the [libcontainers-common package](https://build.opensuse.org/package/show/devel:kubic/libcontainers-common).

**Comment by rhatdan** [comment] 2018-11-27 18:45
@seanbow Could you answer @vrothberg questions?  Do you still have this issue?

**Comment by vrothberg** [comment] 2018-11-28 07:41
I suggest closing this issue. A solution to the issue is described [above](https://github.com/containers/buildah/issues/1169#issuecomment-437787767). Please re-open if the issue re-occurs on Tumbleweed or if the proposed solution doesn't work.

**Closed by vrothberg** 2018-11-28 07:41 UTC
