### ISSUE TITLE
buildah bud reads a file from parent directory through a symlink

### ISSUE THREAD

**Issue by eriksjolund** [containers/buildah#1798] opened 2019-08-16 16:53 UTC
**Description**

`buildah bud .` can read a file in the parent directory by following a symlink.
`docker build .` (from __moby-engine__) on the other hand gives an error when building the same Dockerfile. I think it is better to give an error.

**Steps to reproduce the issue:**

```
erik@laptop:~$ mkdir test
erik@laptop:~$ cd test/
erik@laptop:~/test$ emacs -nw Dockerfile
erik@laptop:~/test$ cat Dockerfile
From scratch
ADD foobar /
CMD /foobar
erik@laptop:~/test$ echo hello > ../hello.txt
erik@laptop:~/test$ ln -s ../hello.txt foobar
erik@laptop:~/test$ buildah bud -t test1 .
STEP 1: FROM scratch
STEP 2: ADD foobar /
STEP 3: CMD /foobar
STEP 4: COMMIT test1
Getting image source signatures
Copying blob c7f1bacd27b0 done
Copying config 15563d09cd done
Writing manifest to image destination
Storing signatures
15563d09cdab15f2b9f3c9d802dc900187b975076260cdc35cbb138d4a9cdfd4
erik@laptop:~/test$ 
erik@laptop:~/test$ emacs -nw list.sh
erik@laptop:~/test$ cat list.sh 
container=$(buildah from localhost/test1)
mnt=$(buildah mount $container)
ls -l "$mnt/foobar"
cat "$mnt/foobar"
buildah umount $container                                                                                                                                                                               
buildah rm $container
erik@laptop:~/test$ buildah unshare bash list.sh
-rw-rw-r-- 1 root root 6 Aug 16 16:05 /home/erik/.local/share/containers/storage/overlay/89f3271b4dcd39b5d8403223c64275d6e982b58968d0f26db1f32c8217376c42/merged/foobar
hello
e04b15eded53e5ae1b3dd6454663ea3b4b73f5a610068e1d5879da9057b504bf
e04b15eded53e5ae1b3dd6454663ea3b4b73f5a610068e1d5879da9057b504bf
```

**Describe the results you received:**

I see that the newly built container contains the file

_/foobar_

that has the content

```
hello
```

In other words, I can conclude that the symlink
ln -s ../hello.txt foobar
was dereferenced in the command `buildah bud -t test1 .` 

**Describe the results you expected:**

I would have expected the command `buildah bud -t test1 .`  to fail as
Docker does. (I tried with package
moby-engine-18.06.3-2.ce.gitd7080c1.fc30.x86_64
in Fedora 30)

```
[erik@fedora test]$ docker build -t test .
Sending build context to Docker daemon  2.048kB
Step 1/3 : From scratch
 ---> 
Step 2/3 : ADD foobar /
ADD failed: stat /var/lib/docker/tmp/docker-builder249860419/foobar: no such file or directory
```

**Output of `rpm -q buildah` or `apt list buildah`:**

```
$ apt list buildah
Listing... Done
buildah/bionic,now 1.10.1-1~ubuntu18.04~ppa1 amd64 [installed]
```

**Output of `buildah version`:**

```
buildah version 1.10.1 (image-spec 1.0.1, runtime-spec 1.0.1-dev)
```

**Output of `cat /etc/*release`:**

```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.3 LTS"
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

**Output of `uname -a`:**

```
Linux aeserv19a 5.0.0-23-generic #24~18.04.1-Ubuntu SMP Mon Jul 29 16:12:28 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Output of `cat /etc/containers/storage.conf`:**

```
# storage.conf is the configuration file for all tools
# that share the containers/storage libraries
# See man 5 containers-storage.conf for more information

# The "container storage" table contains all of the server options.
[storage]

# Default Storage Driver
driver = "overlay"

# Temporary storage location
runroot = "/var/run/containers/storage"

# Primary read-write location of container storage
graphroot = "/var/lib/containers/storage"

[storage.options]
# AdditionalImageStores is used to pass paths to additional read-only image stores
# Must be comma separated list.
additionalimagestores = [
]

# Size is used to set a maximum size of the container image.  Only supported by
# certain container storage drivers (currently overlay, zfs, vfs, btrfs)
size = ""

# OverrideKernelCheck tells the driver to ignore kernel checks based on kernel version
override_kernel_check = "true"
```

**Comment by eriksjolund** [comment] 2019-08-16 20:53
Actually, there is no need to involve symlinks to see the different behavior of `buildah bud` and `docker build`. 
If we specify the file to be included as

`ADD ../hello.txt /hello.txt`

like this

``` 
From scratch
ADD ../hello.txt /hello.txt
CMD /hello.txt
```

 `buildah bud`  does not complain

```
erik@laptop:~/test$ buildah bud -t test1 .
STEP 1: FROM scratch
STEP 2: ADD ../hello.txt /
STEP 3: CMD /hello.txt
STEP 4: COMMIT test1
Getting image source signatures
Copying blob b5cfd02ed471 done
Copying config f9c5825f57 done
Writing manifest to image destination
Storing signatures
f9c5825f5794d7b7529c4073368c4aedb8370244721effcf8228886931614995
erik@laptop:~/test$
```

but `docker build` does complain


```
[erik@fedora test]$ docker build -t test .
Sending build context to Docker daemon  3.072kB
Step 1/3 : From scratch
 ---> 
Step 2/3 : ADD ../hello.txt /hello.txt
ADD failed: Forbidden path outside the build context: ../hello.txt ()
[erik@fedora test]$ 
```

**Comment by caiges** [comment] 2019-10-08 01:25
I wasn't able to reproduce at [7a7e1f0](https://github.com/containers/buildah/tree/7a7e1f07ee7b16c2299f334cd8f551c3e4a0c4cb). The error message is different but substantively similar. I tried both symlinks and regular files. I've included the symlink test below:

Working directory:
```
Dockerfile
hi.txt -> ../hello.txt
```
Dockerfile:
```
FROM scratch
ADD hi.txt /
```
Buildah output:
```
STEP 1: FROM scratch
STEP 2: ADD hi.txt /
error building at STEP "ADD hi.txt /": no files found matching "/home/caiges/Projects/buildah/tests/bud/copy-create-absolute-invalid-path/hello.txt": no such file or directory
ERRO exit status 1
```

Docker output:
```
docker build .
Sending build context to Docker daemon   2.56kB
Step 1/2 : FROM scratch
 ---> 
Step 2/2 : ADD hi.txt /
ADD failed: stat /var/lib/docker/tmp/docker-builder614252132/hello.txt: no such file or directory
```

**Comment by TomSweeneyRedHat** [comment] 2019-11-08 15:20
I'm going to close this as I was playing with a similar issue that resulted in this change for our error message #1970.  We've also made a number of changes to symbolic link handling since this was reported.  If you think this is still an issue, please feel free to reopen or create a new issue as you feel is warranted.

**Closed by TomSweeneyRedHat** 2019-11-08 15:20 UTC
Labels: good first issue
