### ISSUE TITLE
Buildah is not available for Ubuntu 22

### ISSUE THREAD

**Issue by adelton** [containers/buildah#4007] opened 2022-05-20 09:49 UTC
**Description**

GitHub Actions has added Ubuntu 22.04 LTS virtual environment: https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2204-Readme.md. However, unlike with Ubuntu 20.04 (https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-Readme.md), `buildah`, `podman`, and `skopeo` are not available.

Issue https://github.com/actions/virtual-environments/issues/5490 explicitly lists `buildah`, `podman`, and `skopeo` as missing in the "Software difference between Ubuntu 20 and Ubuntu 22" with note "Buildah is not available for Ubuntu 22 at the moment".

Please make Buildah available for Ubuntu 22 so that `ubuntu-22.04` environment can be used in GitHub Actions workflows that use `podman`.

**Steps to reproduce the issue:**
1. In a workflow that works on `ubuntu-20.04` and uses `podman`, change
```diff
-    runs-on: ubuntu-20.04
+    runs-on: ubuntu-22.04
```
for example https://github.com/adelton/redhat-entitlements/runs/6516332053?check_suite_focus=true.

**Describe the results you received:**

```
line 8: podman: command not found
```

**Describe the results you expected:**

Podman is installed on `ubuntu-22.04` GitHub Actions virtual environment and works.

Please provide Ubuntu 22.04-installable buildah and friends so that it can be included in `ubuntu-22.04`.

**Comment by flouthoc** [comment] 2022-05-20 10:35
Hi @adelton, Do you need `podman` or `buildah`. The issue is opened against `buildah` repo but your command is actually looking for `podman`. But anyways I think issue is quite similar to https://github.com/containers/buildah/issues/4006. I think @lsm5 can answer this better.

**Comment by adelton** [comment] 2022-05-20 12:21
I care about `podman` specifically. The reason why I filed this against `buildah` is because that's what https://github.com/actions/virtual-environments/issues/5490 uses as a justification for not installing `podman` on `ubuntu-22.04`.

**Comment by lsm5** [comment] 2022-05-23 14:27
Hi @adelton , github actions has gotten rid of container tools now, https://github.com/actions/virtual-environments/pull/5580 . AFAICT, this should not be an issue anymore. Closing..

**Closed by lsm5** 2022-05-23 14:27 UTC

**Comment by lsm5** [comment] 2022-05-23 15:36
@adelton responded. podman, buildah and skopeo are in the base 22.04 repos.

**Comment by lsm5** [comment] 2022-05-25 01:11
@adelton in case you also need to use the older ubuntu 20.04 and 18.04, buildah is back on the kubic repos. Sorry about the hassle.
