### ISSUE TITLE
using CLONE3 during podman build vs run

### ISSUE THREAD

**Issue by lbckmnn** [containers/buildah#3776] opened 2022-02-09 10:02 UTC
**Description**

I am trying to build a container with the following Dockerfile on a fresh installation of Debian 11:
``` Dockerfile
FROM quay.io/podman/stable

RUN dnf update
```
This fails with
```
STEP 1: FROM quay.io/podman/stable
STEP 2: RUN dnf update
Fedora 35 - x86_64                              0.0  B/s |   0  B     00:00    
Errors during downloading metadata for repository 'fedora':
  - Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-35&arch=x86_64 [getaddrinfo() thread failed to start]
Error: Failed to download metadata for repo 'fedora': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-35&arch=x86_64 [getaddrinfo() thread failed to start]
Error: error building at STEP "RUN dnf update": error while running runtime: exit status 1
```
Running  `dnf update` in a quay.io/podman/stable container manually leads to the same error.
This seems do be a kwnown issue with seccomp (CLONE3 syscall is not allowed) which should not occur with `--security-opt seccomp=unconfined ` (Fixing this with a proper seccomp.json is of course the better option).

Running the container with `podman run -it --security-opt seccomp=unconfined --rm quay.io/podman/stable` and executing `dnf update` does indeed work.

However, passing the same option to podman build does not work:
```
user@debian:~/podman_bug$ podman build --security-opt seccomp=unconfined .
STEP 1: FROM quay.io/podman/stable
STEP 2: RUN dnf update
Fedora 35 - x86_64                              0.0  B/s |   0  B     00:00    
Errors during downloading metadata for repository 'fedora':
  - Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-35&arch=x86_64 [getaddrinfo() thread failed to start]
Error: Failed to download metadata for repo 'fedora': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-35&arch=x86_64 [getaddrinfo() thread failed to start]
Error: error building at STEP "RUN dnf update": error while running runtime: exit status 1

```
I also tried to use [this](https://github.com/moby/moby/blob/master/profiles/seccomp/default.json) as content for /etc/containers/seccomp.json. 
This resolves the seccomp issue completely with `podman run` (the seccomp=unconfined is not needed anymore) but `podman build`still fails with the same error as before.

A possible related issue: https://github.com/containers/podman/issues/9506

**Output of `rpm -q buildah` or `apt list buildah`:**

```
buildah/stable,now 1.19.6+dfsg1-1+b6 amd64 [installed,automatic]
```

**Output of `buildah version`:**

```
buildah version 1.19.6 (image-spec 1.0.1, runtime-spec 1.0.2-dev)
```

**Output of `podman version` if reporting a `podman build` issue:**

```
Version:      3.0.1
API Version:  3.0.0
Go Version:   go1.15.9
Built:        Thu Jan  1 01:00:00 1970
OS/Arch:      linux/amd64

```

**Output of `cat /etc/*release`:**

```
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

```

**Output of `uname -a`:**

```
Linux debian 5.10.0-11-amd64 #1 SMP Debian 5.10.92-1 (2022-01-18) x86_64 GNU/Linux
```

**Comment by flouthoc** [comment] 2022-02-09 10:29
Hi @lbckmnn , Thanks for creating the issue.

I think that's cause you buildah is really old. `buildah` or `podman` from `main` honors `seccomp` which is configured correctly.
To conclude i am unable to reproduce this on latest buildah/podman which i pulled from `main` branch.

My console
```console
[fl@fedora bin]$ ./buildah build -t podman-test .
STEP 1/2: FROM quay.io/podman/stable
Trying to pull quay.io/podman/stable:latest...
Getting image source signatures
Copying blob 4545346f2a49 done  
Copying blob 091679a1fecc done  
Copying blob 4c7491564588 done  
Copying blob 3561be60ab19 done  
Copying blob a9ca4c4bd8c0 done  
Copying blob 7fcf55dbbc40 done  
Copying blob 9868556c9f57 done  
Copying blob 9c107df9c26d done  
Copying config 3b3a5920c8 done  
Writing manifest to image destination
Storing signatures
STEP 2/2: RUN dnf update
Fedora 35 - x86_64                               14 MB/s |  79 MB     00:05    
Fedora 35 openh264 (From Cisco) - x86_64        467  B/s | 2.5 kB     00:05    
Fedora Modular 35 - x86_64                      4.2 MB/s | 3.3 MB     00:00    
Fedora 35 - x86_64 - Updates                    506 kB/s |  25 MB     00:51    
Fedora Modular 35 - x86_64 - Updates            1.1 MB/s | 2.8 MB     00:02    
Dependencies resolved.
Nothing to do.
Complete!
COMMIT podman-test
Getting image source signatures
Copying blob 80f516d0e5a8 skipped: already exists  
Copying blob c0bb711ad1e5 skipped: already exists  
Copying blob ab3189b06ed5 skipped: already exists  
Copying blob 237dc109a01c skipped: already exists  
Copying blob 659d9a10e9a8 skipped: already exists  
Copying blob ed6aa5adc9cf skipped: already exists  
Copying blob ee996d9fabe8 skipped: already exists  
Copying blob 858d9109e483 skipped: already exists  
Copying blob e0dda00e1fb7 done  
Copying config aa612feb74 done  
Writing manifest to image destination
Storing signatures
--> aa612feb748
Successfully tagged localhost/podman-test:latest
aa612feb748d599fdddd01e5a09e3eb14f5b6b3e39ed0d122d04fa7f534d9f50
```

**Comment by lbckmnn** [comment] 2022-02-09 11:09
I was able to build the image directly with buildah: 
```
user@debian:~/podman_bug$ buildah bud --security-opt seccomp=unconfined -t podman-test .
STEP 1: FROM quay.io/podman/stable
STEP 2: RUN dnf update
Fedora 35 - x86_64                               17 MB/s |  79 MB     00:04  
```

So i guess my version of podman does not pass the `--security-opt seccomp=unconfined` to buildah?
Is it possible to place a seccomp.json somewhere as a workaround?

**Comment by flouthoc** [comment] 2022-02-09 11:49
@lbckmnn Thanks for confirming. I think your `podman` version is also very old could you upgrade it please. I am closing this issue since this is not present on newer versions but please feel free to continue discussion below and re-open issue if you feel anything is unresolved.

**Closed by flouthoc** 2022-02-09 11:49 UTC

**Comment by vrothberg** [comment] 2022-02-09 11:57
> So i guess my version of podman does not pass the --security-opt seccomp=unconfined to buildah?

Yes, there was an issue both in Podman (not passing the security opt) and libseccomp (https://bugzilla.redhat.com/show_bug.cgi?id=1927635).

> Is it possible to place a seccomp.json somewhere as a workaround?

If libseccomp in Debian is outdated (see https://bugzilla.redhat.com/show_bug.cgi?id=1927635), then the only workaround is to disable seccomp.

@giuseppe anything you want to add?

**Comment by lbckmnn** [comment] 2022-02-09 12:38
@vrothberg `apt list libseccomp2 `reports `libseccomp2/stable,now 2.5.1-1+deb11u1 amd64 [installed] ` as this is reported as fix version in the bug report i suppose the libseccomp version is fine?

@vrothberg my podman version is just the version from the current Debian 11 Repository. I can build and install the current podman version, if this helps investigating the issue. However, this does not fix the problem, that podman installed from the most recent Debian 11 sources is effectively not useable. I suppose i have to file a bug report to Debian about that?

**Comment by vrothberg** [comment] 2022-02-09 12:40
@lbckmnn, yes, filing a bug against Podman is probably the best way forward.  I pull in @siretart who is the Podman Debian maintainer.

I see two issues:
1. The syscall doesn´t work
2. podman build doesn´t pass the security opt

**Comment by lbckmnn** [comment] 2022-02-09 12:54
@vrothberg  I think the syscall does not work because the security opt is not passed to buildah and the seccomp.json is also not respected.

**Comment by rhatdan** [comment] 2022-02-09 20:49
Do we know if this is fixed in the 4.0?

**Comment by lbckmnn** [comment] 2022-02-09 22:44
I just tried the following on freshly installed Debian 11 (podman 3.0.1) and Debian 11 while using testing sources (podman  3.4.4)
Containerfile:
``` Dockerfile
FROM quay.io/fedora/fedora
RUN mkdir test
```

seccomp_test.json
``` json
{
        "defaultAction": "SCMP_ACT_ALLOW",
        "architectures": [
                "SCMP_ARCH_X86_64"
                ],
        "syscalls": [
        {
                "names": [
                        "mkdir"
                        ],
                "action": "SCMP_ACT_ERRNO"
        }
        ]
}
```
command:
`podman build --security-opt seccomp=seccomp_test.json .`

This failed (as intended) with podman 3.4.4 but run successfully in podman 3.0.1.
So i suppose this issue is indeed resolved in upstream podman.
I will file a bugreport to Debian.

**Comment by siretart** [comment] 2022-02-10 01:49
I believe this is a variation of the symptoms reported in https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=995777 -- I've prepared a fix for this and am waiting for approval to upload this to stable here: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1004533

Until then, you can try my test build packages at https://people.debian.org/~siretart/bug.994451/

**Comment by lbckmnn** [comment] 2022-02-10 09:23
@siretart with the version from https://people.debian.org/~siretart/bug.994451/ it is possible to build containers with CLONE3 but seccomp options are still not passed  to buildah (which is at least for me no serious problem anymore).
