### ISSUE TITLE
error building at STEP "RUN apt update": exit status 1

### ISSUE THREAD

**Issue by vl-shopback** [containers/buildah#3838] opened 2022-03-23 05:44 UTC
**Description**

**Steps to reproduce the issue:**
below works fine
```
cd /tmp
cat <<EOF > Dockerfile
FROM ubuntu
ENTRYPOINT ["/bin/bash", "-c", "/usr/bin/uname -m"]
EOF

IMAGE=${REGISTRY}/abcdefg/abc
buildah manifest rm $IMAGE || true
buildah manifest create $IMAGE
buildah bud --manifest $IMAGE --arch arm64 --variant v8
buildah bud --manifest $IMAGE --arch amd64
buildah manifest inspect $IMAGE
```
below got error
```
cd /tmp
cat <<EOF > Dockerfile
FROM ubuntu
RUN apt update
ENTRYPOINT ["/bin/bash", "-c", "/usr/bin/uname -m"]
EOF

IMAGE=${REGISTRY}/abcdefg/abc
buildah manifest rm $IMAGE || true
buildah manifest create $IMAGE
buildah bud --manifest $IMAGE --arch arm64 --variant v8
```

```
STEP 1/3: FROM ubuntu
Resolved "ubuntu" as an alias (/etc/containers/registries.conf.d/000-shortnames.conf)
Trying to pull docker.io/library/ubuntu:latest...
Getting image source signatures
Copying blob 57d0418fe9dc skipped: already exists
Copying config e784f03641 done
Writing manifest to image destination
Storing signatures
STEP 2/3: RUN apt update
process exited with error: fork/exec /bin/sh: exec format errorsubprocess exited with status 1
error building at STEP "RUN apt update": exit status 1
```

**Describe the results you received:**
buildah should work fine when build arm64 image on amd64 cpu

**Describe the results you expected:**
```
STEP 2/3: RUN apt update
process exited with error: fork/exec /bin/sh: exec format errorsubprocess exited with status 1
error building at STEP "RUN apt update": exit status 1
```

**Output of `rpm -q buildah` or `apt list buildah`:**

```# rpm -q buildah
buildah-1.23.1-1.fc35.x86_64
```

**Output of `buildah version`:**

```
buildah version 1.23.1 (image-spec 1.0.1-dev, runtime-spec 1.0.2-dev)
```

**Output of `podman version` if reporting a `podman build` issue:**

```
(paste your output here)
```

**Output of `cat /etc/*release`:**

```
Fedora release 35 (Thirty Five)
NAME="Fedora Linux"
VERSION="35 (Container Image)"
ID=fedora
VERSION_ID=35
VERSION_CODENAME=""
PLATFORM_ID="platform:f35"
PRETTY_NAME="Fedora Linux 35 (Container Image)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:35"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f35/system-administrators-guide/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=35
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=35
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Container Image"
VARIANT_ID=container
Fedora release 35 (Thirty Five)
Fedora release 35 (Thirty Five)
```

**Output of `uname -a`:**

```
Linux 28d463cc8b1c 5.11.0-1022-aws #23~20.04.1-Ubuntu SMP Mon Nov 15 14:03:19 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Output of `cat /etc/containers/storage.conf`:**

```
[storage]
driver = "overlay"
runroot = "/run/containers/storage"
graphroot = "/var/lib/containers/storage"
[storage.options]
additionalimagestores = [
"/var/lib/shared",
]
[storage.options.overlay]
mount_program = "/usr/bin/fuse-overlayfs"
mountopt = "nodev,fsync=0"
[storage.options.thinpool]
```

**Comment by flouthoc** [comment] 2022-03-23 06:24
Hi @vl-shopback , Thanks for opening the issues. 

This is expected behviour since `RUN apt update` is executed while building the image, but your current platform is `linux/amd64` while you pulled the base image for `--arch arm64 --variant v8` hence its trying to execute binary which does not matches with the current platform.

You can solve this by

* Using emulator which can support executing binary for different architectures , i'd suggest looking for `qemu-user-static` https://github.com/multiarch/qemu-user-static, https://wiki.debian.org/QemuUserEmulation

Or

* You can also pull the base image for your host friendly platform and tag it as the different platform in manifest list, so something like this should work.

```dockerfile
FROM --platform=linux/amd64 ubuntu
RUN apt update
ENTRYPOINT ["/bin/bash", "-c", "/usr/bin/uname -m"]
```
```console
IMAGE=${REGISTRY}/abcdefg/abc
buildah manifest rm $IMAGE || true
buildah manifest create $IMAGE
buildah bud --manifest $IMAGE --arch arm64 --variant v8
```

I'm closing this issue since this is the expected behavior and does not seems a buildah issue but we can keep discussing below.

Thanks

**Closed by flouthoc** 2022-03-23 06:24 UTC
