### ISSUE TITLE
"man buildah-containers" doesn't mention "scratch" container

### ISSUE THREAD

**Issue by rpjday** [containers/buildah#1462] opened 2019-03-30 22:43 UTC
When I run "buildah containers", I see a scratch container which, for now, I will simply assume will always exist to allow building a new image from scratch. So what I see is:
```
$ buildah containers
CONTAINER ID  BUILDER  IMAGE ID     IMAGE NAME                       CONTAINER NAME
81b1fec124e0     *                  scratch                          working-container
```
and I see no way to delete that container, which seems reasonable.

However, "man buildah-containers" shows examples which do not display the scratch container:
```
buildah containers

       CONTAINER ID  BUILDER  IMAGE ID     IMAGE NAME                       CONTAINER NAME
       29bdb522fc62     *     3fd9065eaf02 docker.io/library/alpine:latest  alpine-working-container
       c6b04237ac8e     *     f9b6f7f7b9d3 docker.io/library/busybox:latest busybox-working-container
```
Should those examples also show the scratch container? Or am I badly misreading something?

**Comment by rpjday** [comment] 2019-03-30 22:46
P.S. With no containers, I used buildah to build a fedora-based container and, sure enough:
```
$ buildah containers
CONTAINER ID  BUILDER  IMAGE ID     IMAGE NAME                       CONTAINER NAME
81b1fec124e0     *                  scratch                          working-container
8cead8c5957f     *     d09302f77cfc docker.io/library/fedora:latest  fedora-working-container
```
so it seems like EXAMPLES should always show the scratch container, regardless of which other containers have been built, no?

**Comment by rhatdan** [comment] 2019-03-31 14:24
buildah rm 81b1fec124e0

Should work.  The default should be to have no containers.

You can start fresh by executing

buildah rm -a -f

**Comment by rpjday** [comment] 2019-03-31 14:59
But is there a reason I can't delete that container via "podman rm"? If it's a regular container, should I not be able to do:

```
$ podman rm 81b1fec124e0
Error: unable to find container 81b1fec124e0: no container with name or ID 81b1fec124e0 found: no such container
```

Is there something about that container that requires buildah to get rid of it? Can you confirm that you see the same thing? Or am I just being clueless?

**Comment by rhatdan** [comment] 2019-03-31 15:06
If you use the upstream version of podman, then podman rm -f 81b1fec124e0 should work.
The problem is buildah and podman have very different concepts of a container.  Podman containers are referenced in libpod's database.  Podman containers have full concepts like binding to ports and a much different inspect data.

Buildah containers are just references to images, before they are committed. They do not use libpod, so when you attempt to remove a buildah container with podman you get those errors.  SImilarly buildah does not see podman containers.

What they do see is each others "Storage containers", Which is why podman rm -f UUID works.

**Comment by rpjday** [comment] 2019-03-31 15:19
Ah, that is not at all obvious, thanks. I will make a note of that.

**Comment by TomSweeneyRedHat** [comment] 2019-04-01 13:27
@rpjday Thanks for the issue.  I believe @rhatdan has explained what you see.  Summarizing, the scratch container is not there all the time and should be removable with Buildah.   Depending on the version of Podman, you may be able to remove it with `rm -f`.    If you think this issue needs more attention, please feel free to reopen it.

**Closed by TomSweeneyRedHat** 2019-04-01 13:27 UTC
