### ISSUE TITLE
`podman build --no-cache` is not working properly with multistage build.

### ISSUE THREAD

**Issue by queeup** [containers/buildah#4462] opened 2022-12-11 13:44 UTC
**Description**
`podman build --no-cache` is not working properly with multistage build. It is ignoring first stages. 

```bash
❯ podman build --no-cache --tag no-cache-test --file no-cache-test.Containerfile
[2/2] STEP 1/2: FROM alpine AS alpine2
[2/2] STEP 2/2: RUN echo "alpine2: podman --no-cache is working!"
alpine2: podman --no-cache is working!
[2/2] COMMIT no-cache-test
--> 2959341d567
Successfully tagged localhost/no-cache-test:latest
2959341d56774aaf3b89702734029b0986451671f96f5d95ee9e090f99a75134
```

**Steps to reproduce the issue:**
1. Build Containerfile below with `podman build --no-cache`
```Dockerfile
FROM alpine AS alpine1

RUN echo "alpine1: podman --no-cache is working!"

FROM alpine AS alpine2

RUN echo "alpine2: podman --no-cache is working!"
```

**Describe the results you received:**
On the example build above, Only second stage RUN working with `--no-cache`. First stage RUN is not printed text to the terminal because it uses cache.

**Describe the results you expected:**
I expected to print both RUN command text on the terminal if I use `--no-cache`

**Output of `rpm -q buildah` or `apt list buildah`:**

```
buildah-1.28.0-6.fc37.x86_64
```

**Output of `buildah version`:**

```
Version:         1.28.0
Go Version:      go1.19.2
Image Spec:      1.0.2-dev
Runtime Spec:    1.0.2-dev
CNI Spec:        1.0.0
libcni Version:  v1.1.2
image Version:   5.23.0
Git Commit:      
Built:           Tue Oct 25 17:14:21 2022
OS/Arch:         linux/amd64
BuildPlatform:   linux/amd64

```

**Output of `podman version` if reporting a `podman build` issue:**

```
Client:       Podman Engine
Version:      4.3.1
API Version:  4.3.1
Go Version:   go1.19.2
Built:        Fri Nov 11 18:01:27 2022
OS/Arch:      linux/amd64

```

**Output of `cat /etc/*release`:**

```
Fedora release 37 (Thirty Seven)
NAME="Fedora Linux"
VERSION="37.20221209.0 (Silverblue)"
ID=fedora
VERSION_ID=37
VERSION_CODENAME=""
PLATFORM_ID="platform:f37"
PRETTY_NAME="Fedora Linux 37.20221209.0 (Silverblue)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:37"
DEFAULT_HOSTNAME="fedora"
HOME_URL="https://silverblue.fedoraproject.org"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora-silverblue/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://github.com/fedora-silverblue/issue-tracker/issues"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=37
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=37
SUPPORT_END=2023-11-14
VARIANT="Silverblue"
VARIANT_ID=silverblue
OSTREE_VERSION='37.20221209.0'
Fedora release 37 (Thirty Seven)
Fedora release 37 (Thirty Seven)

```

**Output of `uname -a`:**

```
Linux fedora-t480 6.0.11-300.fc37.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Dec 2 20:47:45 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

```

**Output of `cat /etc/containers/storage.conf`:**

```
(paste your output here)
```

**Comment by flouthoc** [comment] 2022-12-11 15:08
Hi @queeup , It is expected behavior since the first stage is not part of the target stage hence it is being skipped as it is marked as unused to prevent this add `--skip-unused-stages=false` or use the first stage in the target stage like

```Dockerfile
FROM alpine AS alpine1

RUN echo "alpine1: podman --no-cache is working!"
RUN echo hello > world

FROM alpine AS alpine2
COPY --from=alpine1 world .
RUN echo "alpine2: podman --no-cache is working!"
```

I hope this helps :) I'm closing this issue but please feel free to re-open or comment below :)

**Closed by flouthoc** 2022-12-11 15:08 UTC

**Comment by flouthoc** [comment] 2022-12-12 04:15
@queeup No issues at all it was added in one of the recent versions :)
