### ISSUE TITLE
buildah image archives can't be imported on kind/containerd

### ISSUE THREAD

**Issue by sebastianwebber** [containers/buildah#2542] opened 2020-08-13 00:50 UTC
**Description**

I use Kind to run some integration tests for our applications. Those tests run on a pipeline and the build happens on different stages, so I export the built images on a tar file then on the test stage I use `kind load image-archive` to load that images and use them. Internally `kind` uses the `ctr` to import the images.

The `tar` images generated by `buildah push` aren't being imported by Containerd. I created those images using both a `Dockerfile` (built with `buildah bud`) and a "regular build" (built with regular `buildah add`, `buildah copy`, `buildah commit`).

Building and exporting the same Dockerfile with Docker works without a problem.

I created this sample repo with the tests that I did: https://github.com/sebastianwebber/buildah-issue-demo

once I try to import the images with `ctr` nothing happens:

```bash
➜ sudo ctr --debug --namespace=k8s.io images import --all-platforms --no-unpack target/images/oci-dockerfile-example-master.tar
➜ sudo ctr --debug --namespace=k8s.io images import --all-platforms --no-unpack target/images/docker-dockerfile-example-master.tar
DEBU[0001] file type ignored                             file=29bad1020e6fc9b3c41ec1842a1a701596a1a10e3f9238459587c7465f71221a/layer.tar
DEBU[0001] file type ignored                             file=ec718b963693b22e5513fb4cc333d8c4b922df5dd7c9209251349603c5429b10/layer.tar
DEBU[0001] file type ignored                             file=6550f3af5a0cefa781584b14e70642734dc8924670ff87702ce85cda66ee297a/layer.tar
➜ sudo ctr images ls
REF TYPE DIGEST SIZE PLATFORMS LABELS
```

Is this possibly a bug on `buildah push`?

**Steps to reproduce the issue:**

1. [checkout the repo](https://github.com/sebastianwebber/buildah-issue-demo) with the [dockerfile](https://github.com/sebastianwebber/buildah-issue-demo/blob/master/Dockerfile) and examples.

1. build image using `buildah bud`:

    ```bash
    buildah build-using-dockerfile \
            --format docker \
            --file Dockerfile \
            --volume $(pwd)/config/:/config \
            --tag dockerfile-example:latest \
            --build-arg BUILD_VERSION="master"
    ```

2. export the image to a tar file:

    ```bash
    rm -rf "target/images"
    mkdir -p "target/images"
    buildah push \
            --format docker \
            dockerfile-example:latest \
            docker-archive:target/images/docker-dockerfile-example-master.tar
    buildah push \
            --format oci \
            dockerfile-example:latest \
            oci-archive:target/images/oci-dockerfile-example-master.tar
    ```

3. import the images on containerd:

    ```bash
    sudo ctr --debug --namespace=k8s.io images import --all-platforms --no-unpack target/images/oci-dockerfile-example-master.tar
    sudo ctr --debug --namespace=k8s.io images import --all-platforms --no-unpack target/images/docker-dockerfile-example-master.tar
    ```

**Describe the results you received:**

tar images aren't being imported on containerd.

**Describe the results you expected:**

tar images are imported on containerd and/or display the error that keeps the image to be imported.

**Output of `rpm -q buildah` or `apt list buildah`:**

```
➜ apt list buildah
Listing... Done
buildah/unknown,now 1.15.1~1 amd64 [installed]
buildah/unknown 1.15.1~1 arm64
buildah/unknown 1.15.1~1 armhf
buildah/unknown 1.15.1~1 s390x
```

**Output of `buildah version`:**

```
buildah version 1.15.1 (image-spec 1.0.1-dev, runtime-spec 1.0.2-dev)
```

**Output of `podman version` if reporting a `podman build` issue:**

```
➜ podman version
Version:      2.0.4
API Version:  1
Go Version:   go1.14.2
Built:        Wed Dec 31 21:00:00 1969
OS/Arch:      linux/amd64
```

**Output of `cat /etc/*release`:**

```
➜ cat /etc/*release
DISTRIB_ID=Pop
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Pop!_OS 20.04 LTS"
NAME="Pop!_OS"
VERSION="20.04 LTS"
ID=pop
#ID=ubuntu
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.04 LTS"
VERSION_ID="20.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
LOGO=distributor-logo-pop-os
```

**Output of `uname -a`:**

```
Linux venusaur 5.4.0-7634-generic #38~1596560323~20.04~7719dbd-Ubuntu SMP Tue Aug 4 19:12:34 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
```

**Output of `cat /etc/containers/storage.conf`:**

```
➜ cat /etc/containers/storage.conf
# This file is is the configuration file for all tools
# that use the containers/storage library.
# See man 5 containers-storage.conf for more information
# The "container storage" table contains all of the server options.
[storage]

# Default Storage Driver
driver = ""

# Temporary storage location
runroot = "/var/run/containers/storage"

# Primary Read/Write location of container storage
graphroot = "/var/lib/containers/storage"

# Storage path for rootless users
#
# rootless_storage_path = "$HOME/.local/share/containers/storage"

[storage.options]
# Storage options to be passed to underlying storage drivers

# AdditionalImageStores is used to pass paths to additional Read/Only image stores
# Must be comma separated list.
additionalimagestores = [
]

# Remap-UIDs/GIDs is the mapping from UIDs/GIDs as they should appear inside of
# a container, to the UIDs/GIDs as they should appear outside of the container,
# and the length of the range of UIDs/GIDs.  Additional mapped sets can be
# listed and will be heeded by libraries, but there are limits to the number of
# mappings which the kernel will allow when you later attempt to run a
# container.
#
# remap-uids = 0:1668442479:65536
# remap-gids = 0:1668442479:65536

# Remap-User/Group is a user name which can be used to look up one or more UID/GID
# ranges in the /etc/subuid or /etc/subgid file.  Mappings are set up starting
# with an in-container ID of 0 and then a host-level ID taken from the lowest
# range that matches the specified name, and using the length of that range.
# Additional ranges are then assigned, using the ranges which specify the
# lowest host-level IDs first, to the lowest not-yet-mapped in-container ID,
# until all of the entries have been used for maps.
#
# remap-user = "containers"
# remap-group = "containers"

# Root-auto-userns-user is a user name which can be used to look up one or more UID/GID
# ranges in the /etc/subuid and /etc/subgid file.  These ranges will be partioned
# to containers configured to create automatically a user namespace.  Containers
# configured to automatically create a user namespace can still overlap with containers
# having an explicit mapping set.
# This setting is ignored when running as rootless.
# root-auto-userns-user = "storage"
#
# Auto-userns-min-size is the minimum size for a user namespace created automatically.
# auto-userns-min-size=1024
#
# Auto-userns-max-size is the minimum size for a user namespace created automatically.
# auto-userns-max-size=65536

[storage.options.overlay]
# ignore_chown_errors can be set to allow a non privileged user running with
# a single UID within a user namespace to run containers. The user can pull
# and use any image even those with multiple uids.  Note multiple UIDs will be
# squashed down to the default uid in the container.  These images will have no
# separation between the users in the container. Only supported for the overlay
# and vfs drivers.
#ignore_chown_errors = false

# Path to an helper program to use for mounting the file system instead of mounting it
# directly.
#mount_program = "/usr/bin/fuse-overlayfs"

# mountopt specifies comma separated list of extra mount options
mountopt = "nodev"

# Set to skip a PRIVATE bind mount on the storage home directory.
# skip_mount_home = "false"

# Size is used to set a maximum size of the container image.
# size = ""

[storage.options.thinpool]
# Storage Options for thinpool

# autoextend_percent determines the amount by which pool needs to be
# grown. This is specified in terms of % of pool size. So a value of 20 means
# that when threshold is hit, pool will be grown by 20% of existing
# pool size.
# autoextend_percent = "20"

# autoextend_threshold determines the pool extension threshold in terms
# of percentage of pool size. For example, if threshold is 60, that means when
# pool is 60% full, threshold has been hit.
# autoextend_threshold = "80"

# basesize specifies the size to use when creating the base device, which
# limits the size of images and containers.
# basesize = "10G"

# blocksize specifies a custom blocksize to use for the thin pool.
# blocksize="64k"

# directlvm_device specifies a custom block storage device to use for the
# thin pool. Required if you setup devicemapper.
# directlvm_device = ""

# directlvm_device_force wipes device even if device already has a filesystem.
# directlvm_device_force = "True"

# fs specifies the filesystem type to use for the base device.
# fs="xfs"

# log_level sets the log level of devicemapper.
# 0: LogLevelSuppress 0 (Default)
# 2: LogLevelFatal
# 3: LogLevelErr
# 4: LogLevelWarn
# 5: LogLevelNotice
# 6: LogLevelInfo
# 7: LogLevelDebug
# log_level = "7"

# min_free_space specifies the min free space percent in a thin pool require for
# new device creation to succeed. Valid values are from 0% - 99%.
# Value 0% disables
# min_free_space = "10%"

# mkfsarg specifies extra mkfs arguments to be used when creating the base
# device.
# mkfsarg = ""

# Size is used to set a maximum size of the container image.
# size = ""

# use_deferred_removal marks devicemapper block device for deferred removal.
# If the thinpool is in use when the driver attempts to remove it, the driver
# tells the kernel to remove it as soon as possible. Note this does not free
# up the disk space, use deferred deletion to fully remove the thinpool.
# use_deferred_removal = "True"

# use_deferred_deletion marks thinpool device for deferred deletion.
# If the device is busy when the driver attempts to delete it, the driver
# will attempt to delete device every 30 seconds until successful.
# If the program using the driver exits, the driver will continue attempting
# to cleanup the next time the driver is used. Deferred deletion permanently
# deletes the device and all data stored in device will be lost.
# use_deferred_deletion = "True"

# xfs_nospace_max_retries specifies the maximum number of retries XFS should
# attempt to complete IO when ENOSPC (no space) error is returned by
# underlying storage device.
# xfs_nospace_max_retries = "0"
```

Attaching the output of [`make all` command](https://github.com/containers/buildah/files/5066581/all.log).

**Comment by rhatdan** [comment] 2020-08-13 10:38
@nalind PTAL

**Comment by rhatdan** [comment] 2020-10-07 18:29
@sebastianwebber Is this still an issue,  I have a feeling this is because buildah defaults to OCI images and perhaps these tools can't deal with them.
If you want to build the older docker format, you can specify `--format docker`

**Comment by sebastianwebber** [comment] 2021-01-28 03:57
hey @rhatdan sorry for the delay.

I'm already using the `--format=docker`.

Did you got a chance to check the repo that I've created? 

Thanks.

**Comment by VJftw** [comment] 2021-01-30 04:28
I'm experiencing the same, additionally, I seem to be losing the image repository and tag when exporting to a docker tar and re-importing it via `buildah`:
```
$ buildah --version
buildah version 1.19.2 (image-spec 1.0.1-dev, runtime-spec 1.0.2-dev)
```

1. build and export an image in `docker` format to `my-image.tar`:
```
$ newContainer=$(buildah from scratch) && \
  buildah commit --format docker --rm --squash $newContainer my-image && \
  buildah push --format docker my-image docker-archive:my-image.tar
Getting image source signatures
Copying blob 5f70bf18a086 done  
Copying config fe67c279be done  
Writing manifest to image destination
Storing signatures
fe67c279be7fc15070c1c818786f2a7c8bf6637c9bd042962cc0478178ce26d4
Getting image source signatures
Copying blob 5f70bf18a086 done  
Copying config fe67c279be done  
Writing manifest to image destination
Storing signatures
```
2. note that `my-image:latest` exists locally, and then remove it
```
$ buildah images
REPOSITORY           TAG      IMAGE ID       CREATED         SIZE
localhost/my-image   latest   fe67c279be7f   3 seconds ago   2.82 KB

$ buildah rmi my-image
untagged: localhost/my-image:latest
fe67c279be7fc15070c1c818786f2a7c8bf6637c9bd042962cc0478178ce26d4
```
3. import the tar image
```
$ buildah pull docker-archive:my-image.tar
Getting image source signatures
Copying blob 5f70bf18a086 done  
Copying config fe67c279be done  
Writing manifest to image destination
Storing signatures
fe67c279be7fc15070c1c818786f2a7c8bf6637c9bd042962cc0478178ce26d4
```
4. note that the image has no repository but the same ID (when we expect it to have same repository and tag as before)
```
$ buildah images
REPOSITORY   TAG      IMAGE ID       CREATED          SIZE
<none>       <none>   fe67c279be7f   48 seconds ago   2.83 KB
```

**Comment by rhatdan** [comment] 2021-02-02 20:00
@mtrmac @QiWang19 Is this a bug in buildah?  Or does `podman import` do something different?

**Comment by mtrmac** [comment] 2021-02-02 20:11
> I seem to be losing the image repository and tag when exporting to a docker tar and re-importing it via `buildah`:
> 
> ```
>   buildah push --format docker my-image docker-archive:my-image.tar
> …
> $ buildah pull docker-archive:my-image.tar
> …
> ```
> 
> note that the image has no repository but the same ID (when we expect it to have same repository and tag as before)
> 
> ```
> $ buildah images
> REPOSITORY   TAG      IMAGE ID       CREATED          SIZE
> <none>       <none>   fe67c279be7f   48 seconds ago   2.83 KB
> ```

This is expected; the `docker-archive:$path` syntax means “create a docker-archive tarball at $path that contains an unnamed image”. Use something like `docker-archive:my-image.tar:localhost/my-image:latest` .

Similarly `oci-archive:$path` creates an archive that contains an unnamed image.

---

The `containerd` import failure is not so obvious to me, and would require reproducing/debugging; it might possibly just be the reader ignoring unnamed images, but the
> ```
> DEBU[0001] file type ignored                             file=29bad1020e6fc9b3c41ec1842a1a701596a1a10e3f9238459587c7465f71221a/layer.tar
> ```
warnings look a bit worrisome WRT the approach used by c/image to generate the archive.

**Comment by VJftw** [comment] 2021-02-02 20:31
> This is expected; the `docker-archive:$path` syntax means “create a docker-archive tarball at $path that contains an unnamed image”. Use something like `docker-archive:my-image.tar:localhost/my-image:latest` .

Amazing, thanks! this has resolved my `kind load image-archive ...` issue too :ok_hand:. I missed the 'image:tag` suffix from the docs here: https://github.com/containers/buildah/blob/master/docs/buildah-push.md#example

**Comment by rhatdan** [comment] 2021-02-03 20:42
I believe I can close this as solved.  Reopen if I am mistaken.

**Closed by rhatdan** 2021-02-03 20:42 UTC
Labels: question

**Comment by alakdam07** [comment] 2023-05-30 08:23
@mtrmac, sorry to bother you. 

I have one Dockerfile from the Dockerfile I want to release node [semantic-versioning](https://semver.org/) release. I used loop to tag images then save it by using [docker-archive](https://manpages.ubuntu.com/manpages/impish/man1/buildah-push.1.html). In loop after saving MAJOR_VERSION_TAG when it tries to save MINOR_VERSION_TAG, it throws me the error: docker-archive doesn't support modifying existing images. I am not sure how to resolve this issue. Can you please help me to fix the issue?

```
buildah build --squash -t "${DOCKER_REGISTRY_IMAGE_NAME}:${TARGET_VERSION}" -f "${DOCKERFILE}" .

# Create a container from the image and retrieve OS information
CONTAINER=$(buildah from --pull=false "${DOCKER_REGISTRY_IMAGE_NAME}:${TARGET_VERSION}")

LINUX_DISTRIBUTION=$(buildah run "$CONTAINER" cat /etc/os-release | grep -w "NAME" | sed 's/.*"\(.*\)"/\1/' | cut -d ' ' -f1)
NODE_VERSION=$(buildah run "$CONTAINER" node --version)

# Extract major, minor, and patch version
MAJOR_VERSION_TAG=$(echo "$NODE_VERSION" | sed 's/^v//' | cut -d'.' -f1)
MINOR_VERSION_TAG=$(echo "$NODE_VERSION" | sed 's/^v//' | cut -d'.' -f1-2)
PATCH_VERSION_TAG=$(echo "$NODE_VERSION" | sed 's/^v//')


ZIP_TARGET="${ARTIFACT_PATH}/${CI_PROJECT_NAME}.tar.gz"
mkdir -p "${ARTIFACT_PATH}"

# # Create an array list
NODE_TAG_VERSIONS=("${MAJOR_VERSION_TAG}" "${MINOR_VERSION_TAG}" "${PATCH_VERSION_TAG}")
# Buildah doesn't support multiple tags push.
for NEW_TAG in "${NODE_TAG_VERSIONS[@]}"; do
  echo "Tagging $NEW_TAG"
  buildah tag "${DOCKER_REGISTRY_IMAGE_NAME}:${TARGET_VERSION}" "${DOCKER_REGISTRY_IMAGE_NAME}:${NEW_TAG}-${LINUX_DISTRIBUTION}-${BUILD_VARIANT}"
  buildah push --rm --format docker "${DOCKER_REGISTRY_IMAGE_NAME}:${NEW_TAG}-${LINUX_DISTRIBUTION}-${BUILD_VARIANT}" "docker-archive:${ZIP_TARGET}:${DOCKER_REGISTRY_IMAGE_NAME}:${NEW_TAG}-${LINUX_DISTRIBUTION}-${BUILD_VARIANT}" ## docker-archive doesn't support modifying existing images
done

## remove the initial image

buildah rmi "${DOCKER_REGISTRY_IMAGE_NAME}:${TARGET_VERSION}"
```
