### ISSUE TITLE
`buildah rmi -f` silently "fails" when ID contains `sha256:`

### ISSUE THREAD

**Issue by kwshi** [containers/buildah#3206] opened 2021-05-06 03:39 UTC
**Description**

When a parent image has dependent child images, it cannot be removed (unless the children are first removed).  Attempting to do so with either `buildah rmi` or `buildah rmi -f` outputs the same 
```
unable to delete "..." (cannot be forced) - image has dependent child images
```
error message.  _However_, if the parent image ID is passed to `buildah rmi` in `sha256:...` form, then no error message is thrown (it should be)--instead, an empty `untagged:` list is printed.

**Steps to reproduce the issue:**
1. `parent=$(buildah from scratch)`
2. `parent_img=$(buildah commit $parent parent-img)`.  `parent_img` now contains an image ID that looks like `d1957dbfbca8d3ef98c2c49bebe68b8030634ca19a6320fdd0640c60474408f4`.
3. `child=$(buildah from parent-img)`
4. `buildah commit $child child-img`
5. Now `parent-img` has `child-img` as a dependent, so `parent-img` cannot be removed.  Attempting to run `buildah rmi $parent_img` will print an error message, as expected.  However, running `buildah rmi sha256:$parent_img` does _not_ print an error message.

**Describe the results you received:**

`buildah rmi sha256:$parent_img` does not result in an error message.

**Describe the results you expected:**

The behavior of `buildah rmi $parent_img` and `buildah rmi sha256:$parent_img` should be consistent, since they mean the same thing (assuming `$parent_img` is in image hash ID format), right?  I've noticed that the plain ID (without `sha256:`) is the one usually printed to stdout by `buildah commit`, whereas the `sha256:` ID (which is the exact same as the plain ID, just with an extra prefix) is the one written to `--iidfile` as well as the one outputted by `buildah images -q --no-trunc`.

**Output of ~`rpm -q buildah` or `apt list buildah`:~ `xbps-query -R buildah`**

```
architecture: x86_64
changelog: https://github.com/containers/buildah/blob/master/CHANGELOG.md
filename-sha256: 25806183e98deae0653cf8c2faa61e61426343e5cb50fb3ca6f3088e61d2d6a3
filename-size: 13MB
homepage: https://github.com/containers/buildah
installed_size: 29MB
license: Apache-2.0
maintainer: Cameron Nemo <cnemo@tutanota.com>
pkgname: buildah
pkgver: buildah-1.20.1_1
repository: https://alpha.us.repo.voidlinux.org/current
run_depends:
	runc>=0
	containers.image>=0
	glibc>=2.32_1
	libgpgme>=1.12.0_2
	libassuan>=2.0.1_1
	libgpg-error>=1.6_1
	device-mapper>=2.02.110_1
shlib-requires:
	libpthread.so.0
	libgpgme.so.11
	libassuan.so.0
	libgpg-error.so.0
	libdl.so.2
	libdevmapper.so.1.02
	libc.so.6
short_desc: Dockerfile compatible OCI image building tool
source-revisions: buildah:b177108fa1
```

**Output of `buildah version`:**

```
Version:         1.20.1
Go Version:      go1.16.3
Image Spec:      1.0.1-dev
Runtime Spec:    1.0.2-dev
CNI Spec:        0.4.0
libcni Version:  
image Version:   5.10.5
Git Commit:      
Built:           Wed Dec 31 16:00:00 1969
OS/Arch:         linux/amd64
```

**Output of `cat /etc/*release`:**

```
NAME="void"
ID="void"
DISTRIB_ID="void"
PRETTY_NAME="void"
```

**Output of `uname -a`:**

```
Linux vic 5.11.12_1 #1 SMP 1617903641 x86_64 GNU/Linux
```

**Output of ~`cat /etc/containers/storage.conf`~ (no such file, here's `buildah info` instead):**

```
{
    "host": {
        "CgroupVersion": "v1",
        "Distribution": {
            "distribution": "\"void\"",
            "version": "unknown"
        },
        "MemFree": 4459892736,
        "MemTotal": 67415830528,
        "OCIRuntime": "runc",
        "SwapFree": 0,
        "SwapTotal": 0,
        "arch": "amd64",
        "cpus": 12,
        "hostname": "vic",
        "kernel": "5.11.12_1",
        "os": "linux",
        "rootless": true,
        "uptime": "369h 44m 50.6s (Approximately 15.38 days)"
    },
    "store": {
        "ContainerStore": {
            "number": 13
        },
        "GraphDriverName": "overlay",
        "GraphOptions": [
            "overlay.mount_program=/usr/bin/fuse-overlayfs"
        ],
        "GraphRoot": "/home/kshi/.local/share/containers/storage",
        "GraphStatus": {
            "Backing Filesystem": "extfs",
            "Native Overlay Diff": "false",
            "Supports d_type": "true",
            "Using metacopy": "false"
        },
        "ImageStore": {
            "number": 22
        },
        "RunRoot": "/var/tmp/containers-user-1000/containers"
    }
}
```

**Comment by vrothberg** [comment] 2021-05-06 07:10
Thank you for reaching out and for great reproducer.

This should now be fixed.  Following your reproducer, the first error I get now is
> Image used by e89bb4514ee230e5b447e6c610e38ef0bbbc2ea92bc9441e61d620daf6f65ce4: image is in use by a container

After a `buildah rm -a`, I now get the following output
> untagged: localhost/parent-img:latest

That means that the image has been untagged. It won't show up in `buildah images` anymore.  The reason for it not being reported as "removed" is that all it's layers are still present in the local storage as it has child images still using it.

@nalind @rhatdan PTAL.  The behavior changed with the libimage (Docker compat).

**Comment by rhatdan** [comment] 2021-05-06 12:43
SGTM

**Comment by nalind** [comment] 2021-05-06 13:49
Wait, so the image's record is still there?  Why?  The presence of images that use the same layers that the image that we're asked to remove shouldn't matter.

**Comment by vrothberg** [comment] 2021-05-06 13:52
> Wait, so the image's record is still there? Why? The presence of images that use the same layers that the image that we're asked to remove shouldn't matter.

With libimage, it is not there.

**Comment by nalind** [comment] 2021-05-06 14:16
So the image's record was removed, but we don't say that?

**Comment by vrothberg** [comment] 2021-05-06 14:58
> So the image's record was removed, but we don't say that?

Yes

**Comment by vrothberg** [comment] 2021-05-06 15:08
Ah ... if we `force` delete, it will be reported as such.

**Comment by rhatdan** [comment] 2021-06-07 13:35
@vrothberg @nalind Where are we on this issue?

**Comment by vrothberg** [comment] 2021-06-07 14:07
I think we'd just need to document it.

**Comment by rhatdan** [comment] 2021-06-07 19:07
Could you specify the documentation you want or open a PR?

**Comment by vrothberg** [comment] 2021-06-08 07:21
Sorry, wrong issue.  I think we're good to close it.

**Closed by vrothberg** 2021-06-08 07:21 UTC
