### ISSUE TITLE
"docker build" succeeds but "buildah build" fails with "mv: cannot move"

### ISSUE THREAD

**Issue by eriksjolund** [containers/buildah#4221] opened 2022-09-06 09:45 UTC
**Description**

`docker build -t test .` succeeds but `buildah build -t test .` fails with 
```
mv: cannot move '/etc/bind' to '/srv/conf/etc/': No such file or directory
error building at STEP "RUN mv /etc/bind /srv/conf/etc/": error while running runtime: exit status 1
```
**Steps to reproduce the issue:**

1. Create a directory and cd into it
    ```
    $ mkdir ~/test
    $ cd ~/test
    ```
2. Create the file _~/test/Dockerfile_ with this contents
    ```
    FROM ubuntu:jammy
    VOLUME ["/srv"]
    RUN mkdir -p /srv/conf/etc
    RUN mkdir -p /etc/bind
    RUN mv /etc/bind /srv/conf/etc/
    ```
3. Try to build the container image
    ```
    $ buildah build -t test .
    STEP 1/5: FROM ubuntu:jammy
    Resolved "ubuntu" as an alias (/etc/containers/registries.conf.d/000-shortnames.conf)
    Trying to pull docker.io/library/ubuntu:jammy...
    Getting image source signatures
    Copying blob 00f50047d606 done  
    Copying config 21735dab04 done  
    Writing manifest to image destination
    Storing signatures
    STEP 2/5: VOLUME ["/srv"]
    STEP 3/5: RUN mkdir -p /srv/conf/etc
    STEP 4/5: RUN mkdir -p /etc/bind
    STEP 5/5: RUN mv /etc/bind /srv/conf/etc/
    mv: cannot move '/etc/bind' to '/srv/conf/etc/': No such file or directory
    error building at STEP "RUN mv /etc/bind /srv/conf/etc/": error while running runtime: exit status 1
    ```

**Describe the results you received:**

The command
```
buildah build -t test .
```
failed.

**Describe the results you expected:**

I expected the command 

```
buildah build -t test .
```
to succeed.

**Output of `rpm -q buildah` or `apt list buildah`:**

```
buildah-1.27.0-1.fc37.aarch64
```

**Output of `buildah version`:**

```
Version:         1.27.0
Go Version:      go1.19
Image Spec:      1.0.2-dev
Runtime Spec:    1.0.2-dev
CNI Spec:        1.0.0
libcni Version:  v1.1.2
image Version:   5.22.0
Git Commit:      
Built:           Tue Aug  9 02:08:50 2022
OS/Arch:         linux/arm64
BuildPlatform:   linux/arm64/v8
```

**Output of `cat /etc/*release`:**

```
Fedora release 38 (Rawhide)
NAME="Fedora Linux"
VERSION="38.20220905.91.0 (CoreOS Prerelease)"
ID=fedora
VERSION_ID=38
VERSION_CODENAME=""
PLATFORM_ID="platform:f38"
PRETTY_NAME="Fedora CoreOS 38.20220905.91.0"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:38"
HOME_URL="https://getfedora.org/coreos/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora-coreos/"
SUPPORT_URL="https://github.com/coreos/fedora-coreos-tracker/"
BUG_REPORT_URL="https://github.com/coreos/fedora-coreos-tracker/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=rawhide
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=rawhide
VARIANT="CoreOS"
VARIANT_ID=coreos
OSTREE_VERSION='38.20220905.91.0'
Fedora release 38 (Rawhide)
Fedora release 38 (Rawhide)
```

**Output of `uname -a`:**

```
Linux localhost.localdomain 6.0.0-0.rc3.25.fc38.aarch64 #1 SMP PREEMPT_DYNAMIC Mon Aug 29 12:51:31 UTC 2022 aarch64 GNU/Linux
```

**Output of `cat /etc/containers/storage.conf`:**

```
cat /etc/containers/storage.conf
cat: /etc/containers/storage.conf: No such file or directory
```

**Extra information**

I downloaded __fedora-coreos-38.20220905.91.0-qemu.aarch64.qcow2.xz__ from
https://builds.coreos.fedoraproject.org/browser?stream=rawhide&arch=aarch64
and booted up the VM with qemu on a macbook pro.
Buildah was installed with
```
rpm-ostree install --apply-live buildah
```

**Comment by flouthoc** [comment] 2022-09-06 10:19
@eriksjolund does it work if you do `buildah build -v /srv:/srv:z -t test .`

**Comment by eriksjolund** [comment] 2022-09-06 10:27
The command returns the exit value 125.
```
$ buildah build -v /srv:/srv:z -t test .
STEP 1/5: FROM ubuntu:jammy
STEP 2/5: VOLUME ["/srv"]
STEP 3/5: RUN mkdir -p /srv/conf/etc
error building at STEP "RUN mkdir -p /srv/conf/etc": error resolving mountpoints for container "ed1640f782ad626490444e682ea0f2e677f3317556a5a5b77f78b7eaa4857395": SELinux relabeling of /srv is not allowed
$ echo $?
125
```

**Comment by flouthoc** [comment] 2022-09-06 10:34
@eriksjolund Could you try 
```console
mkdir /tmp/hello
buildah build -v /tmp/hello:/srv:z -t test .
```
also are you expecting `VOLUME ["/srv"]` to create a bind mount of `/srv` from host to container ?

**Comment by rhatdan** [comment] 2022-09-06 10:36
Just try `sudo setenforce 0` And then don't use the :z

**Comment by eriksjolund** [comment] 2022-09-06 10:40
I saw this question https://serverfault.com/questions/1109788/moving-folders-while-building-a-podman-container and wondered whether it was a bug. I made a minimal reproducer and noticed that `docker build` succeeds but `buildah build` fails. 
(I'm note sure whether this issue is a bug)

**Comment by eriksjolund** [comment] 2022-09-06 10:44
```
$ mkdir /tmp/hello
$ buildah build -v /tmp/hello:/srv:z -t test .
STEP 1/5: FROM ubuntu:jammy
STEP 2/5: VOLUME ["/srv"]
STEP 3/5: RUN mkdir -p /srv/conf/etc
STEP 4/5: RUN mkdir -p /etc/bind
STEP 5/5: RUN mv /etc/bind /srv/conf/etc/
mv: cannot move '/etc/bind' to '/srv/conf/etc/': No such file or directory
error building at STEP "RUN mv /etc/bind /srv/conf/etc/": error while running runtime: exit status 1
```
with `setenforce 0`
```
$ sudo setenforce 0
$ buildah build -v /srv:/srv -t test .
STEP 1/5: FROM ubuntu:jammy
STEP 2/5: VOLUME ["/srv"]
STEP 3/5: RUN mkdir -p /srv/conf/etc
STEP 4/5: RUN mkdir -p /etc/bind
STEP 5/5: RUN mv /etc/bind /srv/conf/etc/
mv: cannot move '/etc/bind' to '/srv/conf/etc/': No such file or directory
error building at STEP "RUN mv /etc/bind /srv/conf/etc/": error while running runtime: exit status 1
$ 
```

**Comment by eriksjolund** [comment] 2022-09-06 10:59
> also are you expecting VOLUME ["/srv"] to create a bind mount of /srv from host to container ?

No. I thought building a Dockerfile was independent of other directories on the host (outside of `~/test`)

**Comment by rhatdan** [comment] 2022-09-06 13:11
So this is not SELinux, Now could you try this in rootful mode

**Comment by Molgaard78** [comment] 2022-09-06 14:37
Hi small comment. It is my question that is linked to on ServerFault page.

One important line has been omitted in the minimal reproduction before the "RUN mv /etc/bind/ ..." command and that is installing bind first. :-)

I did it with "RUN apt-get install bind".

Because if bind is not installed, you can ofc not move the folder with bind configuration. ;-)

That aside: 

It looks strange that Docker kan build the file but Buildah cannot?

**Comment by eriksjolund** [comment] 2022-09-06 14:58
Rootful mode fails too.

But a slightly modified Dockerfile works for both rootless and rootful:
```
FROM ubuntu:jammy
VOLUME ["/srv"]
RUN mkdir -p /srv/conf
RUN mkdir -p /etc/bind
RUN mv /etc/bind /srv/conf/
```

Here is a diff:
``` diff
--- Dockerfile.old	2022-09-06 13:41:45.383516067 +0000
+++ Dockerfile.new	2022-09-06 13:41:54.201649117 +0000
@@ -1,6 +1,6 @@
 FROM ubuntu:jammy
 VOLUME ["/srv"]
-RUN mkdir -p /srv/conf/etc
+RUN mkdir -p /srv/conf
 RUN mkdir -p /etc/bind
-RUN mv /etc/bind /srv/conf/etc/
+RUN mv /etc/bind /srv/conf/

```

**Comment by eriksjolund** [comment] 2022-09-06 16:18
Here are the same Dockerfiles as before but I renamed the paths to make them easier to read.

Dockerfile.success 

```
FROM ubuntu:jammy
VOLUME ["/testvol"]
RUN mkdir -p /testvol/test1
RUN mkdir -p /test3
RUN mv /test3 /testvol/test1
```

Dockerfile.failure

```
FROM ubuntu:jammy
VOLUME ["/testvol"]
RUN mkdir -p /testvol/test1/test2
RUN mkdir -p /test3
RUN mv /test3 /testvol/test1/test2
```

diff
``` diff
--- Dockerfile.failure	2022-09-06 14:32:41.125259586 +0000
+++ Dockerfile.success	2022-09-06 14:35:11.510560543 +0000
@@ -1,6 +1,6 @@
 FROM ubuntu:jammy
 VOLUME ["/testvol"]
-RUN mkdir -p /testvol/test1/test2
+RUN mkdir -p /testvol/test1
 RUN mkdir -p /test3
-RUN mv /test3 /testvol/test1/test2
+RUN mv /test3 /testvol/test1
```

**Comment by rhatdan** [comment] 2022-09-06 19:35
@nalind @flouthoc PTAL

**Comment by eriksjolund** [comment] 2022-09-06 19:52
I think it boils down to this difference:

Dockerfile
```
FROM ubuntu:jammy
VOLUME ["/testvol"]
RUN mkdir /testvol
```

```
$ podman build .
STEP 1/3: FROM ubuntu:jammy
STEP 2/3: VOLUME ["/testvol"]
--> Using cache 1154b072bcc2c06edec3c4c87b8c4de7be6f9e2e5b707188d8683a6297dbbe91
--> 1154b072bcc
STEP 3/3: RUN mkdir /testvol
mkdir: cannot create directory '/testvol': File exists
Error: error building at STEP "RUN mkdir /testvol": error while running runtime: exit status 1
$ 
```

```
$ docker build .
[+] Building 1.2s (6/6) FINISHED                                                                     
 => [internal] load build definition from Dockerfile                                            0.0s
 => => transferring dockerfile: 97B                                                             0.0s
 => [internal] load .dockerignore                                                               0.0s
 => => transferring context: 2B                                                                 0.0s
 => [internal] load metadata for docker.io/library/ubuntu:jammy                                 1.1s
 => [1/2] FROM docker.io/library/ubuntu:jammy@sha256:20fa2d7bb4de7723f542be5923b06c4d704370f03  0.0s
 => CACHED [2/2] RUN mkdir /testvol                                                             0.0s
 => exporting to image                                                                          0.0s
 => => exporting layers                                                                         0.0s
 => => writing image sha256:35c9f81fb578b98b88dd729f704a8f6e1523810351a1e96c63211d27045e3e25    0.0s
$ echo $?
0
```

**Comment by nalind** [comment] 2022-09-06 20:09
The VOLUME instruction "freezes" the contents of the named directory so that it can only be subsequently modified with ADD or COPY.  Any effects that RUN instructions that come after VOLUME have on the directory are discarded immediately, so the destination for the "mv" command does not exist.  When I try to build that Dockerfile with an empty build context using moby-engine-20.10.17-5.fc36.x86_64, it also fails at the same spot for the same reason (verified by RUNning "find /srv -ls" right before).  Are you using a different version of `docker build`?

When I try with DOCKER_BUILDKIT=1 in my environment, that first "mkdir" appears to be stopped by SELinux because "mv" is running as "container_t" and trying to write to a /srv that's labeled as "container_ro_file_t", which is not allowed.  In permissive mode, it does appear that the volume's contents aren't being reset after RUN, which is surprising for me, and may be a bug.

**Comment by eriksjolund** [comment] 2022-09-06 20:13
I used this Docker version
```
$ docker --version         
Docker version 20.10.17, build 100c701
```

```
$ docker version  
Client:
 Cloud integration: v1.0.29
 Version:           20.10.17
 API version:       1.41
 Go version:        go1.17.11
 Git commit:        100c701
 Built:             Mon Jun  6 23:04:45 2022
 OS/Arch:           darwin/arm64
 Context:           default
 Experimental:      true

Server: Docker Desktop 4.12.0 (85629)
 Engine:
  Version:          20.10.17
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.11
  Git commit:       a89b842
  Built:            Mon Jun  6 23:01:01 2022
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.8
  GitCommit:        9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by eriksjolund** [comment] 2022-09-06 20:39
Another example of a difference (probably just a variation):

Both __docker__ and __podman__ builds this Dockerfile successfully:

```
FROM ubuntu:jammy
VOLUME ["/testvol"]
RUN mkdir -p /testvol/dir
```

but I see some difference when running the container.


__podman__
```
$ podman run --rm localhost/test ls -ld /testvol/dir
ls: cannot access '/testvol/dir': No such file or directory
$ 
```

__docker__
```
$ docker run --rm localhost/test ls -ld /testvol/dir 
drwxr-xr-x 2 root root 4096 Sep  6 20:36 /testvol/dir
$
```

**Comment by rhatdan** [comment] 2022-09-06 20:43
Does this work if you do

podman run --rm docker-daemon:localhost/test ls -ld /testvol/dir

This should show if the issue is with creation of the image or with podman running the image.

@nalind @flouthoc WDYT?

**Comment by Molgaard78** [comment] 2022-09-06 21:07
> The VOLUME instruction "freezes" the contents of the named directory so that it can only be subsequently modified with ADD or COPY.

Interesting.

I was under the impression that VOLUME was used to define an area where files can be modified and stored between every time the container is restarted as all other files will revert back to original if modified whenever the container is restarted.

I also was under the impression that VOLUME had to be defined in the beginning of the Dockerfile, but if the directory is "frozen" when defined and VOLUME can be called anywhere in Dockerfile, then I could just do all my file movements first and ***then*** use VOLUME.

**Comment by Molgaard78** [comment] 2022-09-07 01:05
I tested out my hyposesis with when to move vs when to declare VOLUME and apparently this work fine with Podman:

```
# First do moving and linking
RUN mkdir -p /storage/conf
RUN mv /etc/bind /storage/conf/
RUN ln -s /storage/conf/bind /etc/bind

# And THEN declare volume.
VOLUME["/storage"]
```

I had issues with SELinux when attempting to fiddle with `/srv` folder, so I just opted to create a different mount point altogether. :-)

I have other issues with my compiled container, but that is outside the scope of this topic.

**Comment by eriksjolund** [comment] 2022-09-07 05:32
### Test on MacBook Pro

> Does this work if you do
>
> podman run --rm docker-daemon:localhost/test ls -ld /testvol/dir

Podman was missing on the MacBook Pro so I first ran `brew install podman`.

Then I tried the command but it failed

```
$ podman run --rm docker-daemon:localhost/test ls -ld /testvol/dir 
Cannot connect to Podman. Please verify your connection to the Linux system using `podman system connection list`, or try `podman machine init` and `podman machine start` to manage a new Linux VM
Error: unable to connect to Podman socket: Get "http://d/v4.2.0/libpod/_ping": dial unix ///var/folders/c9/47tdk4qn5g37zfwjjk0q3wz80000gn/T/podman-run--1/podman/podman.sock: connect: no such file or directory
```


I also tried to have Podman use `unix:///var/run/docker.sock` but it failed
```
$ ls /var/run/docker.sock 
/var/run/docker.sock
$ podman system connection add localdocker unix:///var/run/docker.sock
$ podman system connection default localdocker 
$ podman  run --rm docker-daemon:localhost/test ls -ld /testvol/dir  
Cannot connect to Podman. Please verify your connection to the Linux system using `podman system connection list`, or try `podman machine init` and `podman machine start` to manage a new Linux VM
Error: unable to connect to Podman socket: ping response was 404
```


A test using the `DOCKER_HOST` environment variable failed
```
$ DOCKER_HOST=unix:///var/run/docker.sock podman run --rm docker-daemon:localhost/test ls -ld /testvol/dir
Cannot connect to Podman. Please verify your connection to the Linux system using `podman system connection list`, or try `podman machine init` and `podman machine start` to manage a new Linux VM
Error: unable to connect to Podman socket: Get "http://d/v4.2.0/libpod/_ping": dial unix ///var/folders/c9/47tdk4qn5g37zfwjjk0q3wz80000gn/T/podman-run--1/podman/podman.sock: connect: no such file or directory
```



### Test in the Fedora CoreOS VM

I noticed that the __docker__ command was also installed in the Fedora CoreOS VM.
Trying that one out, I get the same results as with __podman__.

```
$ docker run --rm localhost/test ls -ld /testvol/dir 
ls: cannot access '/testvol/dir': No such file or directory
```

Building the other Dockerfile fails (just like Podman does) 
```
$ cat Dockerfile 
FROM ubuntu:jammy
VOLUME ["/testvol"]
RUN mkdir /testvol
$ podman build --no-cache  .
STEP 1/3: FROM ubuntu:jammy
STEP 2/3: VOLUME ["/testvol"]
--> dd3805005b0
STEP 3/3: RUN mkdir /testvol
mkdir: cannot create directory '/testvol': File exists
Error: error building at STEP "RUN mkdir /testvol": error while running runtime: exit status 1
$ 
```

Here is some info about the Fedora CoreOS VM:
```
$ cat /etc/fedora-release 
Fedora release 38 (Rawhide)
$ docker --version
Docker version 20.10.17, build aa7e414
$ docker version
Client:
 Version:           20.10.17
 API version:       1.41
 Go version:        go1.19
 Git commit:        aa7e414
 Built:             Fri Sep  2 13:47:25 2022
 OS/Arch:           linux/arm64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.17
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.19
  Git commit:       f756502
  Built:            Fri Sep  2 13:47:25 2022
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.8
  GitCommit:        
 runc:
  Version:          1.1.3
  GitCommit:        
 docker-init:
  Version:          0.19.0
  GitCommit:        
```

**Comment by Molgaard78** [comment] 2022-09-07 06:33
> $ podman run --rm docker-daemon:localhost/test ls -ld /testvol/dir

Well on my computer I created the folder `/storage` so this works:

```
[root@server ~]# podman run --rm localhost/samba-ad2:latest ls -ld /storage/conf/etc/samba/*
-rw-r--r--. 1 root root    8 Jul 28 12:07 /storage/conf/etc/samba/gdbcommands
-rw-r--r--. 1 root root 8950 Sep  7 00:35 /storage/conf/etc/samba/smb.conf
drwxr-xr-x. 2 root root    6 Jul 28 12:07 /storage/conf/etc/samba/tls
```

And when running the command:

```
[root@server ~]# podman run --rm localhost/samba-ad2:latest ls -ld /etc/*
```

I can see amongst others:

```
lrwxrwxrwx. 1 root root      23 Sep  7 00:38 /etc/samba -> /storage/conf/etc/samba
```

So I guess I got at least the file structure correct?

**Comment by Molgaard78** [comment] 2022-09-07 06:47
> Building the other Dockerfile fails (just like Podman does)

```
FROM ubuntu:jammy
VOLUME ["/testvol"]
RUN mkdir /testvol
```

Try flyipping the commands RUN and VOLUME in Dockerfile it worked for me.

So you get:

```
FROM ubuntu:jammy
RUN mkdir /testvol
VOLUME ["/testvol"]
```

**Comment by eriksjolund** [comment] 2022-09-07 07:29
I asked in the Moby GitHub project:
* https://github.com/moby/moby/discussions/44104

**Comment by Molgaard78** [comment] 2022-09-07 07:37
Have you tried my suggestion above?

```
FROM ubuntu:jammy
RUN mkdir /testvol
VOLUME ["/testvol"]
```

Note the comment from @nalind:

> The VOLUME instruction "freezes" the contents of the named directory so that it can only be subsequently modified with ADD or COPY. Any effects that RUN instructions that come after VOLUME have on the directory are discarded immediatelyTh.

Therefore:

First do all your work with the `/testvol` folder and **then** expose it via VOLUME.

**Comment by eriksjolund** [comment] 2022-09-07 09:11
@Molgaard78 The Dockerfile 
```
FROM ubuntu:jammy
RUN mkdir /testvol
VOLUME ["/testvol"]
```
is built successfully by podman and docker (both Macbook Pro Docker Desktop and Fedora CoreOS Rawhide docker).

It's more interesting to study:
```
FROM ubuntu:jammy
VOLUME ["/testvol"]
RUN mkdir /testvol
```
because there different results can be seen.
Podman and Docker (Fedora CoreOS rawhide version) give the same result (failure).
Docker (Macbook Pro Docker Desktop) gives a different result (success).

**Comment by Molgaard78** [comment] 2022-09-07 09:16
Okay.

Anyway my container is sort of up and running, though I am fighting with Samba instead, due to a domain restore did not go as smoth as hoped for. :-)

**Comment by nalind** [comment] 2022-09-07 12:46
> I was under the impression that VOLUME was used to define an area where files can be modified and stored between every time the container is restarted as all other files will revert back to original if modified whenever the container is restarted.

Restarting a specific container does not modify the contents of volumes.  Recreating the container, of course, gives the new container a fresh copy of whatever was in the image at that location.

> I also was under the impression that VOLUME had to be defined in the beginning of the Dockerfile, but if the directory is "frozen" when defined and VOLUME can be called anywhere in Dockerfile, then I could just do all my file movements first and _**then**_ use VOLUME.

This is generally what I'd recommend.

**Comment by eriksjolund** [comment] 2022-09-08 18:10
Podman currently implements the classic (legacy) builder functionality.

The newer BuildKit behaves differently. See the explanation: 
https://github.com/moby/moby/discussions/44104#discussioncomment-3593939
See also
https://github.com/moby/moby/issues/3639#issuecomment-482098988

**Comment by flouthoc** [comment] 2022-09-13 06:50
I am closing this issue since this looks resolved, lets open a new issue for buildkit's new behavior and we can work on implementing that. But please re-open this issue if something looks unresolved.

**Closed by flouthoc** 2022-09-13 06:50 UTC

**Comment by eriksjolund** [comment] 2022-09-15 04:33
Feature request created: https://github.com/containers/buildah/issues/4247
