### ISSUE TITLE
Docker references with both a tag and digest are currently not supported

### ISSUE THREAD

**Issue by devurandom** [containers/buildah#1407] opened 2019-03-13 18:33 UTC
**Description**

Buildah 1.7.1 does not support referencing an image (or pulling it from a registry) with both a tag and a digest. I could not find a feature request about this, so I create this one.

**Steps to reproduce the issue:**

```
$ buildah from docker://docker.io/library/clojure:openjdk-8-lein-2.9.1-alpine@sha256:d5454be246358c9cd683a06108ccdecc8b31a0341e45973af480bef708e8cf1e
while pulling "docker://docker.io/library/clojure:openjdk-8-lein-2.9.1-alpine@sha256:d5454be246358c9cd683a06108ccdecc8b31a0341e45973af480bef708e8cf1e" as "docker.io/library/clojure:openjdk-8-lein-2.9.1-alpine@sha256:d5454be246358c9cd683a06108ccdecc8b31a0341e45973af480bef708e8cf1e": error parsing attempted image name "docker://docker.io/library/clojure:openjdk-8-lein-2.9.1-alpine@sha256:d5454be246358c9cd683a06108ccdecc8b31a0341e45973af480bef708e8cf1e": Docker references with both a tag and digest are currently not supported
```

**Comment by TomSweeneyRedHat** [comment] 2019-03-13 18:38
@devurandom Thanks for the issue.

@mtrmac is this anything you forsee changing or should we look into propping up the documentation somehow?

**Comment by mtrmac** [comment] 2019-03-13 19:41
We’ve seen this brought up in a one other place WRT `podman pull`, and Docker does accept that syntax; so, yes, perhaps we would accept this syntax — but _only_ in the compatibility / convenience syntax that does not start with a transport specification (`buildah from docker.io/…`), as handled in Podman’s `pullGoalFromPossiblyUnqualifiedName`.

(We’ve been tentatively discussing sharing the pull code between buildah/libpod; this should probably happen in there.)

I don’t expect this syntax to be supported for the `docker://` transport directly, primarily because the underlying protocol does not allow specifying both at the same time, so its semantics is ambiguous about users’ intent, and the historical practice is problematic:
- Earlier versions of Docker, including 1.13.1, interpret this as “ask for the image with the specified tag, then fail if the manifest does not match the specified digest”. That’s fairly brittle but ultimately plausible (where the tag ~documents the intent and the digest ensure immutability and prevents moving the tag maliciously).
- Later versions of Docker interpret this as “ask for the image with the specified digest, ignore the tag completely”, which is, in my view, mostly pointless and can be actively misleading. If the tag is ignored in the code, the users’ intent can just as well be noted in a comment after the command instead of inside the image specification, and that would be more accurate WRT what is actually happening.

It may turn out to be necessary to support the `:`_tag_`@`_digest_ syntax for compatibility, but especially when the semantics of that syntax goes over time from “risky but plausible” to “actively confusing”, I don’t think it makes sense to support the “actively confusing” semantics in the new `docker://` syntax — and if we are aiming for compatibility, using any but the latest syntax would not be useful either.

**Comment by devurandom** [comment] 2019-03-14 05:05
> Earlier versions of Docker, including 1.13.1, interpret this as “ask for the image with the specified tag, then fail if the manifest does not match the specified digest”. That’s fairly brittle but ultimately plausible (where the tag ~documents the intent and the digest ensure immutability and prevents moving the tag maliciously).

That is what I expected to happen.

**Comment by rhatdan** [comment] 2019-03-14 13:30
How critical is this for you?  Why not just pull by digest?

**Comment by devurandom** [comment] 2019-03-14 18:49
> How critical is this for you? Why not just pull by digest?

I wouldn't say it is critical, but for documentary purposes it is good to have the tag alongside the shasum. I can of course also achieve that by adding a comment (if the file is not JSON, which luckily is seldom these days), which is what I am doing now.

**Comment by rhatdan** [comment] 2019-06-08 18:08
Closing this as I don't see anyone working on it.

**Closed by rhatdan** 2019-06-08 18:08 UTC

**Comment by chanseokoh** [comment] 2020-02-06 23:28
FYI, [Tekton](https://github.com/cri-o/cri-o/issues/2351#issuecomment-583158833) uses both a tag and a digest.

**Comment by chanseokoh** [comment] 2020-03-12 19:45
FYI, crio-o fixed this issue and will support using tag + digest: https://github.com/cri-o/cri-o/issues/2351

**Comment by riconnon** [comment] 2021-05-12 22:42
Throwing my oar in...
I use the `repo:tag@digest` syntax to represent a developer-friendly vs. machine-interpretted version of the same thing, somewhat akin to a modern language package manager (`package.json`/`yarn.lock`, `cargo.toml`/`cargo.lock`)
We use supporting tooling (Renovate: https://docs.renovatebot.com/) which ensures all images referenced by tag have a digest to ensure reproducible builds, and automatically performs CI then auto-merges digest updates which ensures we're aware of breakage when the base images we're using get rebuilt.

The lack of support for this is likely deal breaking for me on the whole `containers` ecosystem.

**Comment by TomSweeneyRedHat** [comment] 2021-05-14 20:20
@riconnon would you mind opening a new issue about what you'd like to see exactly?  I'm not entirely clear and would like a dedicated space to discuss/consider it.  Thanks!

**Comment by rarkins** [comment] 2021-06-23 07:29
@TomSweeneyRedHat I have opened https://github.com/containers/buildah/issues/3331
